// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package goTypeBase

type DomainDiceJson struct {
	// Description corresponds to the JSON schema field "Description".
	Description *string `json:"Description,omitempty" yaml:"Description,omitempty" mapstructure:"Description,omitempty"`

	// IsActive corresponds to the JSON schema field "IsActive".
	IsActive *bool `json:"IsActive,omitempty" yaml:"IsActive,omitempty" mapstructure:"IsActive,omitempty"`

	// Maximum corresponds to the JSON schema field "Maximum".
	Maximum float64 `json:"Maximum" yaml:"Maximum" mapstructure:"Maximum"`

	// Minimum corresponds to the JSON schema field "Minimum".
	Minimum float64 `json:"Minimum" yaml:"Minimum" mapstructure:"Minimum"`

	// Title corresponds to the JSON schema field "Title".
	Title *string `json:"Title,omitempty" yaml:"Title,omitempty" mapstructure:"Title,omitempty"`

	// Id corresponds to the JSON schema field "id".
	Id *float64 `json:"id,omitempty" yaml:"id,omitempty" mapstructure:"id,omitempty"`
}
