//*** CAUTION ***
//This is an autogenerated file produced by generateTypes.py.
//Edits made here will not persist after regeneration.
import { IsEqual } from "type-fest";import { SchemaObject } from "../SchemaObject";
import { Campaign as Base__Campaign } from "../coreTypes/Campaign";
import { Character as Base__Character } from "../coreTypes/Character";
import { CharacterDomainConditionInstance as Base__CharacterDomainConditionInstance } from "../coreTypes/CharacterDomainConditionInstance";
import { CharacterDomainEntityStatInstance as Base__CharacterDomainEntityStatInstance } from "../coreTypes/CharacterDomainEntityStatInstance";
import { CharacterDomainSubClassInstance as Base__CharacterDomainSubClassInstance } from "../coreTypes/CharacterDomainSubClassInstance";
import { ClassPrimaryAbility as Base__ClassPrimaryAbility } from "../coreTypes/ClassPrimaryAbility";
import { ClassSave as Base__ClassSave } from "../coreTypes/ClassSave";
import { ClassSpell as Base__ClassSpell } from "../coreTypes/ClassSpell";
import { DomainAction as Base__DomainAction } from "../coreTypes/DomainAction";
import { DomainAppRole as Base__DomainAppRole } from "../coreTypes/DomainAppRole";
import { DomainArmor as Base__DomainArmor } from "../coreTypes/DomainArmor";
import { DomainArmorCategory as Base__DomainArmorCategory } from "../coreTypes/DomainArmorCategory";
import { DomainBooleanCondition as Base__DomainBooleanCondition } from "../coreTypes/DomainBooleanCondition";
import { DomainClass as Base__DomainClass } from "../coreTypes/DomainClass";
import { DomainClassLevelAddition as Base__DomainClassLevelAddition } from "../coreTypes/DomainClassLevelAddition";
import { DomainClassResource as Base__DomainClassResource } from "../coreTypes/DomainClassResource";
import { DomainClassTrait as Base__DomainClassTrait } from "../coreTypes/DomainClassTrait";
import { DomainCondition as Base__DomainCondition } from "../coreTypes/DomainCondition";
import { DomainCreatureType as Base__DomainCreatureType } from "../coreTypes/DomainCreatureType";
import { DomainCurrencyDenomination as Base__DomainCurrencyDenomination } from "../coreTypes/DomainCurrencyDenomination";
import { DomainDamageType as Base__DomainDamageType } from "../coreTypes/DomainDamageType";
import { DomainDice as Base__DomainDice } from "../coreTypes/DomainDice";
import { DomainDiceRollSubType as Base__DomainDiceRollSubType } from "../coreTypes/DomainDiceRollSubType";
import { DomainDiceRollType as Base__DomainDiceRollType } from "../coreTypes/DomainDiceRollType";
import { DomainEntityStat as Base__DomainEntityStat } from "../coreTypes/DomainEntityStat";
import { DomainItem as Base__DomainItem } from "../coreTypes/DomainItem";
import { DomainItemGroup as Base__DomainItemGroup } from "../coreTypes/DomainItemGroup";
import { DomainLanguage as Base__DomainLanguage } from "../coreTypes/DomainLanguage";
import { DomainModifierMechanic as Base__DomainModifierMechanic } from "../coreTypes/DomainModifierMechanic";
import { DomainProficiencyOption as Base__DomainProficiencyOption } from "../coreTypes/DomainProficiencyOption";
import { DomainQuantifierVariant as Base__DomainQuantifierVariant } from "../coreTypes/DomainQuantifierVariant";
import { DomainSize as Base__DomainSize } from "../coreTypes/DomainSize";
import { DomainSkill as Base__DomainSkill } from "../coreTypes/DomainSkill";
import { DomainSpecies as Base__DomainSpecies } from "../coreTypes/DomainSpecies";
import { DomainSpell as Base__DomainSpell } from "../coreTypes/DomainSpell";
import { DomainSpellSchool as Base__DomainSpellSchool } from "../coreTypes/DomainSpellSchool";
import { DomainStaticEffect as Base__DomainStaticEffect } from "../coreTypes/DomainStaticEffect";
import { DomainSubClass as Base__DomainSubClass } from "../coreTypes/DomainSubClass";
import { DomainTool as Base__DomainTool } from "../coreTypes/DomainTool";
import { DomainToolCategory as Base__DomainToolCategory } from "../coreTypes/DomainToolCategory";
import { DomainWeapon as Base__DomainWeapon } from "../coreTypes/DomainWeapon";
import { DomainWeaponCategory as Base__DomainWeaponCategory } from "../coreTypes/DomainWeaponCategory";
import { DomainWeaponDomainWeaponCategoryInstance as Base__DomainWeaponDomainWeaponCategoryInstance } from "../coreTypes/DomainWeaponDomainWeaponCategoryInstance";
import { EvaluatedConditional as Base__EvaluatedConditional } from "../coreTypes/EvaluatedConditional";
import { ItemDomainItemGroupInstance as Base__ItemDomainItemGroupInstance } from "../coreTypes/ItemDomainItemGroupInstance";
import { Quantifier as Base__Quantifier } from "../coreTypes/Quantifier";
import { QuantifierCostSpecifier as Base__QuantifierCostSpecifier } from "../coreTypes/QuantifierCostSpecifier";
import { User as Base__User } from "../coreTypes/User";
import { UserRoleInstance as Base__UserRoleInstance } from "../coreTypes/UserRoleInstance";

const BaseAppTypes = {
	Campaign: {} as Base__Campaign,
	Character: {} as Base__Character,
	CharacterDomainConditionInstance: {} as Base__CharacterDomainConditionInstance,
	CharacterDomainEntityStatInstance: {} as Base__CharacterDomainEntityStatInstance,
	CharacterDomainSubClassInstance: {} as Base__CharacterDomainSubClassInstance,
	ClassPrimaryAbility: {} as Base__ClassPrimaryAbility,
	ClassSave: {} as Base__ClassSave,
	ClassSpell: {} as Base__ClassSpell,
	DomainAction: {} as Base__DomainAction,
	DomainAppRole: {} as Base__DomainAppRole,
	DomainArmor: {} as Base__DomainArmor,
	DomainArmorCategory: {} as Base__DomainArmorCategory,
	DomainBooleanCondition: {} as Base__DomainBooleanCondition,
	DomainClass: {} as Base__DomainClass,
	DomainClassLevelAddition: {} as Base__DomainClassLevelAddition,
	DomainClassResource: {} as Base__DomainClassResource,
	DomainClassTrait: {} as Base__DomainClassTrait,
	DomainCondition: {} as Base__DomainCondition,
	DomainCreatureType: {} as Base__DomainCreatureType,
	DomainCurrencyDenomination: {} as Base__DomainCurrencyDenomination,
	DomainDamageType: {} as Base__DomainDamageType,
	DomainDice: {} as Base__DomainDice,
	DomainDiceRollSubType: {} as Base__DomainDiceRollSubType,
	DomainDiceRollType: {} as Base__DomainDiceRollType,
	DomainEntityStat: {} as Base__DomainEntityStat,
	DomainItem: {} as Base__DomainItem,
	DomainItemGroup: {} as Base__DomainItemGroup,
	DomainLanguage: {} as Base__DomainLanguage,
	DomainModifierMechanic: {} as Base__DomainModifierMechanic,
	DomainProficiencyOption: {} as Base__DomainProficiencyOption,
	DomainQuantifierVariant: {} as Base__DomainQuantifierVariant,
	DomainSize: {} as Base__DomainSize,
	DomainSkill: {} as Base__DomainSkill,
	DomainSpecies: {} as Base__DomainSpecies,
	DomainSpell: {} as Base__DomainSpell,
	DomainSpellSchool: {} as Base__DomainSpellSchool,
	DomainStaticEffect: {} as Base__DomainStaticEffect,
	DomainSubClass: {} as Base__DomainSubClass,
	DomainTool: {} as Base__DomainTool,
	DomainToolCategory: {} as Base__DomainToolCategory,
	DomainWeapon: {} as Base__DomainWeapon,
	DomainWeaponCategory: {} as Base__DomainWeaponCategory,
	DomainWeaponDomainWeaponCategoryInstance: {} as Base__DomainWeaponDomainWeaponCategoryInstance,
	EvaluatedConditional: {} as Base__EvaluatedConditional,
	ItemDomainItemGroupInstance: {} as Base__ItemDomainItemGroupInstance,
	Quantifier: {} as Base__Quantifier,
	QuantifierCostSpecifier: {} as Base__QuantifierCostSpecifier,
	User: {} as Base__User,
	UserRoleInstance: {} as Base__UserRoleInstance,
} as const satisfies Record<string, SchemaObject> 


//This prevents any circular relationships from initializing infinitely, even though Typescript
//will allow that sort of type recursion (this mirrors the backend's circular relationship checks)
type RecursionGuardedSchemaObject<T extends SchemaObject, G extends (typeof BaseAppTypes[keyof typeof BaseAppTypes]) = undefined> = IsEqual<G | T, G> extends true? 
	//Circular catch case if the type is in our "seen before" union (with a tuple wrap to interpret the "extends any of the stuff in this union" conditional properly)
	undefined
	:
	{
		Id: T["Id"],
		Attributes: T["Attributes"],
		Relationships: {
			ManyToOne: {[key in keyof T["Relationships"]["ManyToOne"]]: RecursionGuardedSchemaObject<T["Relationships"]["ManyToOne"][key], G extends undefined? T : G | T>},
			//Extra handling to have the circular catch case resolve as undefined instead of undefined[]
			OneToMany: {[key in keyof T["Relationships"]["OneToMany"]]: RecursionGuardedSchemaObject<T["Relationships"]["OneToMany"][key][number], G extends undefined? T : G | T> extends undefined? 
				undefined 
				: 
				RecursionGuardedSchemaObject<T["Relationships"]["OneToMany"][key][number], G extends undefined? T : G | T>[]
			},
		}
	}

export type Campaign = RecursionGuardedSchemaObject<Base__Campaign>;
export type Character = RecursionGuardedSchemaObject<Base__Character>;
export type CharacterDomainConditionInstance = RecursionGuardedSchemaObject<Base__CharacterDomainConditionInstance>;
export type CharacterDomainEntityStatInstance = RecursionGuardedSchemaObject<Base__CharacterDomainEntityStatInstance>;
export type CharacterDomainSubClassInstance = RecursionGuardedSchemaObject<Base__CharacterDomainSubClassInstance>;
export type ClassPrimaryAbility = RecursionGuardedSchemaObject<Base__ClassPrimaryAbility>;
export type ClassSave = RecursionGuardedSchemaObject<Base__ClassSave>;
export type ClassSpell = RecursionGuardedSchemaObject<Base__ClassSpell>;
export type DomainAction = RecursionGuardedSchemaObject<Base__DomainAction>;
export type DomainAppRole = RecursionGuardedSchemaObject<Base__DomainAppRole>;
export type DomainArmor = RecursionGuardedSchemaObject<Base__DomainArmor>;
export type DomainArmorCategory = RecursionGuardedSchemaObject<Base__DomainArmorCategory>;
export type DomainBooleanCondition = RecursionGuardedSchemaObject<Base__DomainBooleanCondition>;
export type DomainClass = RecursionGuardedSchemaObject<Base__DomainClass>;
export type DomainClassLevelAddition = RecursionGuardedSchemaObject<Base__DomainClassLevelAddition>;
export type DomainClassResource = RecursionGuardedSchemaObject<Base__DomainClassResource>;
export type DomainClassTrait = RecursionGuardedSchemaObject<Base__DomainClassTrait>;
export type DomainCondition = RecursionGuardedSchemaObject<Base__DomainCondition>;
export type DomainCreatureType = RecursionGuardedSchemaObject<Base__DomainCreatureType>;
export type DomainCurrencyDenomination = RecursionGuardedSchemaObject<Base__DomainCurrencyDenomination>;
export type DomainDamageType = RecursionGuardedSchemaObject<Base__DomainDamageType>;
export type DomainDice = RecursionGuardedSchemaObject<Base__DomainDice>;
export type DomainDiceRollSubType = RecursionGuardedSchemaObject<Base__DomainDiceRollSubType>;
export type DomainDiceRollType = RecursionGuardedSchemaObject<Base__DomainDiceRollType>;
export type DomainEntityStat = RecursionGuardedSchemaObject<Base__DomainEntityStat>;
export type DomainItem = RecursionGuardedSchemaObject<Base__DomainItem>;
export type DomainItemGroup = RecursionGuardedSchemaObject<Base__DomainItemGroup>;
export type DomainLanguage = RecursionGuardedSchemaObject<Base__DomainLanguage>;
export type DomainModifierMechanic = RecursionGuardedSchemaObject<Base__DomainModifierMechanic>;
export type DomainProficiencyOption = RecursionGuardedSchemaObject<Base__DomainProficiencyOption>;
export type DomainQuantifierVariant = RecursionGuardedSchemaObject<Base__DomainQuantifierVariant>;
export type DomainSize = RecursionGuardedSchemaObject<Base__DomainSize>;
export type DomainSkill = RecursionGuardedSchemaObject<Base__DomainSkill>;
export type DomainSpecies = RecursionGuardedSchemaObject<Base__DomainSpecies>;
export type DomainSpell = RecursionGuardedSchemaObject<Base__DomainSpell>;
export type DomainSpellSchool = RecursionGuardedSchemaObject<Base__DomainSpellSchool>;
export type DomainStaticEffect = RecursionGuardedSchemaObject<Base__DomainStaticEffect>;
export type DomainSubClass = RecursionGuardedSchemaObject<Base__DomainSubClass>;
export type DomainTool = RecursionGuardedSchemaObject<Base__DomainTool>;
export type DomainToolCategory = RecursionGuardedSchemaObject<Base__DomainToolCategory>;
export type DomainWeapon = RecursionGuardedSchemaObject<Base__DomainWeapon>;
export type DomainWeaponCategory = RecursionGuardedSchemaObject<Base__DomainWeaponCategory>;
export type DomainWeaponDomainWeaponCategoryInstance = RecursionGuardedSchemaObject<Base__DomainWeaponDomainWeaponCategoryInstance>;
export type EvaluatedConditional = RecursionGuardedSchemaObject<Base__EvaluatedConditional>;
export type ItemDomainItemGroupInstance = RecursionGuardedSchemaObject<Base__ItemDomainItemGroupInstance>;
export type Quantifier = RecursionGuardedSchemaObject<Base__Quantifier>;
export type QuantifierCostSpecifier = RecursionGuardedSchemaObject<Base__QuantifierCostSpecifier>;
export type User = RecursionGuardedSchemaObject<Base__User>;
export type UserRoleInstance = RecursionGuardedSchemaObject<Base__UserRoleInstance>;

export const AppTypes = {
	Campaign: {} as Campaign,
	Character: {} as Character,
	CharacterDomainConditionInstance: {} as CharacterDomainConditionInstance,
	CharacterDomainEntityStatInstance: {} as CharacterDomainEntityStatInstance,
	CharacterDomainSubClassInstance: {} as CharacterDomainSubClassInstance,
	ClassPrimaryAbility: {} as ClassPrimaryAbility,
	ClassSave: {} as ClassSave,
	ClassSpell: {} as ClassSpell,
	DomainAction: {} as DomainAction,
	DomainAppRole: {} as DomainAppRole,
	DomainArmor: {} as DomainArmor,
	DomainArmorCategory: {} as DomainArmorCategory,
	DomainBooleanCondition: {} as DomainBooleanCondition,
	DomainClass: {} as DomainClass,
	DomainClassLevelAddition: {} as DomainClassLevelAddition,
	DomainClassResource: {} as DomainClassResource,
	DomainClassTrait: {} as DomainClassTrait,
	DomainCondition: {} as DomainCondition,
	DomainCreatureType: {} as DomainCreatureType,
	DomainCurrencyDenomination: {} as DomainCurrencyDenomination,
	DomainDamageType: {} as DomainDamageType,
	DomainDice: {} as DomainDice,
	DomainDiceRollSubType: {} as DomainDiceRollSubType,
	DomainDiceRollType: {} as DomainDiceRollType,
	DomainEntityStat: {} as DomainEntityStat,
	DomainItem: {} as DomainItem,
	DomainItemGroup: {} as DomainItemGroup,
	DomainLanguage: {} as DomainLanguage,
	DomainModifierMechanic: {} as DomainModifierMechanic,
	DomainProficiencyOption: {} as DomainProficiencyOption,
	DomainQuantifierVariant: {} as DomainQuantifierVariant,
	DomainSize: {} as DomainSize,
	DomainSkill: {} as DomainSkill,
	DomainSpecies: {} as DomainSpecies,
	DomainSpell: {} as DomainSpell,
	DomainSpellSchool: {} as DomainSpellSchool,
	DomainStaticEffect: {} as DomainStaticEffect,
	DomainSubClass: {} as DomainSubClass,
	DomainTool: {} as DomainTool,
	DomainToolCategory: {} as DomainToolCategory,
	DomainWeapon: {} as DomainWeapon,
	DomainWeaponCategory: {} as DomainWeaponCategory,
	DomainWeaponDomainWeaponCategoryInstance: {} as DomainWeaponDomainWeaponCategoryInstance,
	EvaluatedConditional: {} as EvaluatedConditional,
	ItemDomainItemGroupInstance: {} as ItemDomainItemGroupInstance,
	Quantifier: {} as Quantifier,
	QuantifierCostSpecifier: {} as QuantifierCostSpecifier,
	User: {} as User,
	UserRoleInstance: {} as UserRoleInstance,
} as const satisfies Record<string, SchemaObject> 