export const themeDefault = {
    "--text-color-primary": "#444746",
    "--color-background": "#e8eef1",
    "--color-primary": "#354156",
    "--color-success": "#4d967b",
    "--color-warning": "#ffca30",
    "--color-error": "#e02045",
    "--spacing-small": "1rem",
    "--spacing-medium": "2rem",
    "--spacing-large": "4rem",
    "--duration-paused": "paused",
    "--duration-slow": "3s",
    "--duration-fast": "500ms",
    "--easing-paused": "paused",
    "--easing-slow": "3s",
    "--easing-fast": "500ms",
    "--radius-large": "4rem",
    "--radius-small": "2rem",
    "--font-family-body": "Arial, Helvetica, sans-serif",
    "--font-family-headings": "Palatino Linotype, serif",
    "--font-size-caption": "12px",
    "--font-size-body": "16px",
    "--font-size-heading": "26px",
} as const;

export const testDarkTheme: Record<ThemeVariables, string> = {
    "--text-color-primary": "#e8eef1",
    "--color-background": "#354156",
    "--color-primary": "#354156",
    "--color-success": "#4d967b",
    "--color-warning": "#ffca30",
    "--color-error": "#e02045",
    "--spacing-small": "1rem",
    "--spacing-medium": "2rem",
    "--spacing-large": "4rem",
    "--duration-paused": "paused",
    "--duration-slow": "3s",
    "--duration-fast": "500ms",
    "--easing-paused": "paused",
    "--easing-slow": "3s",
    "--easing-fast": "500ms",
    "--radius-large": "4rem",
    "--radius-small": "2rem",
    "--font-family-body": "Arial, Helvetica, sans-serif",
    "--font-family-headings": "Palatino Linotype, serif",
    "--font-size-caption": "12px",
    "--font-size-body": "16px",
    "--font-size-heading": "26px",
} as const;

export type ThemeVariables = keyof typeof themeDefault 

function produceThemeVariablesFile() {
    const autogeneratedWarningMessage = [
        '/* *** CAUTION *** */',
        '/* This is an autogenerated file produced by regenerateFrontendTheme.py. */',
        '/* Edits made here will not persist after regeneration. */',
    ]

    autogeneratedWarningMessage.forEach(line => console.log(line))
    console.log("")
    console.log(":root {")

    //Instead of explicitly writing to a file, we're just producing some console output to pipe in at the script level (because I'm lazy)
    Object.keys(themeDefault).forEach((variable) => console.log("   " + variable + ": " + themeDefault[variable as keyof typeof themeDefault] + ";"));
    console.log("}")
}

produceThemeVariablesFile();