//*** CAUTION ***
//This is an autogenerated file produced by regenerateBackend.py.
//Edits made here will not persist after backend regeneration.

package generatedServices
import (
   "errors"
   "reflect"
   types "AdventureEngineServer/generatedDatabaseTypes"
   "gorm.io/gorm"
)

func GetCampaigns(db *gorm.DB, campaigns *[]types.Campaign) error {
   result := db.Table("Campaign").Find(campaigns)
   return result.Error
}

func GetCampaignById(db *gorm.DB, id int, campaign *types.Campaign) error {
   result := db.Table("Campaign").First(campaign, id)
   return result.Error
}

func SaveCampaign(db *gorm.DB, campaigns []*types.Campaign) error {
   tx := db.Begin()
   
   if tx.Error != nil {
      return errors.New("Could not initialize transaction to save " + reflect.TypeOf(campaigns).Name() + " entity")
   }
   
   defer func() {
      if r := recover(); r != nil {
         tx.Rollback()
      }
   }()
   
   if err := tx.Error; err != nil {
      return err
   }
   
   if err := tx.Table("Campaign").Save(campaigns).Error; err != nil {
      tx.Rollback()
      return err
   }
   
   return tx.Commit().Error
}

