//*** CAUTION ***
//This is an autogenerated file produced by regenerateBackend.py.
//Edits made here will not persist after backend regeneration.

package generatedServices
import (
   "errors"
   "reflect"
   types "AdventureEngineServer/generatedDatabaseTypes"
   "gorm.io/gorm"
)

func GetCampaigns(db *gorm.DB, campaigns *[]types.Campaign) error {
   result := db.Table("Campaign").Find(campaigns)
   return result.Error
}

func GetCampaignById(db *gorm.DB, id int, campaign *types.Campaign) error {
   result := db.Table("Campaign").First(campaign, id)
   return result.Error
}

func SaveCampaign(db *gorm.DB, campaign *types.Campaign) error {
   tx := db.Begin()
   
   if tx.Error != nil {
   return errors.New("Could not initialize transaction to save " + reflect.TypeOf(campaign).Name() + " entity")
   }
   
   defer func() {
      if r := recover(); r != nil {
         tx.Rollback()
      }
   }()
   
   if err := tx.Error; err != nil {
      return err
   }
   
   if campaign.Id != nil {
      print("Saving\n")
      if err := tx.Table("Campaign").Save(campaign).Error; err != nil {
         tx.Rollback()
         return err
      }
   } else {
      print("Creating\n")
      if err := tx.Table("Campaign").Create(campaign).Error; err != nil {
         tx.Rollback()
         return err
      }
      print(campaign.Id)
   }
   
   return tx.Commit().Error
}

