//*** CAUTION ***
//This is an autogenerated file produced by regenerateBackend.py.
//Edits made here will not persist after backend regeneration.

package generatedServices
import (
   "errors"
   "gorm.io/gorm"
   "reflect"
   types "AdventureEngineServer/generatedDatabaseTypes"
   utils "AdventureEngineServer/utils"
)

func GetClassSpells(db *gorm.DB, classSpells *[]types.ClassSpell, filters *[]utils.FilterExpression) error {
   filteredContext, err := utils.FilterTableContext(db.Table("ClassSpell"), filters)
   if err != nil {
      return err
   }
   result := filteredContext.Find(classSpells)
   return result.Error
}

func GetClassSpellById(db *gorm.DB, id int, classSpell *types.ClassSpell) error {
   result := db.Table("ClassSpell").First(classSpell, id)
   return result.Error
}

func SaveClassSpell(db *gorm.DB, classSpells []*types.ClassSpell) error {
   tx := db.Begin()
   
   if tx.Error != nil {
      return errors.New("Could not initialize transaction to save " + reflect.TypeOf(classSpells).Name() + " entity")
   }
   
   defer func() {
      if r := recover(); r != nil {
         tx.Rollback()
      }
   }()
   
   if err := tx.Error; err != nil {
      return err
   }
   
   if err := tx.Table("ClassSpell").Save(classSpells).Error; err != nil {
      tx.Rollback()
      return err
   }
   
   return tx.Commit().Error
}

