//*** CAUTION ***
//This is an autogenerated file produced by regenerateBackend.py.
//Edits made here will not persist after backend regeneration.

package generatedServices
import (
   "errors"
   "reflect"
   types "AdventureEngineServer/generatedDatabaseTypes"
   "gorm.io/gorm"
)

func GetDomainActions(db *gorm.DB, domainActions *[]types.DomainAction) error {
   result := db.Table("DomainAction").Find(domainActions)
   return result.Error
}

func GetDomainActionById(db *gorm.DB, id int, domainAction *types.DomainAction) error {
   result := db.Table("DomainAction").First(domainAction, id)
   return result.Error
}

func SaveDomainAction(db *gorm.DB, domainActions []*types.DomainAction) error {
   tx := db.Begin()
   
   if tx.Error != nil {
      return errors.New("Could not initialize transaction to save " + reflect.TypeOf(domainActions).Name() + " entity")
   }
   
   defer func() {
      if r := recover(); r != nil {
         tx.Rollback()
      }
   }()
   
   if err := tx.Error; err != nil {
      return err
   }
   
   if err := tx.Table("DomainAction").Create(domainActions).Error; err != nil {
      tx.Rollback()
      return err
   }
   
   return tx.Commit().Error
}

