//*** CAUTION ***
//This is an autogenerated file produced by regenerateBackend.py.
//Edits made here will not persist after backend regeneration.

package generatedServices
import (
   "errors"
   "reflect"
   types "AdventureEngineServer/generatedDatabaseTypes"
   "gorm.io/gorm"
)

func GetDomainDices(db *gorm.DB, domainDices *[]types.DomainDice) error {
   result := db.Table("DomainDice").Find(domainDices)
   return result.Error
}

func GetDomainDiceById(db *gorm.DB, id int, domainDice *types.DomainDice) error {
   result := db.Table("DomainDice").First(domainDice, id)
   return result.Error
}

func SaveDomainDice(db *gorm.DB, domainDice *types.DomainDice) error {
   tx := db.Begin()
   
   if tx.Error != nil {
   return errors.New("Could not initialize transaction to save " + reflect.TypeOf(domainDice).Name() + " entity")
   }
   
   defer func() {
      if r := recover(); r != nil {
         tx.Rollback()
      }
   }()
   
   if err := tx.Error; err != nil {
      return err
   }
   
   if domainDice.Id != nil {
      print("Saving\n")
      if err := tx.Table("DomainDice").Save(domainDice).Error; err != nil {
         tx.Rollback()
         return err
      }
   } else {
      print("Creating\n")
      if err := tx.Table("DomainDice").Create(domainDice).Error; err != nil {
         tx.Rollback()
         return err
      }
      print(domainDice.Id)
   }
   
   return tx.Commit().Error
}

