//*** CAUTION ***
//This is an autogenerated file produced by regenerateBackend.py.
//Edits made here will not persist after backend regeneration.

package generatedServices
import (
   "errors"
   "reflect"
   contextProviders "AdventureEngineServer/contextProviders"
   types "AdventureEngineServer/generatedDatabaseTypes"
   utils "AdventureEngineServer/utils"
)

func GetDomainClasss(context *contextProviders.ServiceContext, args *contextProviders.GetArgs[types.DomainClass]) (contextProviders.GetReturn[types.DomainClass], error) {
   if context == nil {
      return nil, errors.New("No service context provided")
   }
   
   if args == nil {
      return nil, errors.New("No service arguments provided")
   }
   
   if context.DatabaseContext == nil {
      return nil, errors.New("Cannot perform get action on nil database context")
   }
   
   var returnBuffer []types.DomainClass
   
   filteredContext, err := utils.FilterTableContext(context.DatabaseContext.Table("DomainClass"), args.Filters)
   
   if err != nil {
      return nil, err
   }
   result := filteredContext.Find(&returnBuffer)
   
   if result.Error != nil {
      return nil, result.Error
   }
   
   return returnBuffer, nil
}

func GetDomainClassById(context *contextProviders.ServiceContext, args *contextProviders.GetByIdArgs[types.DomainClass]) (contextProviders.GetByIdReturn[types.DomainClass], error) {
   if context == nil {
      return nil, errors.New("No service context provided")
   }
   
   if args == nil {
      return nil, errors.New("No service arguments provided")
   }
   
   if context.DatabaseContext == nil {
      return nil, errors.New("Cannot perform get by id action on nil database context")
   }
   
   var returnPtr *types.DomainClass
   result := context.DatabaseContext.Table("DomainClass").First(returnPtr, args.Id)
   if result.Error != nil {
      return nil, result.Error
   }
   
   return returnPtr, nil
}

func SaveDomainClass(context *contextProviders.ServiceContext, args *contextProviders.SaveArgs[types.DomainClass]) (contextProviders.SaveReturn[types.DomainClass], error) {
   if context == nil {
      return nil, errors.New("No service context provided")
   }
   
   if args == nil {
      return nil, errors.New("No service arguments provided")
   }
   
   if context.DatabaseContext == nil {
      return nil, errors.New("Cannot perform save action on nil database context")
   }
   
   tx := context.DatabaseContext.Begin()
   
   if tx.Error != nil {
      return nil, errors.New("Could not initialize transaction to save " + reflect.TypeOf(args.Items).Name() + " entity")
   }
   
   defer func() {
      if r := recover(); r != nil {
         tx.Rollback()
      }
   }()
   
   if err := tx.Error; err != nil {
      return nil, err
   }
   
   if err := tx.Table("DomainClass").Save(args.Items).Error; err != nil {
      tx.Rollback()
      return nil, err
   }
   if tx.Commit().Error != nil {
      return nil, tx.Commit().Error
   }
   
   return args.Items, nil
}
