//*** CAUTION ***
//This is an autogenerated file produced by regenerateBackend.py.
//Edits made here will not persist after backend regeneration.

package generatedservices
import (
   "errors"
   "reflect"
   types "AdventureEngineServer/generatedTypes"
   "gorm.io/gorm"
)

func GetDomainConditions(db *gorm.DB, domainConditions *[]types.DomainConditionJson) error {
   result := db.Find(domainConditions)
   return result.Error
}

func GetDomainConditionById(db *gorm.DB, id int, domainCondition *types.DomainConditionJson) error {
   result := db.First(domainCondition, id)
   return result.Error
}

func SaveDomainCondition(db *gorm.DB, domainCondition *types.DomainConditionJson) error {
   tx := db.Begin()
   
   if tx.Error != nil {
   return errors.New("Could not initialize transaction to save " + reflect.TypeOf(domainCondition).Name() + " entity")
   }
   
   defer func() {
      if r := recover(); r != nil {
         tx.Rollback()
      }
   }()
   
   if err := tx.Error; err != nil {
      return err
   }
   
   if err := tx.Save(domainCondition).Error; err != nil {
      tx.Rollback()
      return err
   }
   
   return tx.Commit().Error
}
