//*** CAUTION ***
//This is an autogenerated file produced by regenerateBackend.py.
//Edits made here will not persist after backend regeneration.

package generatedServices
import (
   "errors"
   "reflect"
   types "AdventureEngineServer/generatedDatabaseTypes"
   "gorm.io/gorm"
)

func GetDomainClasss(db *gorm.DB, domainClasss *[]types.DomainClass) error {
   result := db.Table("DomainClass").Find(domainClasss)
   return result.Error
}

func GetDomainClassById(db *gorm.DB, id int, domainClass *types.DomainClass) error {
   result := db.Table("DomainClass").First(domainClass, id)
   return result.Error
}

func SaveDomainClass(db *gorm.DB, domainClass *types.DomainClass) error {
   tx := db.Begin()
   
   if tx.Error != nil {
   return errors.New("Could not initialize transaction to save " + reflect.TypeOf(domainClass).Name() + " entity")
   }
   
   defer func() {
      if r := recover(); r != nil {
         tx.Rollback()
      }
   }()
   
   if err := tx.Error; err != nil {
      return err
   }
   
   if err := tx.Save(domainClass).Error; err != nil {
      tx.Rollback()
      return err
   }
   
   return tx.Commit().Error
}

