//*** CAUTION ***
//This is an autogenerated file produced by regenerateBackend.py.
//Edits made here will not persist after backend regeneration.

package generatedservices
import (
   "errors"
   "reflect"
   types "AdventureEngineServer/generatedTypes"
   "gorm.io/gorm"
)

func GetDomainSizes(db *gorm.DB, domainSizes *[]types.DomainSizeJson) error {
   result := db.Find(domainSizes)
   return result.Error
}

func GetDomainSizeById(db *gorm.DB, id int, domainSize *types.DomainSizeJson) error {
   result := db.First(domainSize, id)
   return result.Error
}

func SaveDomainSize(db *gorm.DB, domainSize *types.DomainSizeJson) error {
   tx := db.Begin()
   
   if tx.Error != nil {
   return errors.New("Could not initialize transaction to save " + reflect.TypeOf(domainSize).Name() + " entity")
   }
   
   defer func() {
      if r := recover(); r != nil {
         tx.Rollback()
      }
   }()
   
   if err := tx.Error; err != nil {
      return err
   }
   
   if err := tx.Save(domainSize).Error; err != nil {
      tx.Rollback()
      return err
   }
   
   return tx.Commit().Error
}
