//*** CAUTION ***
//This is an autogenerated file produced by regenerateBackend.py.
//Edits made here will not persist after backend regeneration.

package generatedServices
import (
   "errors"
   "reflect"
   types "AdventureEngineServer/generatedDatabaseTypes"
   "gorm.io/gorm"
)

func GetDomainConditions(db *gorm.DB, domainConditions *[]types.DomainCondition) error {
   result := db.Table("DomainCondition").Find(domainConditions)
   return result.Error
}

func GetDomainConditionById(db *gorm.DB, id int, domainCondition *types.DomainCondition) error {
   result := db.Table("DomainCondition").First(domainCondition, id)
   return result.Error
}

func SaveDomainCondition(db *gorm.DB, domainConditions []*types.DomainCondition) error {
   tx := db.Begin()
   
   if tx.Error != nil {
      return errors.New("Could not initialize transaction to save " + reflect.TypeOf(domainConditions).Name() + " entity")
   }
   
   defer func() {
      if r := recover(); r != nil {
         tx.Rollback()
      }
   }()
   
   if err := tx.Error; err != nil {
      return err
   }
   
   if err := tx.Table("DomainCondition").Create(domainConditions).Error; err != nil {
      tx.Rollback()
      return err
   }
   
   return tx.Commit().Error
}

