//*** CAUTION ***
//This is an autogenerated file produced by regenerateBackend.py.
//Edits made here will not persist after backend regeneration.

package generatedServices
import (
   "errors"
   "reflect"
   contextProviders "AdventureEngineServer/contextProviders"
   types "AdventureEngineServer/generatedDatabaseTypes"
   utils "AdventureEngineServer/utils"
)

func GetDomainItems(context *contextProviders.ServiceContext, args *contextProviders.GetArgs[types.DomainItem]) (contextProviders.GetReturn[types.DomainItem], error) {
   if context == nil {
      return nil, errors.New("No service context provided")
   }
   
   if args == nil {
      return nil, errors.New("No service arguments provided")
   }
   
   var returnBuffer []types.DomainItem
   
   filteredContext, err := utils.FilterTableContext(context.DatabaseContext.Table("DomainItem"), args.Filters)
   
   if err != nil {
      return nil, err
   }
   result := filteredContext.Find(returnBuffer)
   
   if result.Error != nil {
      return nil, result.Error
   }
   
   return returnBuffer, nil
}

func GetDomainItemById(context *contextProviders.ServiceContext, args *contextProviders.GetByIdArgs[types.DomainItem]) (contextProviders.GetByIdReturn[types.DomainItem], error) {
   if context == nil {
      return nil, errors.New("No service context provided")
   }
   
   if args == nil {
      return nil, errors.New("No service arguments provided")
   }
   
   var returnPtr *types.DomainItem
   result := context.DatabaseContext.Table("DomainItem").First(returnPtr, args.Id)
   if result.Error != nil {
      return nil, result.Error
   }
   
   return returnPtr, nil
}

func SaveDomainItem(context *contextProviders.ServiceContext, args *contextProviders.SaveArgs[types.DomainItem]) (contextProviders.SaveReturn[types.DomainItem], error) {
   if context == nil {
      return nil, errors.New("No service context provided")
   }
   
   if args == nil {
      return nil, errors.New("No service arguments provided")
   }
   
   tx := context.DatabaseContext.Begin()
   
   if tx.Error != nil {
      return nil, errors.New("Could not initialize transaction to save " + reflect.TypeOf(args.Items).Name() + " entity")
   }
   
   defer func() {
      if r := recover(); r != nil {
         tx.Rollback()
      }
   }()
   
   if err := tx.Error; err != nil {
      return nil, err
   }
   
   if err := tx.Table("DomainItem").Save(args.Items).Error; err != nil {
      tx.Rollback()
      return nil, err
   }
   if tx.Commit().Error != nil {
      return nil, tx.Commit().Error
   }
   
   return args.Items, nil
}
