//*** CAUTION ***
//This is an autogenerated file produced by regenerateBackend.py.
//Edits made here will not persist after backend regeneration.

package generatedServices
import (
   "errors"
   "reflect"
   types "AdventureEngineServer/generatedDatabaseTypes"
   "gorm.io/gorm"
)

func GetDomainSpells(db *gorm.DB, domainSpells *[]types.DomainSpell) error {
   result := db.Table("DomainSpell").Find(domainSpells)
   return result.Error
}

func GetDomainSpellById(db *gorm.DB, id int, domainSpell *types.DomainSpell) error {
   result := db.Table("DomainSpell").First(domainSpell, id)
   return result.Error
}

func SaveDomainSpell(db *gorm.DB, domainSpell *types.DomainSpell) error {
   tx := db.Begin()
   
   if tx.Error != nil {
   return errors.New("Could not initialize transaction to save " + reflect.TypeOf(domainSpell).Name() + " entity")
   }
   
   defer func() {
      if r := recover(); r != nil {
         tx.Rollback()
      }
   }()
   
   if err := tx.Error; err != nil {
      return err
   }
   
   if err := tx.Table("DomainSpell").Save(domainSpell).Error; err != nil {
      tx.Rollback()
      return err
   }
   
   return tx.Commit().Error
}

func GetClassSpellsByDomainSpellId(db *gorm.DB, id int, ClassSpells *[]types.ClassSpell) error {
   result := db.Table("ClassSpell").Where(map[string]interface{}{"Spell__DomainSpell": id}).Find(&ClassSpells)
   return result.Error
}
