//*** CAUTION ***
//This is an autogenerated file produced by regenerateBackend.py.
//Edits made here will not persist after backend regeneration.

package generatedServices
import (
   "errors"
   "reflect"
   contextProviders "AdventureEngineServer/contextProviders"
   types "AdventureEngineServer/generatedDatabaseTypes"
   utils "AdventureEngineServer/utils"
)

func GetDomainToolCategorys(context *contextProviders.ServiceContext, args *contextProviders.GetArgs[types.DomainToolCategory]) (contextProviders.GetReturn[types.DomainToolCategory], error) {
   if context == nil {
      return nil, errors.New("No service context provided")
   }
   
   if args == nil {
      return nil, errors.New("No service arguments provided")
   }
   
   if context.DatabaseContext == nil {
      return nil, errors.New("Cannot perform get action on nil database context")
   }
   
   var returnBuffer []types.DomainToolCategory
   
   filteredContext, err := utils.FilterTableContext(context.DatabaseContext.Table("DomainToolCategory"), args.Filters)
   
   if err != nil {
      return nil, err
   }
   result := filteredContext.Find(&returnBuffer)
   
   if result.Error != nil {
      return nil, result.Error
   }
   
   return returnBuffer, nil
}

func GetDomainToolCategoryById(context *contextProviders.ServiceContext, args *contextProviders.GetByIdArgs[types.DomainToolCategory]) (contextProviders.GetByIdReturn[types.DomainToolCategory], error) {
   if context == nil {
      return nil, errors.New("No service context provided")
   }
   
   if args == nil {
      return nil, errors.New("No service arguments provided")
   }
   
   if context.DatabaseContext == nil {
      return nil, errors.New("Cannot perform get by id action on nil database context")
   }
   
   var returnBuffer types.DomainToolCategory
   result := context.DatabaseContext.Table("DomainToolCategory").First(&returnBuffer, args.Id)
   if result.Error != nil {
      return nil, result.Error
   }
   
   return &returnBuffer, nil
}

func SaveDomainToolCategory(context *contextProviders.ServiceContext, args *contextProviders.SaveArgs[types.DomainToolCategory]) (contextProviders.SaveReturn[types.DomainToolCategory], error) {
   if context == nil {
      return nil, errors.New("No service context provided")
   }
   
   if args == nil {
      return nil, errors.New("No service arguments provided")
   }
   
   if context.DatabaseContext == nil {
      return nil, errors.New("Cannot perform save action on nil database context")
   }
   
   tx := context.DatabaseContext.Begin()
   
   if tx.Error != nil {
      return nil, errors.New("Could not initialize transaction to save " + reflect.TypeOf(args.Items).Name() + " entity")
   }
   
   defer func() {
      if r := recover(); r != nil {
         tx.Rollback()
      }
   }()
   
   if err := tx.Error; err != nil {
      return nil, err
   }
   
   if err := tx.Table("DomainToolCategory").Save(args.Items).Error; err != nil {
      tx.Rollback()
      return nil, err
   }
   if tx.Commit().Error != nil {
      return nil, tx.Commit().Error
   }
   
   return args.Items, nil
}
