// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package generatedDatabaseTypes

type Character struct {
	// AbbreviatedTitle corresponds to the JSON schema field "AbbreviatedTitle".
	AbbreviatedTitle *string `json:"AbbreviatedTitle" gorm:"column:AbbreviatedTitle" mapstructure:"AbbreviatedTitle"`

	// CampaignCampaign corresponds to the JSON schema field "Campaign__Campaign".
	Campaign__Campaign *int `json:"Campaign__Campaign" gorm:"column:Campaign__Campaign" mapstructure:"Campaign__Campaign"`

	// CreatedAt corresponds to the JSON schema field "CreatedAt".
	CreatedAt *string `json:"CreatedAt" gorm:"column:CreatedAt" mapstructure:"CreatedAt"`

	// CurrentSizeDomainSize corresponds to the JSON schema field
	// "CurrentSize__DomainSize".
	CurrentSize__DomainSize *int `json:"CurrentSize__DomainSize" gorm:"column:CurrentSize__DomainSize" mapstructure:"CurrentSize__DomainSize"`

	// Description corresponds to the JSON schema field "Description".
	Description *string `json:"Description" gorm:"column:Description" mapstructure:"Description"`

	// Id corresponds to the JSON schema field "Id".
	Id *int `json:"Id" gorm:"primaryKey;column:Id" mapstructure:"Id"`

	// IsActive corresponds to the JSON schema field "IsActive".
	IsActive *bool `json:"IsActive" gorm:"column:IsActive" mapstructure:"IsActive"`

	// ResourceOwnerUser corresponds to the JSON schema field "ResourceOwner__User".
	ResourceOwner__User *int `json:"ResourceOwner__User" gorm:"column:ResourceOwner__User" mapstructure:"ResourceOwner__User"`

	// SpeciesDomainSpecies corresponds to the JSON schema field
	// "Species__DomainSpecies".
	Species__DomainSpecies *int `json:"Species__DomainSpecies" gorm:"column:Species__DomainSpecies" mapstructure:"Species__DomainSpecies"`

	// StatsCharacterDomainCharacterStatInstance corresponds to the JSON schema field
	// "Stats__CharacterDomainCharacterStatInstance".

	// SubClassesCharacterDomainSubClassInstance corresponds to the JSON schema field
	// "SubClasses__CharacterDomainSubClassInstance".

	// Title corresponds to the JSON schema field "Title".
	Title *string `json:"Title" gorm:"column:Title" mapstructure:"Title"`

	// UpdatedAt corresponds to the JSON schema field "UpdatedAt".
	UpdatedAt *string `json:"UpdatedAt" gorm:"column:UpdatedAt" mapstructure:"UpdatedAt"`
}
