// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package generatedDatabaseTypes

type DomainAction struct {
	// Description corresponds to the JSON schema field "Description".
	Description *string `json:"Description,omitempty" yaml:"Description,omitempty" mapstructure:"Description,omitempty"`

	// IsActive corresponds to the JSON schema field "IsActive".
	IsActive *bool `json:"IsActive,omitempty" yaml:"IsActive,omitempty" mapstructure:"IsActive,omitempty"`

	// Title corresponds to the JSON schema field "Title".
	Title *string `json:"Title,omitempty" yaml:"Title,omitempty" mapstructure:"Title,omitempty"`

	// UsesAction corresponds to the JSON schema field "UsesAction".
	UsesAction *bool `json:"UsesAction,omitempty" yaml:"UsesAction,omitempty" mapstructure:"UsesAction,omitempty"`

	// UsesBonusAction corresponds to the JSON schema field "UsesBonusAction".
	UsesBonusAction *bool `json:"UsesBonusAction,omitempty" yaml:"UsesBonusAction,omitempty" mapstructure:"UsesBonusAction,omitempty"`

	// Id corresponds to the JSON schema field "id".
	Id *float64 `json:"id,omitempty" yaml:"id,omitempty" mapstructure:"id,omitempty"`
}
