// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package generatedDatabaseTypes

type DomainAction struct {
	// Description corresponds to the JSON schema field "Description".
	Description *string `json:"Description" gorm:"column:Description" mapstructure:"Description"`

	// Id corresponds to the JSON schema field "Id".
	Id *int `json:"Id" gorm:"primaryKey;column:Id" mapstructure:"Id"`

	// IsActive corresponds to the JSON schema field "IsActive".
	IsActive *bool `json:"IsActive" gorm:"column:IsActive" mapstructure:"IsActive"`

	// Title corresponds to the JSON schema field "Title".
	Title *string `json:"Title" gorm:"column:Title" mapstructure:"Title"`

	// UsesAction corresponds to the JSON schema field "UsesAction".
	UsesAction *bool `json:"UsesAction" gorm:"column:UsesAction" mapstructure:"UsesAction"`

	// UsesBonusAction corresponds to the JSON schema field "UsesBonusAction".
	UsesBonusAction *bool `json:"UsesBonusAction" gorm:"column:UsesBonusAction" mapstructure:"UsesBonusAction"`
}
