// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package generatedDatabaseTypes

type DomainClass struct {
	// Description corresponds to the JSON schema field "Description".
	Description *string `json:"Description,omitempty" yaml:"Description,omitempty" mapstructure:"Description,omitempty"`

	// HitDieDomainDice corresponds to the JSON schema field "HitDie__domainDice".
	HitDieDomainDice *float64 `json:"HitDie__domainDice,omitempty" yaml:"HitDie__domainDice,omitempty" mapstructure:"HitDie__domainDice,omitempty"`

	// Id corresponds to the JSON schema field "Id".
	Id *float64 `json:"Id,omitempty" yaml:"Id,omitempty" mapstructure:"Id,omitempty"`

	// IsActive corresponds to the JSON schema field "IsActive".
	IsActive *bool `json:"IsActive,omitempty" yaml:"IsActive,omitempty" mapstructure:"IsActive,omitempty"`

	// SpellcastingStatDomainCharacterStat corresponds to the JSON schema field
	// "SpellcastingStat__domainCharacterStat".
	SpellcastingStatDomainCharacterStat *float64 `json:"SpellcastingStat__domainCharacterStat,omitempty" yaml:"SpellcastingStat__domainCharacterStat,omitempty" mapstructure:"SpellcastingStat__domainCharacterStat,omitempty"`

	// Title corresponds to the JSON schema field "Title".
	Title *string `json:"Title,omitempty" yaml:"Title,omitempty" mapstructure:"Title,omitempty"`
}
