// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package generatedDatabaseTypes

type DomainDice struct {
	// Description corresponds to the JSON schema field "Description".
	Description *string `json:"Description" gorm:"column:Description" mapstructure:"Description"`

	// Id corresponds to the JSON schema field "Id".
	Id *float64 `json:"Id" gorm:"primaryKey;column:Id" mapstructure:"Id"`

	// IsActive corresponds to the JSON schema field "IsActive".
	IsActive *bool `json:"IsActive" gorm:"column:IsActive" mapstructure:"IsActive"`

	// Maximum corresponds to the JSON schema field "Maximum".
	Maximum float64 `json:"Maximum" gorm:"column:Maximum" mapstructure:"Maximum"`

	// Minimum corresponds to the JSON schema field "Minimum".
	Minimum float64 `json:"Minimum" gorm:"column:Minimum" mapstructure:"Minimum"`

	// Title corresponds to the JSON schema field "Title".
	Title *string `json:"Title" gorm:"column:Title" mapstructure:"Title"`
}
