// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package generatedDatabaseTypes

type QuantifierCostSpecifier struct {
	// AbbreviatedTitle corresponds to the JSON schema field "AbbreviatedTitle".
	AbbreviatedTitle *string `json:"AbbreviatedTitle" gorm:"column:AbbreviatedTitle" mapstructure:"AbbreviatedTitle"`

	// CostDomainCharacterStat corresponds to the JSON schema field
	// "Cost__DomainCharacterStat".
	Cost__DomainCharacterStat *int `json:"Cost__DomainCharacterStat" gorm:"column:Cost__DomainCharacterStat" mapstructure:"Cost__DomainCharacterStat"`

	// CreatedAt corresponds to the JSON schema field "CreatedAt".
	CreatedAt *string `json:"CreatedAt" gorm:"column:CreatedAt" mapstructure:"CreatedAt"`

	// DeltaPercentage corresponds to the JSON schema field "DeltaPercentage".
	DeltaPercentage *float64 `json:"DeltaPercentage" gorm:"column:DeltaPercentage" mapstructure:"DeltaPercentage"`

	// DeltaQuantity corresponds to the JSON schema field "DeltaQuantity".
	DeltaQuantity *float64 `json:"DeltaQuantity" gorm:"column:DeltaQuantity" mapstructure:"DeltaQuantity"`

	// Description corresponds to the JSON schema field "Description".
	Description *string `json:"Description" gorm:"column:Description" mapstructure:"Description"`

	// Id corresponds to the JSON schema field "Id".
	Id *int `json:"Id" gorm:"primaryKey;column:Id" mapstructure:"Id"`

	// IsActive corresponds to the JSON schema field "IsActive".
	IsActive *bool `json:"IsActive" gorm:"column:IsActive" mapstructure:"IsActive"`

	// QuantifierQuantifier corresponds to the JSON schema field
	// "Quantifier__Quantifier".
	Quantifier__Quantifier *int `json:"Quantifier__Quantifier" gorm:"column:Quantifier__Quantifier" mapstructure:"Quantifier__Quantifier"`

	// ResourceOwnerUser corresponds to the JSON schema field "ResourceOwner__User".
	ResourceOwner__User *int `json:"ResourceOwner__User" gorm:"column:ResourceOwner__User" mapstructure:"ResourceOwner__User"`

	// Title corresponds to the JSON schema field "Title".
	Title *string `json:"Title" gorm:"column:Title" mapstructure:"Title"`

	// UpdatedAt corresponds to the JSON schema field "UpdatedAt".
	UpdatedAt *string `json:"UpdatedAt" gorm:"column:UpdatedAt" mapstructure:"UpdatedAt"`
}
