// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package generatedDatabaseTypes

type Quantifier struct {
	// AddedSpellDomainSpell corresponds to the JSON schema field
	// "AddedSpell__domainSpell".
	AddedSpellDomainSpell *float64 `json:"AddedSpell__domainSpell,omitempty" yaml:"AddedSpell__domainSpell,omitempty" mapstructure:"AddedSpell__domainSpell,omitempty"`

	// ConditionDomainCondition corresponds to the JSON schema field
	// "Condition__domainCondition".
	ConditionDomainCondition *float64 `json:"Condition__domainCondition,omitempty" yaml:"Condition__domainCondition,omitempty" mapstructure:"Condition__domainCondition,omitempty"`

	// DamageTypeDomainDamageType corresponds to the JSON schema field
	// "DamageType__domainDamageType".
	DamageTypeDomainDamageType *float64 `json:"DamageType__domainDamageType,omitempty" yaml:"DamageType__domainDamageType,omitempty" mapstructure:"DamageType__domainDamageType,omitempty"`

	// Delta corresponds to the JSON schema field "Delta".
	Delta *float64 `json:"Delta,omitempty" yaml:"Delta,omitempty" mapstructure:"Delta,omitempty"`

	// Description corresponds to the JSON schema field "Description".
	Description *string `json:"Description,omitempty" yaml:"Description,omitempty" mapstructure:"Description,omitempty"`

	// EffectDomainStaticEffect corresponds to the JSON schema field
	// "Effect__domainStaticEffect".
	EffectDomainStaticEffect *float64 `json:"Effect__domainStaticEffect,omitempty" yaml:"Effect__domainStaticEffect,omitempty" mapstructure:"Effect__domainStaticEffect,omitempty"`

	// Id corresponds to the JSON schema field "Id".
	Id *float64 `json:"Id,omitempty" yaml:"Id,omitempty" mapstructure:"Id,omitempty"`

	// ImpactsSelf corresponds to the JSON schema field "ImpactsSelf".
	ImpactsSelf *bool `json:"ImpactsSelf,omitempty" yaml:"ImpactsSelf,omitempty" mapstructure:"ImpactsSelf,omitempty"`

	// IntoInventory corresponds to the JSON schema field "IntoInventory".
	IntoInventory *bool `json:"IntoInventory,omitempty" yaml:"IntoInventory,omitempty" mapstructure:"IntoInventory,omitempty"`

	// IsAction corresponds to the JSON schema field "IsAction".
	IsAction *bool `json:"IsAction,omitempty" yaml:"IsAction,omitempty" mapstructure:"IsAction,omitempty"`

	// IsActive corresponds to the JSON schema field "IsActive".
	IsActive *bool `json:"IsActive,omitempty" yaml:"IsActive,omitempty" mapstructure:"IsActive,omitempty"`

	// IsBonusAction corresponds to the JSON schema field "IsBonusAction".
	IsBonusAction *bool `json:"IsBonusAction,omitempty" yaml:"IsBonusAction,omitempty" mapstructure:"IsBonusAction,omitempty"`

	// Level1SpellSlots corresponds to the JSON schema field "Level1SpellSlots".
	Level1SpellSlots *float64 `json:"Level1SpellSlots,omitempty" yaml:"Level1SpellSlots,omitempty" mapstructure:"Level1SpellSlots,omitempty"`

	// Level2SpellSlots corresponds to the JSON schema field "Level2SpellSlots".
	Level2SpellSlots *float64 `json:"Level2SpellSlots,omitempty" yaml:"Level2SpellSlots,omitempty" mapstructure:"Level2SpellSlots,omitempty"`

	// Level3SpellSlots corresponds to the JSON schema field "Level3SpellSlots".
	Level3SpellSlots *float64 `json:"Level3SpellSlots,omitempty" yaml:"Level3SpellSlots,omitempty" mapstructure:"Level3SpellSlots,omitempty"`

	// Level4SpellSlots corresponds to the JSON schema field "Level4SpellSlots".
	Level4SpellSlots *float64 `json:"Level4SpellSlots,omitempty" yaml:"Level4SpellSlots,omitempty" mapstructure:"Level4SpellSlots,omitempty"`

	// Level5SpellSlots corresponds to the JSON schema field "Level5SpellSlots".
	Level5SpellSlots *float64 `json:"Level5SpellSlots,omitempty" yaml:"Level5SpellSlots,omitempty" mapstructure:"Level5SpellSlots,omitempty"`

	// Level6SpellSlots corresponds to the JSON schema field "Level6SpellSlots".
	Level6SpellSlots *float64 `json:"Level6SpellSlots,omitempty" yaml:"Level6SpellSlots,omitempty" mapstructure:"Level6SpellSlots,omitempty"`

	// Level7SpellSlots corresponds to the JSON schema field "Level7SpellSlots".
	Level7SpellSlots *float64 `json:"Level7SpellSlots,omitempty" yaml:"Level7SpellSlots,omitempty" mapstructure:"Level7SpellSlots,omitempty"`

	// Level8SpellSlots corresponds to the JSON schema field "Level8SpellSlots".
	Level8SpellSlots *float64 `json:"Level8SpellSlots,omitempty" yaml:"Level8SpellSlots,omitempty" mapstructure:"Level8SpellSlots,omitempty"`

	// Level9SpellSlots corresponds to the JSON schema field "Level9SpellSlots".
	Level9SpellSlots *float64 `json:"Level9SpellSlots,omitempty" yaml:"Level9SpellSlots,omitempty" mapstructure:"Level9SpellSlots,omitempty"`

	// LevelMaximumRequirement corresponds to the JSON schema field
	// "LevelMaximumRequirement".
	LevelMaximumRequirement *float64 `json:"LevelMaximumRequirement,omitempty" yaml:"LevelMaximumRequirement,omitempty" mapstructure:"LevelMaximumRequirement,omitempty"`

	// LevelMinimumRequirement corresponds to the JSON schema field
	// "LevelMinimumRequirement".
	LevelMinimumRequirement *float64 `json:"LevelMinimumRequirement,omitempty" yaml:"LevelMinimumRequirement,omitempty" mapstructure:"LevelMinimumRequirement,omitempty"`

	// Quantity corresponds to the JSON schema field "Quantity".
	Quantity *float64 `json:"Quantity,omitempty" yaml:"Quantity,omitempty" mapstructure:"Quantity,omitempty"`

	// RefreshOnLongRest corresponds to the JSON schema field "RefreshOnLongRest".
	RefreshOnLongRest *bool `json:"RefreshOnLongRest,omitempty" yaml:"RefreshOnLongRest,omitempty" mapstructure:"RefreshOnLongRest,omitempty"`

	// RefreshOnShortRest corresponds to the JSON schema field "RefreshOnShortRest".
	RefreshOnShortRest *bool `json:"RefreshOnShortRest,omitempty" yaml:"RefreshOnShortRest,omitempty" mapstructure:"RefreshOnShortRest,omitempty"`

	// ResistanceTypeDomainDamageType corresponds to the JSON schema field
	// "ResistanceType__domainDamageType".
	ResistanceTypeDomainDamageType *float64 `json:"ResistanceType__domainDamageType,omitempty" yaml:"ResistanceType__domainDamageType,omitempty" mapstructure:"ResistanceType__domainDamageType,omitempty"`

	// SaveDomainCharacterStat corresponds to the JSON schema field
	// "Save__domainCharacterStat".
	SaveDomainCharacterStat *float64 `json:"Save__domainCharacterStat,omitempty" yaml:"Save__domainCharacterStat,omitempty" mapstructure:"Save__domainCharacterStat,omitempty"`

	// TargetDomainCharacterStat corresponds to the JSON schema field
	// "Target__domainCharacterStat".
	TargetDomainCharacterStat *float64 `json:"Target__domainCharacterStat,omitempty" yaml:"Target__domainCharacterStat,omitempty" mapstructure:"Target__domainCharacterStat,omitempty"`

	// Title corresponds to the JSON schema field "Title".
	Title *string `json:"Title,omitempty" yaml:"Title,omitempty" mapstructure:"Title,omitempty"`

	// UntilLongRest corresponds to the JSON schema field "UntilLongRest".
	UntilLongRest *bool `json:"UntilLongRest,omitempty" yaml:"UntilLongRest,omitempty" mapstructure:"UntilLongRest,omitempty"`

	// UntilShortRest corresponds to the JSON schema field "UntilShortRest".
	UntilShortRest *bool `json:"UntilShortRest,omitempty" yaml:"UntilShortRest,omitempty" mapstructure:"UntilShortRest,omitempty"`
}
