// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package generatedDatabaseTypes

type UserRoleInstance struct {
	// AbbreviatedTitle corresponds to the JSON schema field "AbbreviatedTitle".
	AbbreviatedTitle *string `json:"AbbreviatedTitle" gorm:"column:AbbreviatedTitle" mapstructure:"AbbreviatedTitle"`

	// CreatedAt corresponds to the JSON schema field "CreatedAt".
	CreatedAt *string `json:"CreatedAt" gorm:"column:CreatedAt" mapstructure:"CreatedAt"`

	// Description corresponds to the JSON schema field "Description".
	Description *string `json:"Description" gorm:"column:Description" mapstructure:"Description"`

	// Id corresponds to the JSON schema field "Id".
	Id *int `json:"Id" gorm:"primaryKey;column:Id" mapstructure:"Id"`

	// IsActive corresponds to the JSON schema field "IsActive".
	IsActive *bool `json:"IsActive" gorm:"column:IsActive" mapstructure:"IsActive"`

	// ResourceOwnerUser corresponds to the JSON schema field "ResourceOwner__User".
	ResourceOwner__User *int `json:"ResourceOwner__User" gorm:"column:ResourceOwner__User" mapstructure:"ResourceOwner__User"`

	// RoleDomainAppRole corresponds to the JSON schema field "Role__DomainAppRole".
	Role__DomainAppRole *int `json:"Role__DomainAppRole" gorm:"column:Role__DomainAppRole" mapstructure:"Role__DomainAppRole"`

	// Title corresponds to the JSON schema field "Title".
	Title *string `json:"Title" gorm:"column:Title" mapstructure:"Title"`

	// UpdatedAt corresponds to the JSON schema field "UpdatedAt".
	UpdatedAt *string `json:"UpdatedAt" gorm:"column:UpdatedAt" mapstructure:"UpdatedAt"`

	// UserUser corresponds to the JSON schema field "User__User".
	User__User *int `json:"User__User" gorm:"column:User__User" mapstructure:"User__User"`
}
