// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package generatedtypes

type CharacterJson struct {
	// CampaignCampaign corresponds to the JSON schema field "campaign__Campaign".
	CampaignCampaign *float64 `json:"campaign__Campaign,omitempty" yaml:"campaign__Campaign,omitempty" mapstructure:"campaign__Campaign,omitempty"`

	// CurrentSizeDomainSize corresponds to the JSON schema field
	// "currentSize__domainSize".
	CurrentSizeDomainSize *float64 `json:"currentSize__domainSize,omitempty" yaml:"currentSize__domainSize,omitempty" mapstructure:"currentSize__domainSize,omitempty"`

	// Description corresponds to the JSON schema field "description".
	Description *string `json:"description,omitempty" yaml:"description,omitempty" mapstructure:"description,omitempty"`

	// Id corresponds to the JSON schema field "id".
	Id *float64 `json:"id,omitempty" yaml:"id,omitempty" mapstructure:"id,omitempty"`

	// IsActive corresponds to the JSON schema field "isActive".
	IsActive *bool `json:"isActive,omitempty" yaml:"isActive,omitempty" mapstructure:"isActive,omitempty"`

	// SpeciesDomainSpecies corresponds to the JSON schema field
	// "species__domainSpecies".
	SpeciesDomainSpecies *float64 `json:"species__domainSpecies,omitempty" yaml:"species__domainSpecies,omitempty" mapstructure:"species__domainSpecies,omitempty"`

	// SubclassDomainSubClass corresponds to the JSON schema field
	// "subclass__domainSubClass".
	SubclassDomainSubClass *float64 `json:"subclass__domainSubClass,omitempty" yaml:"subclass__domainSubClass,omitempty" mapstructure:"subclass__domainSubClass,omitempty"`

	// Title corresponds to the JSON schema field "title".
	Title *string `json:"title,omitempty" yaml:"title,omitempty" mapstructure:"title,omitempty"`
}
