//*** CAUTION ***
//This is an autogenerated file produced by regenerateFrontendQueries.py.
//Edits made here will not persist after regeneration.

import { AppTypes } from "../types/appTypes/appTypes";

export type ServiceInterface<T> = {
   getAllItems: () => Promise<Array<T>>
   getItemById: (id: number) => Promise<T>
   saveItem: (item: T) => Promise<T>
}

export type QueryServicesType = {[key in keyof typeof AppTypes]: ServiceInterface<typeof AppTypes[key]>}

export function composeQueryContext<
   //Type templating
   QueryHandlerType extends <T>(opts: {
      key: string[]
      query: (...args : any[]) => Promise<T>
   //Covering a generic query return
   }) => Record<string, T | any>
>(
   //Arguments/dependencies
   queryHandler: QueryHandlerType,
   services: QueryServicesType
) {
   return {
      queryCampaigns: () => queryHandler({
         key: ["Campaigns"],
         query: () => services.Campaign.getAllItems()
      }),
      queryCharacters: () => queryHandler({
         key: ["Characters"],
         query: () => services.Character.getAllItems()
      }),
      queryCharacterDomainCharacterStatInstances: () => queryHandler({
         key: ["CharacterDomainCharacterStatInstances"],
         query: () => services.CharacterDomainCharacterStatInstance.getAllItems()
      }),
      queryDomainActions: () => queryHandler({
         key: ["DomainActions"],
         query: () => services.DomainAction.getAllItems()
      }),
      queryDomainCharacterStats: () => queryHandler({
         key: ["DomainCharacterStats"],
         query: () => services.DomainCharacterStat.getAllItems()
      }),
      queryDomainClasss: () => queryHandler({
         key: ["DomainClasss"],
         query: () => services.DomainClass.getAllItems()
      }),
      queryDomainConditions: () => queryHandler({
         key: ["DomainConditions"],
         query: () => services.DomainCondition.getAllItems()
      }),
      queryDomainCreatureTypes: () => queryHandler({
         key: ["DomainCreatureTypes"],
         query: () => services.DomainCreatureType.getAllItems()
      }),
      queryDomainDamageTypes: () => queryHandler({
         key: ["DomainDamageTypes"],
         query: () => services.DomainDamageType.getAllItems()
      }),
      queryDomainDices: () => queryHandler({
         key: ["DomainDices"],
         query: () => services.DomainDice.getAllItems()
      }),
      queryDomainDiceRollTypes: () => queryHandler({
         key: ["DomainDiceRollTypes"],
         query: () => services.DomainDiceRollType.getAllItems()
      }),
      queryDomainItems: () => queryHandler({
         key: ["DomainItems"],
         query: () => services.DomainItem.getAllItems()
      }),
      queryDomainSizes: () => queryHandler({
         key: ["DomainSizes"],
         query: () => services.DomainSize.getAllItems()
      }),
      queryDomainSpeciess: () => queryHandler({
         key: ["DomainSpeciess"],
         query: () => services.DomainSpecies.getAllItems()
      }),
      queryDomainSpells: () => queryHandler({
         key: ["DomainSpells"],
         query: () => services.DomainSpell.getAllItems()
      }),
      queryDomainSpellSchools: () => queryHandler({
         key: ["DomainSpellSchools"],
         query: () => services.DomainSpellSchool.getAllItems()
      }),
      queryDomainStaticEffects: () => queryHandler({
         key: ["DomainStaticEffects"],
         query: () => services.DomainStaticEffect.getAllItems()
      }),
      queryDomainSubClasss: () => queryHandler({
         key: ["DomainSubClasss"],
         query: () => services.DomainSubClass.getAllItems()
      }),
      queryQuantifiers: () => queryHandler({
         key: ["Quantifiers"],
         query: () => services.Quantifier.getAllItems()
      }),
   }
}
