//*** CAUTION ***
//This is an autogenerated file produced by regenerateBackend.py.
//Edits made here will not persist after backend regeneration.

package generatedDTOs

import (
   contextProviders "AdventureEngineServer/contextProviders"
   types "AdventureEngineServer/generatedDatabaseTypes"
   
   services "AdventureEngineServer/generatedServices"
   "errors"
   "fmt"
   "reflect"
   "slices"
)

type CampaignDTOAttributes struct {
   AbbreviatedTitle *string
   CreatedAt *string
   Description *string
   
   IsActive *bool
   Notes string
   Title *string
   UpdatedAt *string
}

type CampaignDTOManyToOneRelationships struct {
   ResourceOwner__User *UserDTO
}

type CampaignDTOOneToManyRelationships struct {
}

type CampaignDTORelationships struct {
   ManyToOne CampaignDTOManyToOneRelationships
   OneToMany CampaignDTOOneToManyRelationships
}

type CampaignDTO struct {
   Id *int
   
   Attributes CampaignDTOAttributes
   
   Relationships CampaignDTORelationships
}

func CampaignToCampaignDTO(context *contextProviders.DTOContext, campaign *types.Campaign) (*CampaignDTO, error) {
   if context == nil {
      return nil, errors.New("No DTO context provided")
   }
   
   if (campaign == nil) {
      return nil, errors.New("Cannot convert nil pointer passed to DTO conversion for table Campaign")
   }
   
   if (slices.Contains(context.TraversedTables, reflect.TypeOf(*campaign).Name())) {
      fmt.Println("Hit circular catch case for table Campaign")
      return nil, nil
   }
   
   childDTOContext := contextProviders.DTOContext{
      DatabaseContext: context.DatabaseContext,
      TraversedTables: append(context.TraversedTables, reflect.TypeOf(*campaign).Name()),
   }
   serviceContext := &contextProviders.ServiceContext{
      DatabaseContext: context.DatabaseContext,
      CurrentUser: nil,
   }
   
   var includedResourceOwner__User *types.User
   
   var ResourceOwner__UserDTO *UserDTO
   
   var err error
   
   if (campaign.ResourceOwner__User != nil) {
      includedResourceOwner__User, err = services.GetUserById(serviceContext, contextProviders.ProduceGetByIdArgs[types.User](campaign.ResourceOwner__User))
      if err != nil {
         return nil, err
      }
      ResourceOwner__UserDTO, err = UserToUserDTO(&childDTOContext, includedResourceOwner__User)
      if err != nil {
         return nil, err
      }
   }

   
   return &CampaignDTO{
      Id: campaign.Id,
      Attributes: CampaignDTOAttributes{
         AbbreviatedTitle: campaign.AbbreviatedTitle,
         CreatedAt: campaign.CreatedAt,
         Description: campaign.Description,
         
         IsActive: campaign.IsActive,
         Notes: campaign.Notes,
         Title: campaign.Title,
         UpdatedAt: campaign.UpdatedAt,
      },
      Relationships: CampaignDTORelationships{
         ManyToOne: CampaignDTOManyToOneRelationships {
            ResourceOwner__User: ResourceOwner__UserDTO,
         },
         OneToMany: CampaignDTOOneToManyRelationships {
         },
      },
   }, nil
}

func CampaignDTOToCampaign(campaign *CampaignDTO) *types.Campaign {
   var tableTypeBuffer types.Campaign
   
   tableTypeBuffer.Id = campaign.Id
   tableTypeBuffer.AbbreviatedTitle = campaign.Attributes.AbbreviatedTitle
   tableTypeBuffer.CreatedAt = campaign.Attributes.CreatedAt
   tableTypeBuffer.Description = campaign.Attributes.Description
   
   tableTypeBuffer.IsActive = campaign.Attributes.IsActive
   tableTypeBuffer.Notes = campaign.Attributes.Notes
   tableTypeBuffer.Title = campaign.Attributes.Title
   tableTypeBuffer.UpdatedAt = campaign.Attributes.UpdatedAt
   
   if (campaign.Relationships.ManyToOne.ResourceOwner__User != nil) {
      tableTypeBuffer.ResourceOwner__User = campaign.Relationships.ManyToOne.ResourceOwner__User.Id
   }

   return &tableTypeBuffer
}
