//*** CAUTION ***
//This is an autogenerated file produced by regenerateBackend.py.
//Edits made here will not persist after backend regeneration.

package generatedDTOs

import (
   contextProviders "AdventureEngineServer/contextProviders"
   types "AdventureEngineServer/generatedDatabaseTypes"
   utils "AdventureEngineServer/utils"
   services "AdventureEngineServer/generatedServices"
   "errors"
   "fmt"
   "reflect"
   "slices"
)

type CharacterDTOAttributes struct {
   AbbreviatedTitle *string
   CreatedAt *string
   Description *string
   
   IsActive *bool
   Title *string
   UpdatedAt *string
}

type CharacterDTOManyToOneRelationships struct {
   Campaign__Campaign *CampaignDTO
   CurrentSize__DomainSize *DomainSizeDTO
   ResourceOwner__User *UserDTO
   Species__DomainSpecies *DomainSpeciesDTO
}

type CharacterDTOOneToManyRelationships struct {
   Stats__CharacterDomainCharacterStatInstance []*CharacterDomainCharacterStatInstanceDTO
   SubClasses__CharacterDomainSubClassInstance []*CharacterDomainSubClassInstanceDTO
}

type CharacterDTORelationships struct {
   ManyToOne CharacterDTOManyToOneRelationships
   OneToMany CharacterDTOOneToManyRelationships
}

type CharacterDTO struct {
   Id *int
   
   Attributes CharacterDTOAttributes
   
   Relationships CharacterDTORelationships
}

func CharacterToCharacterDTO(context *contextProviders.DTOContext, character *types.Character) (*CharacterDTO, error) {
   if context == nil {
      return nil, errors.New("No DTO context provided")
   }
   
   if (character == nil) {
      return nil, errors.New("Cannot convert nil pointer passed to DTO conversion for table Character")
   }
   
   if (slices.Contains(context.TraversedTables, reflect.TypeOf(*character).Name())) {
      fmt.Println("Hit circular catch case for table Character")
      return nil, nil
   }
   
   childDTOContext := contextProviders.DTOContext{
      DatabaseContext: context.DatabaseContext,
      TraversedTables: append(context.TraversedTables, reflect.TypeOf(*character).Name()),
   }
   serviceContext := &contextProviders.ServiceContext{
      DatabaseContext: context.DatabaseContext,
      CurrentUser: nil,
   }
   
   var includedCampaign__Campaign *types.Campaign
   var includedCurrentSize__DomainSize *types.DomainSize
   var includedResourceOwner__User *types.User
   var includedSpecies__DomainSpecies *types.DomainSpecies
   var includedStats__CharacterDomainCharacterStatInstances []types.CharacterDomainCharacterStatInstance
   var includedSubClasses__CharacterDomainSubClassInstances []types.CharacterDomainSubClassInstance
   
   var Campaign__CampaignDTO *CampaignDTO
   var CurrentSize__DomainSizeDTO *DomainSizeDTO
   var ResourceOwner__UserDTO *UserDTO
   var Species__DomainSpeciesDTO *DomainSpeciesDTO
   var Stats__CharacterDomainCharacterStatInstanceDTOs []*CharacterDomainCharacterStatInstanceDTO
   var SubClasses__CharacterDomainSubClassInstanceDTOs []*CharacterDomainSubClassInstanceDTO
   
   var err error
   
   if (character.Campaign__Campaign != nil) {
      includedCampaign__Campaign, err = services.GetCampaignById(serviceContext, contextProviders.ProduceGetByIdArgs[types.Campaign](character.Campaign__Campaign))
      if err != nil {
         return nil, err
      }
      Campaign__CampaignDTO, err = CampaignToCampaignDTO(&childDTOContext, includedCampaign__Campaign)
      if err != nil {
         return nil, err
      }
   }

   if (character.CurrentSize__DomainSize != nil) {
      includedCurrentSize__DomainSize, err = services.GetDomainSizeById(serviceContext, contextProviders.ProduceGetByIdArgs[types.DomainSize](character.CurrentSize__DomainSize))
      if err != nil {
         return nil, err
      }
      CurrentSize__DomainSizeDTO, err = DomainSizeToDomainSizeDTO(&childDTOContext, includedCurrentSize__DomainSize)
      if err != nil {
         return nil, err
      }
   }

   if (character.ResourceOwner__User != nil) {
      includedResourceOwner__User, err = services.GetUserById(serviceContext, contextProviders.ProduceGetByIdArgs[types.User](character.ResourceOwner__User))
      if err != nil {
         return nil, err
      }
      ResourceOwner__UserDTO, err = UserToUserDTO(&childDTOContext, includedResourceOwner__User)
      if err != nil {
         return nil, err
      }
   }

   if (character.Species__DomainSpecies != nil) {
      includedSpecies__DomainSpecies, err = services.GetDomainSpeciesById(serviceContext, contextProviders.ProduceGetByIdArgs[types.DomainSpecies](character.Species__DomainSpecies))
      if err != nil {
         return nil, err
      }
      Species__DomainSpeciesDTO, err = DomainSpeciesToDomainSpeciesDTO(&childDTOContext, includedSpecies__DomainSpecies)
      if err != nil {
         return nil, err
      }
   }

   if (slices.Contains(context.TraversedTables, reflect.TypeOf(includedStats__CharacterDomainCharacterStatInstances).Elem().Name())) {
      includedStats__CharacterDomainCharacterStatInstances = []types.CharacterDomainCharacterStatInstance{}
      fmt.Println("Hit circular catch case for table CharacterDomainCharacterStatInstance")
   } else {
      includedStats__CharacterDomainCharacterStatInstances, err = services.GetCharacterDomainCharacterStatInstances(serviceContext, contextProviders.ProduceGetArgs[types.CharacterDomainCharacterStatInstance]("Character__Character", character.Id))
      if err != nil {
         return nil, err
      }
      Stats__CharacterDomainCharacterStatInstanceDTOs, err = utils.ErrorCompatibleMap(includedStats__CharacterDomainCharacterStatInstances, func(relationshipElement types.CharacterDomainCharacterStatInstance) (*CharacterDomainCharacterStatInstanceDTO, error) { return CharacterDomainCharacterStatInstanceToCharacterDomainCharacterStatInstanceDTO(&childDTOContext, &relationshipElement) })
      if err != nil {
         return nil, err
      }
   }

   if (slices.Contains(context.TraversedTables, reflect.TypeOf(includedSubClasses__CharacterDomainSubClassInstances).Elem().Name())) {
      includedSubClasses__CharacterDomainSubClassInstances = []types.CharacterDomainSubClassInstance{}
      fmt.Println("Hit circular catch case for table CharacterDomainSubClassInstance")
   } else {
      includedSubClasses__CharacterDomainSubClassInstances, err = services.GetCharacterDomainSubClassInstances(serviceContext, contextProviders.ProduceGetArgs[types.CharacterDomainSubClassInstance]("Character__Character", character.Id))
      if err != nil {
         return nil, err
      }
      SubClasses__CharacterDomainSubClassInstanceDTOs, err = utils.ErrorCompatibleMap(includedSubClasses__CharacterDomainSubClassInstances, func(relationshipElement types.CharacterDomainSubClassInstance) (*CharacterDomainSubClassInstanceDTO, error) { return CharacterDomainSubClassInstanceToCharacterDomainSubClassInstanceDTO(&childDTOContext, &relationshipElement) })
      if err != nil {
         return nil, err
      }
   }

   
   return &CharacterDTO{
      Id: character.Id,
      Attributes: CharacterDTOAttributes{
         AbbreviatedTitle: character.AbbreviatedTitle,
         CreatedAt: character.CreatedAt,
         Description: character.Description,
         
         IsActive: character.IsActive,
         Title: character.Title,
         UpdatedAt: character.UpdatedAt,
      },
      Relationships: CharacterDTORelationships{
         ManyToOne: CharacterDTOManyToOneRelationships {
            Campaign__Campaign: Campaign__CampaignDTO,
            CurrentSize__DomainSize: CurrentSize__DomainSizeDTO,
            ResourceOwner__User: ResourceOwner__UserDTO,
            Species__DomainSpecies: Species__DomainSpeciesDTO,
         },
         OneToMany: CharacterDTOOneToManyRelationships {
            Stats__CharacterDomainCharacterStatInstance: Stats__CharacterDomainCharacterStatInstanceDTOs,
            SubClasses__CharacterDomainSubClassInstance: SubClasses__CharacterDomainSubClassInstanceDTOs,
         },
      },
   }, nil
}

func CharacterDTOToCharacter(character *CharacterDTO) *types.Character {
   var tableTypeBuffer types.Character
   
   tableTypeBuffer.Id = character.Id
   tableTypeBuffer.AbbreviatedTitle = character.Attributes.AbbreviatedTitle
   tableTypeBuffer.CreatedAt = character.Attributes.CreatedAt
   tableTypeBuffer.Description = character.Attributes.Description
   
   tableTypeBuffer.IsActive = character.Attributes.IsActive
   tableTypeBuffer.Title = character.Attributes.Title
   tableTypeBuffer.UpdatedAt = character.Attributes.UpdatedAt
   
   if (character.Relationships.ManyToOne.Campaign__Campaign != nil) {
      tableTypeBuffer.Campaign__Campaign = character.Relationships.ManyToOne.Campaign__Campaign.Id
   }

   if (character.Relationships.ManyToOne.CurrentSize__DomainSize != nil) {
      tableTypeBuffer.CurrentSize__DomainSize = character.Relationships.ManyToOne.CurrentSize__DomainSize.Id
   }

   if (character.Relationships.ManyToOne.ResourceOwner__User != nil) {
      tableTypeBuffer.ResourceOwner__User = character.Relationships.ManyToOne.ResourceOwner__User.Id
   }

   if (character.Relationships.ManyToOne.Species__DomainSpecies != nil) {
      tableTypeBuffer.Species__DomainSpecies = character.Relationships.ManyToOne.Species__DomainSpecies.Id
   }

   return &tableTypeBuffer
}
