//*** CAUTION ***
//This is an autogenerated file produced by regenerateBackend.py.
//Edits made here will not persist after backend regeneration.

package generatedDTOs

import (
   types "AdventureEngineServer/generatedDatabaseTypes"
   
   services "AdventureEngineServer/generatedServices"
   "gorm.io/gorm"
   "fmt"
   "reflect"
   "slices"
)

type CharacterDomainSubClassInstanceDTOAttributes struct {
   AbbreviatedTitle *string
   CreatedAt *string
   Description *string
   
   IsActive *bool
   Level float64
   Title *string
   UpdatedAt *string
}

type CharacterDomainSubClassInstanceDTOManyToOneRelationships struct {
   Character__Character *CharacterDTO
   SubClass__DomainSubClass *DomainSubClassDTO
}

type CharacterDomainSubClassInstanceDTOOneToManyRelationships struct {
}

type CharacterDomainSubClassInstanceDTORelationships struct {
   ManyToOne CharacterDomainSubClassInstanceDTOManyToOneRelationships
   OneToMany CharacterDomainSubClassInstanceDTOOneToManyRelationships
}

type CharacterDomainSubClassInstanceDTO struct {
   Id *int
   
   Attributes CharacterDomainSubClassInstanceDTOAttributes
   
   Relationships CharacterDomainSubClassInstanceDTORelationships
}

func CharacterDomainSubClassInstanceToCharacterDomainSubClassInstanceDTO(db *gorm.DB, characterDomainSubClassInstance *types.CharacterDomainSubClassInstance, traversedTables []string) *CharacterDomainSubClassInstanceDTO {
   
   if (characterDomainSubClassInstance == nil) {
      fmt.Println("Nil pointer passed to DTO conversion for table CharacterDomainSubClassInstance")
      return nil
   }
   
   if (slices.Contains(traversedTables, reflect.TypeOf(*characterDomainSubClassInstance).Name())) {
      fmt.Println("Hit circular catch case for table CharacterDomainSubClassInstance")
      return nil
   }
   
   traversedTables = append(traversedTables, reflect.TypeOf(*characterDomainSubClassInstance).Name())
   
   var includedCharacter__Character types.Character
   var includedSubClass__DomainSubClass types.DomainSubClass
   
   if (characterDomainSubClassInstance.Character__Character != nil) {
      if err := services.GetCharacterById(db, int(*characterDomainSubClassInstance.Character__Character), &includedCharacter__Character); err != nil {
         fmt.Println("Error fetching many-to-one table Character:")
         fmt.Println(err)
      }
   }

   if (characterDomainSubClassInstance.SubClass__DomainSubClass != nil) {
      if err := services.GetDomainSubClassById(db, int(*characterDomainSubClassInstance.SubClass__DomainSubClass), &includedSubClass__DomainSubClass); err != nil {
         fmt.Println("Error fetching many-to-one table DomainSubClass:")
         fmt.Println(err)
      }
   }

   
   return &CharacterDomainSubClassInstanceDTO{
      Id: characterDomainSubClassInstance.Id,
      Attributes: CharacterDomainSubClassInstanceDTOAttributes{
         AbbreviatedTitle: characterDomainSubClassInstance.AbbreviatedTitle,
         CreatedAt: characterDomainSubClassInstance.CreatedAt,
         Description: characterDomainSubClassInstance.Description,
         
         IsActive: characterDomainSubClassInstance.IsActive,
         Level: characterDomainSubClassInstance.Level,
         Title: characterDomainSubClassInstance.Title,
         UpdatedAt: characterDomainSubClassInstance.UpdatedAt,
      },
      Relationships: CharacterDomainSubClassInstanceDTORelationships{
         ManyToOne: CharacterDomainSubClassInstanceDTOManyToOneRelationships {
            Character__Character: CharacterToCharacterDTO(db, &includedCharacter__Character, traversedTables),
            SubClass__DomainSubClass: DomainSubClassToDomainSubClassDTO(db, &includedSubClass__DomainSubClass, traversedTables),
         },
         OneToMany: CharacterDomainSubClassInstanceDTOOneToManyRelationships {
         },
      },
   }
}

func CharacterDomainSubClassInstanceDTOToCharacterDomainSubClassInstance(characterDomainSubClassInstance *CharacterDomainSubClassInstanceDTO) *types.CharacterDomainSubClassInstance {
   var tableTypeBuffer types.CharacterDomainSubClassInstance
   
   tableTypeBuffer.Id = characterDomainSubClassInstance.Id
   tableTypeBuffer.AbbreviatedTitle = characterDomainSubClassInstance.Attributes.AbbreviatedTitle
   tableTypeBuffer.CreatedAt = characterDomainSubClassInstance.Attributes.CreatedAt
   tableTypeBuffer.Description = characterDomainSubClassInstance.Attributes.Description
   
   tableTypeBuffer.IsActive = characterDomainSubClassInstance.Attributes.IsActive
   tableTypeBuffer.Level = characterDomainSubClassInstance.Attributes.Level
   tableTypeBuffer.Title = characterDomainSubClassInstance.Attributes.Title
   tableTypeBuffer.UpdatedAt = characterDomainSubClassInstance.Attributes.UpdatedAt
   
   if (characterDomainSubClassInstance.Relationships.ManyToOne.Character__Character != nil) {
      tableTypeBuffer.Character__Character = characterDomainSubClassInstance.Relationships.ManyToOne.Character__Character.Id
   }

   if (characterDomainSubClassInstance.Relationships.ManyToOne.SubClass__DomainSubClass != nil) {
      tableTypeBuffer.SubClass__DomainSubClass = characterDomainSubClassInstance.Relationships.ManyToOne.SubClass__DomainSubClass.Id
   }

   return &tableTypeBuffer
}
