//*** CAUTION ***
//This is an autogenerated file produced by regenerateBackend.py.
//Edits made here will not persist after backend regeneration.

package generatedDTOs

import (
   types "AdventureEngineServer/generatedDatabaseTypes"
   
   
   "gorm.io/gorm"
   "reflect"
   "slices"
)

type DomainStaticEffectDTOAttributes struct {
   Description *string
   
   IsActive *bool
   Title *string
}

type DomainStaticEffectDTOManyToOneRelationships struct {
}

type DomainStaticEffectDTOOneToManyRelationships struct {
}

type DomainStaticEffectDTORelationships struct {
   ManyToOne DomainStaticEffectDTOManyToOneRelationships
   OneToMany DomainStaticEffectDTOOneToManyRelationships
}

type DomainStaticEffectDTO struct {
   Id *float64
   
   Attributes DomainStaticEffectDTOAttributes
   
   Relationships DomainStaticEffectDTORelationships
}

func DomainStaticEffectToDomainStaticEffectDTO(db *gorm.DB, domainStaticEffect *types.DomainStaticEffect, traversedTables []string) *DomainStaticEffectDTO {
   
   if (slices.Contains(traversedTables, reflect.TypeOf(*domainStaticEffect).Name())) {
      print("Hit circular catch case for table DomainStaticEffect\n")
      return nil
   }
   
   traversedTables = append(traversedTables, reflect.TypeOf(*domainStaticEffect).Name())
   
   
   
   return &DomainStaticEffectDTO{
      Id: domainStaticEffect.Id,
      Attributes: DomainStaticEffectDTOAttributes{
         Description: domainStaticEffect.Description,
         
         IsActive: domainStaticEffect.IsActive,
         Title: domainStaticEffect.Title,
      },
      Relationships: DomainStaticEffectDTORelationships{
         ManyToOne: DomainStaticEffectDTOManyToOneRelationships {
         },
         OneToMany: DomainStaticEffectDTOOneToManyRelationships {
         },
      },
   }
}

func DomainStaticEffectDTOToDomainStaticEffect(domainStaticEffect *DomainStaticEffectDTO) types.DomainStaticEffect {
   return types.DomainStaticEffect{
      Id: domainStaticEffect.Id,
      Description: domainStaticEffect.Attributes.Description,
      
      IsActive: domainStaticEffect.Attributes.IsActive,
      Title: domainStaticEffect.Attributes.Title,
   }
}
