//*** CAUTION ***
//This is an autogenerated file produced by regenerateBackend.py.
//Edits made here will not persist after backend regeneration.

package generatedDTOs

import (
   types "AdventureEngineServer/generatedDatabaseTypes"
   utils "AdventureEngineServer/utils"
   services "AdventureEngineServer/generatedServices"
   "gorm.io/gorm"
   "reflect"
   "slices"
)

type DomainSpellDTOAttributes struct {
   ConcentrationRequired *bool
   DayDuration *float64
   Description *string
   HasSomaticRequirement *bool
   HasVerbalRequirement *bool
   HourCastTime *float64
   HourDuration *float64
   
   IsAction *bool
   IsActive *bool
   IsBonusAction *bool
   IsCantrip *bool
   IsInstantaneous *bool
   IsRitual *bool
   LastsUntilDispelled *bool
   LevelRequirement *float64
   MaterialComponent *string
   MinuteCastTime *float64
   MinuteDuration *float64
   RangeFeet *float64
   RangeMiles *float64
   RequiresTouch *bool
   RoundDuration *float64
   TargetsSelf *bool
   Title *string
}

type DomainSpellDTOManyToOneRelationships struct {
   DamageScaling__DomainDice *DomainDiceDTO
   School__DomainSpellSchool *DomainSpellSchoolDTO
}

type DomainSpellDTOOneToManyRelationships struct {
   Classes__ClassSpell []*ClassSpellDTO
}

type DomainSpellDTORelationships struct {
   ManyToOne DomainSpellDTOManyToOneRelationships
   OneToMany DomainSpellDTOOneToManyRelationships
}

type DomainSpellDTO struct {
   Id *float64
   
   Attributes DomainSpellDTOAttributes
   
   Relationships DomainSpellDTORelationships
}

func DomainSpellToDomainSpellDTO(db *gorm.DB, domainSpell *types.DomainSpell, traversedTables []string) *DomainSpellDTO {
   
   if (domainSpell == nil) {
      print("No valid pointer passed to DTO conversion for table DomainSpell")
      return nil
   }
   
   if (slices.Contains(traversedTables, reflect.TypeOf(*domainSpell).Name())) {
      print("Hit circular catch case for table DomainSpell\n")
      return nil
   }
   
   traversedTables = append(traversedTables, reflect.TypeOf(*domainSpell).Name())
   
   var includedDamageScaling__DomainDice types.DomainDice
   var includedSchool__DomainSpellSchool types.DomainSpellSchool
   var includedClasses__ClassSpells []types.ClassSpell
   
   if (domainSpell.DamageScaling__DomainDice != nil) {
      services.GetDomainDiceById(db, int(*domainSpell.DamageScaling__DomainDice), &includedDamageScaling__DomainDice)
   }

   if (domainSpell.School__DomainSpellSchool != nil) {
      services.GetDomainSpellSchoolById(db, int(*domainSpell.School__DomainSpellSchool), &includedSchool__DomainSpellSchool)
   }

   if (slices.Contains(traversedTables, reflect.TypeOf(includedClasses__ClassSpells).Elem().Name())) {
      services.GetClassSpellsByDomainSpellId(db, int(*domainSpell.Id), &includedClasses__ClassSpells)
   } else {
      includedClasses__ClassSpells = []types.ClassSpell{}
      print("Hit circular catch case for table ClassSpell\n")
   }

   
   return &DomainSpellDTO{
      Id: domainSpell.Id,
      Attributes: DomainSpellDTOAttributes{
         ConcentrationRequired: domainSpell.ConcentrationRequired,
         DayDuration: domainSpell.DayDuration,
         Description: domainSpell.Description,
         HasSomaticRequirement: domainSpell.HasSomaticRequirement,
         HasVerbalRequirement: domainSpell.HasVerbalRequirement,
         HourCastTime: domainSpell.HourCastTime,
         HourDuration: domainSpell.HourDuration,
         
         IsAction: domainSpell.IsAction,
         IsActive: domainSpell.IsActive,
         IsBonusAction: domainSpell.IsBonusAction,
         IsCantrip: domainSpell.IsCantrip,
         IsInstantaneous: domainSpell.IsInstantaneous,
         IsRitual: domainSpell.IsRitual,
         LastsUntilDispelled: domainSpell.LastsUntilDispelled,
         LevelRequirement: domainSpell.LevelRequirement,
         MaterialComponent: domainSpell.MaterialComponent,
         MinuteCastTime: domainSpell.MinuteCastTime,
         MinuteDuration: domainSpell.MinuteDuration,
         RangeFeet: domainSpell.RangeFeet,
         RangeMiles: domainSpell.RangeMiles,
         RequiresTouch: domainSpell.RequiresTouch,
         RoundDuration: domainSpell.RoundDuration,
         TargetsSelf: domainSpell.TargetsSelf,
         Title: domainSpell.Title,
      },
      Relationships: DomainSpellDTORelationships{
         ManyToOne: DomainSpellDTOManyToOneRelationships {
            DamageScaling__DomainDice: DomainDiceToDomainDiceDTO(db, &includedDamageScaling__DomainDice, traversedTables),
            School__DomainSpellSchool: DomainSpellSchoolToDomainSpellSchoolDTO(db, &includedSchool__DomainSpellSchool, traversedTables),
         },
         OneToMany: DomainSpellDTOOneToManyRelationships {
            Classes__ClassSpell: utils.Map(includedClasses__ClassSpells, func(relationshipElement types.ClassSpell) *ClassSpellDTO { return ClassSpellToClassSpellDTO(db, &relationshipElement, traversedTables) }),
         },
      },
   }
}

func DomainSpellDTOToDomainSpell(domainSpell *DomainSpellDTO) types.DomainSpell {
   return types.DomainSpell{
      Id: domainSpell.Id,
      ConcentrationRequired: domainSpell.Attributes.ConcentrationRequired,
      DayDuration: domainSpell.Attributes.DayDuration,
      Description: domainSpell.Attributes.Description,
      HasSomaticRequirement: domainSpell.Attributes.HasSomaticRequirement,
      HasVerbalRequirement: domainSpell.Attributes.HasVerbalRequirement,
      HourCastTime: domainSpell.Attributes.HourCastTime,
      HourDuration: domainSpell.Attributes.HourDuration,
      
      IsAction: domainSpell.Attributes.IsAction,
      IsActive: domainSpell.Attributes.IsActive,
      IsBonusAction: domainSpell.Attributes.IsBonusAction,
      IsCantrip: domainSpell.Attributes.IsCantrip,
      IsInstantaneous: domainSpell.Attributes.IsInstantaneous,
      IsRitual: domainSpell.Attributes.IsRitual,
      LastsUntilDispelled: domainSpell.Attributes.LastsUntilDispelled,
      LevelRequirement: domainSpell.Attributes.LevelRequirement,
      MaterialComponent: domainSpell.Attributes.MaterialComponent,
      MinuteCastTime: domainSpell.Attributes.MinuteCastTime,
      MinuteDuration: domainSpell.Attributes.MinuteDuration,
      RangeFeet: domainSpell.Attributes.RangeFeet,
      RangeMiles: domainSpell.Attributes.RangeMiles,
      RequiresTouch: domainSpell.Attributes.RequiresTouch,
      RoundDuration: domainSpell.Attributes.RoundDuration,
      TargetsSelf: domainSpell.Attributes.TargetsSelf,
      Title: domainSpell.Attributes.Title,
      DamageScaling__DomainDice: domainSpell.Relationships.ManyToOne.DamageScaling__DomainDice.Id,
      School__DomainSpellSchool: domainSpell.Relationships.ManyToOne.School__DomainSpellSchool.Id,
   }
}
