//*** CAUTION ***
//This is an autogenerated file produced by regenerateBackend.py.
//Edits made here will not persist after backend regeneration.

package generatedDTOs

import (
   types "AdventureEngineServer/generatedDatabaseTypes"
   utils "AdventureEngineServer/utils"
   services "AdventureEngineServer/generatedServices"
   "gorm.io/gorm"
   "fmt"
   "reflect"
   "slices"
)

type DomainClassTraitDTOAttributes struct {
   AbbreviatedTitle *string
   CreatedAt *string
   Description *string
   
   IsActive *bool
   Title *string
   UpdatedAt *string
}

type DomainClassTraitDTOManyToOneRelationships struct {
   Class__DomainClass *DomainClassDTO
   ResourceOwner__User *UserDTO
   SubClass__DomainSubClass *DomainSubClassDTO
}

type DomainClassTraitDTOOneToManyRelationships struct {
   Quantifiers__Quantifier []*QuantifierDTO
}

type DomainClassTraitDTORelationships struct {
   ManyToOne DomainClassTraitDTOManyToOneRelationships
   OneToMany DomainClassTraitDTOOneToManyRelationships
}

type DomainClassTraitDTO struct {
   Id *int
   
   Attributes DomainClassTraitDTOAttributes
   
   Relationships DomainClassTraitDTORelationships
}

func DomainClassTraitToDomainClassTraitDTO(db *gorm.DB, domainClassTrait *types.DomainClassTrait, traversedTables []string) *DomainClassTraitDTO {
   
   if (domainClassTrait == nil) {
      fmt.Println("Nil pointer passed to DTO conversion for table DomainClassTrait")
      return nil
   }
   
   if (slices.Contains(traversedTables, reflect.TypeOf(*domainClassTrait).Name())) {
      fmt.Println("Hit circular catch case for table DomainClassTrait")
      return nil
   }
   
   traversedTables = append(traversedTables, reflect.TypeOf(*domainClassTrait).Name())
   
   var includedClass__DomainClass types.DomainClass
   var includedResourceOwner__User types.User
   var includedSubClass__DomainSubClass types.DomainSubClass
   var includedQuantifiers__Quantifiers []types.Quantifier
   
   if (domainClassTrait.Class__DomainClass != nil) {
      if err := services.GetDomainClassById(db, int(*domainClassTrait.Class__DomainClass), &includedClass__DomainClass); err != nil {
         fmt.Println("Error fetching many-to-one table DomainClass:")
         fmt.Println(err)
      }
   }

   if (domainClassTrait.ResourceOwner__User != nil) {
      if err := services.GetUserById(db, int(*domainClassTrait.ResourceOwner__User), &includedResourceOwner__User); err != nil {
         fmt.Println("Error fetching many-to-one table User:")
         fmt.Println(err)
      }
   }

   if (domainClassTrait.SubClass__DomainSubClass != nil) {
      if err := services.GetDomainSubClassById(db, int(*domainClassTrait.SubClass__DomainSubClass), &includedSubClass__DomainSubClass); err != nil {
         fmt.Println("Error fetching many-to-one table DomainSubClass:")
         fmt.Println(err)
      }
   }

   if (slices.Contains(traversedTables, reflect.TypeOf(includedQuantifiers__Quantifiers).Elem().Name())) {
      includedQuantifiers__Quantifiers = []types.Quantifier{}
      fmt.Println("Hit circular catch case for table Quantifier")
   } else {
      services.GetQuantifiersByDomainClassTraitId(db, int(*domainClassTrait.Id), &includedQuantifiers__Quantifiers)
   }

   
   return &DomainClassTraitDTO{
      Id: domainClassTrait.Id,
      Attributes: DomainClassTraitDTOAttributes{
         AbbreviatedTitle: domainClassTrait.AbbreviatedTitle,
         CreatedAt: domainClassTrait.CreatedAt,
         Description: domainClassTrait.Description,
         
         IsActive: domainClassTrait.IsActive,
         Title: domainClassTrait.Title,
         UpdatedAt: domainClassTrait.UpdatedAt,
      },
      Relationships: DomainClassTraitDTORelationships{
         ManyToOne: DomainClassTraitDTOManyToOneRelationships {
            Class__DomainClass: DomainClassToDomainClassDTO(db, &includedClass__DomainClass, traversedTables),
            ResourceOwner__User: UserToUserDTO(db, &includedResourceOwner__User, traversedTables),
            SubClass__DomainSubClass: DomainSubClassToDomainSubClassDTO(db, &includedSubClass__DomainSubClass, traversedTables),
         },
         OneToMany: DomainClassTraitDTOOneToManyRelationships {
            Quantifiers__Quantifier: utils.Map(includedQuantifiers__Quantifiers, func(relationshipElement types.Quantifier) *QuantifierDTO { return QuantifierToQuantifierDTO(db, &relationshipElement, traversedTables) }),
         },
      },
   }
}

func DomainClassTraitDTOToDomainClassTrait(domainClassTrait *DomainClassTraitDTO) *types.DomainClassTrait {
   var tableTypeBuffer types.DomainClassTrait
   
   tableTypeBuffer.Id = domainClassTrait.Id
   tableTypeBuffer.AbbreviatedTitle = domainClassTrait.Attributes.AbbreviatedTitle
   tableTypeBuffer.CreatedAt = domainClassTrait.Attributes.CreatedAt
   tableTypeBuffer.Description = domainClassTrait.Attributes.Description
   
   tableTypeBuffer.IsActive = domainClassTrait.Attributes.IsActive
   tableTypeBuffer.Title = domainClassTrait.Attributes.Title
   tableTypeBuffer.UpdatedAt = domainClassTrait.Attributes.UpdatedAt
   
   if (domainClassTrait.Relationships.ManyToOne.Class__DomainClass != nil) {
      tableTypeBuffer.Class__DomainClass = domainClassTrait.Relationships.ManyToOne.Class__DomainClass.Id
   }

   if (domainClassTrait.Relationships.ManyToOne.ResourceOwner__User != nil) {
      tableTypeBuffer.ResourceOwner__User = domainClassTrait.Relationships.ManyToOne.ResourceOwner__User.Id
   }

   if (domainClassTrait.Relationships.ManyToOne.SubClass__DomainSubClass != nil) {
      tableTypeBuffer.SubClass__DomainSubClass = domainClassTrait.Relationships.ManyToOne.SubClass__DomainSubClass.Id
   }

   return &tableTypeBuffer
}
