//*** CAUTION ***
//This is an autogenerated file produced by regenerateBackend.py.
//Edits made here will not persist after backend regeneration.

package generatedDTOs

import (
   contextProviders "AdventureEngineServer/contextProviders"
   types "AdventureEngineServer/generatedDatabaseTypes"
   
   services "AdventureEngineServer/generatedServices"
   "errors"
   "fmt"
   "reflect"
   "slices"
)

type DomainAppRoleDTOAttributes struct {
   AbbreviatedTitle *string
   CreatedAt *string
   Description *string
   
   IsActive *bool
   Title *string
   UpdatedAt *string
}

type DomainAppRoleDTOManyToOneRelationships struct {
   ResourceOwner__User *UserDTO
}

type DomainAppRoleDTOOneToManyRelationships struct {
}

type DomainAppRoleDTORelationships struct {
   ManyToOne DomainAppRoleDTOManyToOneRelationships
   OneToMany DomainAppRoleDTOOneToManyRelationships
}

type DomainAppRoleDTO struct {
   Id *int
   
   Attributes DomainAppRoleDTOAttributes
   
   Relationships DomainAppRoleDTORelationships
}

func DomainAppRoleToDomainAppRoleDTO(context *contextProviders.DTOContext, domainAppRole *types.DomainAppRole) (*DomainAppRoleDTO, error) {
   if context == nil {
      return nil, errors.New("No DTO context provided")
   }
   
   if (domainAppRole == nil) {
      return nil, errors.New("Cannot convert nil pointer passed to DTO conversion for table DomainAppRole")
   }
   
   if (slices.Contains(context.TraversedTables, reflect.TypeOf(*domainAppRole).Name())) {
      fmt.Println("Hit circular catch case for table DomainAppRole")
      return nil, nil
   }
   
   childDTOContext := contextProviders.DTOContext{
      DatabaseContext: context.DatabaseContext,
      TraversedTables: append(context.TraversedTables, reflect.TypeOf(*domainAppRole).Name()),
   }
   serviceContext := &contextProviders.ServiceContext{
      DatabaseContext: context.DatabaseContext,
      CurrentUser: nil,
   }
   
   var includedResourceOwner__User *types.User
   
   var ResourceOwner__UserDTO *UserDTO
   
   var err error
   
   if (domainAppRole.ResourceOwner__User != nil) {
      includedResourceOwner__User, err = services.GetUserById(serviceContext, contextProviders.ProduceGetByIdArgs[types.User](domainAppRole.ResourceOwner__User))
      if err != nil {
         return nil, err
      }
      ResourceOwner__UserDTO, err = UserToUserDTO(&childDTOContext, includedResourceOwner__User)
      if err != nil {
         return nil, err
      }
   }

   
   return &DomainAppRoleDTO{
      Id: domainAppRole.Id,
      Attributes: DomainAppRoleDTOAttributes{
         AbbreviatedTitle: domainAppRole.AbbreviatedTitle,
         CreatedAt: domainAppRole.CreatedAt,
         Description: domainAppRole.Description,
         
         IsActive: domainAppRole.IsActive,
         Title: domainAppRole.Title,
         UpdatedAt: domainAppRole.UpdatedAt,
      },
      Relationships: DomainAppRoleDTORelationships{
         ManyToOne: DomainAppRoleDTOManyToOneRelationships {
            ResourceOwner__User: ResourceOwner__UserDTO,
         },
         OneToMany: DomainAppRoleDTOOneToManyRelationships {
         },
      },
   }, nil
}

func DomainAppRoleDTOToDomainAppRole(domainAppRole *DomainAppRoleDTO) *types.DomainAppRole {
   var tableTypeBuffer types.DomainAppRole
   
   tableTypeBuffer.Id = domainAppRole.Id
   tableTypeBuffer.AbbreviatedTitle = domainAppRole.Attributes.AbbreviatedTitle
   tableTypeBuffer.CreatedAt = domainAppRole.Attributes.CreatedAt
   tableTypeBuffer.Description = domainAppRole.Attributes.Description
   
   tableTypeBuffer.IsActive = domainAppRole.Attributes.IsActive
   tableTypeBuffer.Title = domainAppRole.Attributes.Title
   tableTypeBuffer.UpdatedAt = domainAppRole.Attributes.UpdatedAt
   
   if (domainAppRole.Relationships.ManyToOne.ResourceOwner__User != nil) {
      tableTypeBuffer.ResourceOwner__User = domainAppRole.Relationships.ManyToOne.ResourceOwner__User.Id
   }

   return &tableTypeBuffer
}
