//*** CAUTION ***
//This is an autogenerated file produced by regenerateBackend.py.
//Edits made here will not persist after backend regeneration.

package generatedDTOs

import (
   contextProviders "AdventureEngineServer/contextProviders"
   types "AdventureEngineServer/generatedDatabaseTypes"
   
   services "AdventureEngineServer/generatedServices"
   "errors"
   "fmt"
   "reflect"
   "slices"
)

type DomainEntityStatDTOAttributes struct {
   AbbreviatedTitle *string
   CreatedAt *string
   Description *string
   
   IsActive *bool
   IsBaseStat bool
   Title *string
   UpdatedAt *string
}

type DomainEntityStatDTOManyToOneRelationships struct {
   ResourceOwner__User *UserDTO
}

type DomainEntityStatDTOOneToManyRelationships struct {
}

type DomainEntityStatDTORelationships struct {
   ManyToOne DomainEntityStatDTOManyToOneRelationships
   OneToMany DomainEntityStatDTOOneToManyRelationships
}

type DomainEntityStatDTO struct {
   Id *int
   
   Attributes DomainEntityStatDTOAttributes
   
   Relationships DomainEntityStatDTORelationships
}

func DomainEntityStatToDomainEntityStatDTO(context *contextProviders.DTOContext, domainEntityStat *types.DomainEntityStat) (*DomainEntityStatDTO, error) {
   if context == nil {
      return nil, errors.New("No DTO context provided")
   }
   
   if (domainEntityStat == nil) {
      return nil, errors.New("Cannot convert nil pointer passed to DTO conversion for table DomainEntityStat")
   }
   
   if (slices.Contains(context.TraversedTables, reflect.TypeOf(*domainEntityStat).Name())) {
      fmt.Println("Hit circular catch case for table DomainEntityStat")
      return nil, nil
   }
   
   childDTOContext := contextProviders.DTOContext{
      DatabaseContext: context.DatabaseContext,
      TraversedTables: append(context.TraversedTables, reflect.TypeOf(*domainEntityStat).Name()),
   }
   serviceContext := &contextProviders.ServiceContext{
      DatabaseContext: context.DatabaseContext,
      CurrentUser: nil,
   }
   
   var includedResourceOwner__User *types.User
   
   var ResourceOwner__UserDTO *UserDTO
   
   var err error
   
   if (domainEntityStat.ResourceOwner__User != nil) {
      includedResourceOwner__User, err = services.GetUserById(serviceContext, contextProviders.ProduceGetByIdArgs[types.User](domainEntityStat.ResourceOwner__User))
      if err != nil {
         return nil, err
      }
      ResourceOwner__UserDTO, err = UserToUserDTO(&childDTOContext, includedResourceOwner__User)
      if err != nil {
         return nil, err
      }
   }

   
   return &DomainEntityStatDTO{
      Id: domainEntityStat.Id,
      Attributes: DomainEntityStatDTOAttributes{
         AbbreviatedTitle: domainEntityStat.AbbreviatedTitle,
         CreatedAt: domainEntityStat.CreatedAt,
         Description: domainEntityStat.Description,
         
         IsActive: domainEntityStat.IsActive,
         IsBaseStat: domainEntityStat.IsBaseStat,
         Title: domainEntityStat.Title,
         UpdatedAt: domainEntityStat.UpdatedAt,
      },
      Relationships: DomainEntityStatDTORelationships{
         ManyToOne: DomainEntityStatDTOManyToOneRelationships {
            ResourceOwner__User: ResourceOwner__UserDTO,
         },
         OneToMany: DomainEntityStatDTOOneToManyRelationships {
         },
      },
   }, nil
}

func DomainEntityStatDTOToDomainEntityStat(domainEntityStat *DomainEntityStatDTO) *types.DomainEntityStat {
   var tableTypeBuffer types.DomainEntityStat
   
   tableTypeBuffer.Id = domainEntityStat.Id
   tableTypeBuffer.AbbreviatedTitle = domainEntityStat.Attributes.AbbreviatedTitle
   tableTypeBuffer.CreatedAt = domainEntityStat.Attributes.CreatedAt
   tableTypeBuffer.Description = domainEntityStat.Attributes.Description
   
   tableTypeBuffer.IsActive = domainEntityStat.Attributes.IsActive
   tableTypeBuffer.IsBaseStat = domainEntityStat.Attributes.IsBaseStat
   tableTypeBuffer.Title = domainEntityStat.Attributes.Title
   tableTypeBuffer.UpdatedAt = domainEntityStat.Attributes.UpdatedAt
   
   if (domainEntityStat.Relationships.ManyToOne.ResourceOwner__User != nil) {
      tableTypeBuffer.ResourceOwner__User = domainEntityStat.Relationships.ManyToOne.ResourceOwner__User.Id
   }

   return &tableTypeBuffer
}
