//*** CAUTION ***
//This is an autogenerated file produced by regenerateBackend.py.
//Edits made here will not persist after backend regeneration.

package generatedDTOs

import (
   contextProviders "AdventureEngineServer/contextProviders"
   types "AdventureEngineServer/generatedDatabaseTypes"
   
   services "AdventureEngineServer/generatedServices"
   "errors"
   "fmt"
   "reflect"
   "slices"
)

type DomainLanguageDTOAttributes struct {
   AbbreviatedTitle *string
   CreatedAt *string
   Description *string
   
   IsActive *bool
   Title *string
   UpdatedAt *string
}

type DomainLanguageDTOManyToOneRelationships struct {
   ResourceOwner__User *UserDTO
}

type DomainLanguageDTOOneToManyRelationships struct {
}

type DomainLanguageDTORelationships struct {
   ManyToOne DomainLanguageDTOManyToOneRelationships
   OneToMany DomainLanguageDTOOneToManyRelationships
}

type DomainLanguageDTO struct {
   Id *int
   
   Attributes DomainLanguageDTOAttributes
   
   Relationships DomainLanguageDTORelationships
}

func DomainLanguageToDomainLanguageDTO(context *contextProviders.DTOContext, domainLanguage *types.DomainLanguage) (*DomainLanguageDTO, error) {
   if context == nil {
      return nil, errors.New("No DTO context provided")
   }
   
   if (domainLanguage == nil) {
      return nil, errors.New("Cannot convert nil pointer passed to DTO conversion for table DomainLanguage")
   }
   
   if (slices.Contains(context.TraversedTables, reflect.TypeOf(*domainLanguage).Name())) {
      fmt.Println("Hit circular catch case for table DomainLanguage")
      return nil, nil
   }
   
   childDTOContext := contextProviders.DTOContext{
      DatabaseContext: context.DatabaseContext,
      TraversedTables: append(context.TraversedTables, reflect.TypeOf(*domainLanguage).Name()),
   }
   serviceContext := &contextProviders.ServiceContext{
      DatabaseContext: context.DatabaseContext,
      CurrentUser: nil,
   }
   
   var includedResourceOwner__User *types.User
   
   var ResourceOwner__UserDTO *UserDTO
   
   var err error
   
   if (domainLanguage.ResourceOwner__User != nil) {
      includedResourceOwner__User, err = services.GetUserById(serviceContext, contextProviders.ProduceGetByIdArgs[types.User](domainLanguage.ResourceOwner__User))
      if err != nil {
         return nil, err
      }
      ResourceOwner__UserDTO, err = UserToUserDTO(&childDTOContext, includedResourceOwner__User)
      if err != nil {
         return nil, err
      }
   }

   
   return &DomainLanguageDTO{
      Id: domainLanguage.Id,
      Attributes: DomainLanguageDTOAttributes{
         AbbreviatedTitle: domainLanguage.AbbreviatedTitle,
         CreatedAt: domainLanguage.CreatedAt,
         Description: domainLanguage.Description,
         
         IsActive: domainLanguage.IsActive,
         Title: domainLanguage.Title,
         UpdatedAt: domainLanguage.UpdatedAt,
      },
      Relationships: DomainLanguageDTORelationships{
         ManyToOne: DomainLanguageDTOManyToOneRelationships {
            ResourceOwner__User: ResourceOwner__UserDTO,
         },
         OneToMany: DomainLanguageDTOOneToManyRelationships {
         },
      },
   }, nil
}

func DomainLanguageDTOToDomainLanguage(domainLanguage *DomainLanguageDTO) *types.DomainLanguage {
   var tableTypeBuffer types.DomainLanguage
   
   tableTypeBuffer.Id = domainLanguage.Id
   tableTypeBuffer.AbbreviatedTitle = domainLanguage.Attributes.AbbreviatedTitle
   tableTypeBuffer.CreatedAt = domainLanguage.Attributes.CreatedAt
   tableTypeBuffer.Description = domainLanguage.Attributes.Description
   
   tableTypeBuffer.IsActive = domainLanguage.Attributes.IsActive
   tableTypeBuffer.Title = domainLanguage.Attributes.Title
   tableTypeBuffer.UpdatedAt = domainLanguage.Attributes.UpdatedAt
   
   if (domainLanguage.Relationships.ManyToOne.ResourceOwner__User != nil) {
      tableTypeBuffer.ResourceOwner__User = domainLanguage.Relationships.ManyToOne.ResourceOwner__User.Id
   }

   return &tableTypeBuffer
}
