//*** CAUTION ***
//This is an autogenerated file produced by regenerateBackend.py.
//Edits made here will not persist after backend regeneration.

package generatedDTOs

import (
   types "AdventureEngineServer/generatedDatabaseTypes"
   
   
   "gorm.io/gorm"
   "reflect"
)

type DomainConditionDTOAttributes struct {
   Description *string
   IsActive *bool
   Title *string
   
}

type DomainConditionDTORelationships struct {
}

type DomainConditionDTO struct {
   Id *float64
   
   Attributes DomainConditionDTOAttributes
   
   Relationships DomainConditionDTORelationships
}

func DomainConditionToDomainConditionDTO(db *gorm.DB, domainCondition *types.DomainCondition, originTable *string) *DomainConditionDTO {
   
   if (originTable != nil && *originTable == reflect.TypeOf(*domainCondition).Name()) {
      print("Hit circular catch case for table DomainCondition\n")
      return nil
   }
   if (originTable == nil) {
      var tableName string = reflect.TypeOf(*domainCondition).Name()
      originTable = &tableName
   }
   
   
   return &DomainConditionDTO{
      Id: domainCondition.Id,
      Attributes: DomainConditionDTOAttributes{
         Description: domainCondition.Description,
         IsActive: domainCondition.IsActive,
         Title: domainCondition.Title,
         
      },
      Relationships: DomainConditionDTORelationships{
      },
   }
}

func DomainConditionDTOToDomainCondition(domainCondition *DomainConditionDTO) types.DomainCondition {
   return types.DomainCondition{
      Id: domainCondition.Id,
      Description: domainCondition.Attributes.Description,
      IsActive: domainCondition.Attributes.IsActive,
      Title: domainCondition.Attributes.Title,
      
   }
}
