//*** CAUTION ***
//This is an autogenerated file produced by regenerateBackend.py.
//Edits made here will not persist after backend regeneration.

package generatedDTOs

import (
   types "AdventureEngineServer/generatedDatabaseTypes"
   
   
   "gorm.io/gorm"
   "fmt"
   "reflect"
   "slices"
)

type DomainSpellSchoolDTOAttributes struct {
   AbbreviatedTitle *string
   Description *string
   
   IsActive *bool
   Title *string
}

type DomainSpellSchoolDTOManyToOneRelationships struct {
}

type DomainSpellSchoolDTOOneToManyRelationships struct {
}

type DomainSpellSchoolDTORelationships struct {
   ManyToOne DomainSpellSchoolDTOManyToOneRelationships
   OneToMany DomainSpellSchoolDTOOneToManyRelationships
}

type DomainSpellSchoolDTO struct {
   Id *int
   
   Attributes DomainSpellSchoolDTOAttributes
   
   Relationships DomainSpellSchoolDTORelationships
}

func DomainSpellSchoolToDomainSpellSchoolDTO(db *gorm.DB, domainSpellSchool *types.DomainSpellSchool, traversedTables []string) *DomainSpellSchoolDTO {
   
   if (domainSpellSchool == nil) {
      fmt.Println("Nil pointer passed to DTO conversion for table DomainSpellSchool")
      return nil
   }
   
   if (slices.Contains(traversedTables, reflect.TypeOf(*domainSpellSchool).Name())) {
      fmt.Println("Hit circular catch case for table DomainSpellSchool")
      return nil
   }
   
   traversedTables = append(traversedTables, reflect.TypeOf(*domainSpellSchool).Name())
   
   
   
   return &DomainSpellSchoolDTO{
      Id: domainSpellSchool.Id,
      Attributes: DomainSpellSchoolDTOAttributes{
         AbbreviatedTitle: domainSpellSchool.AbbreviatedTitle,
         Description: domainSpellSchool.Description,
         
         IsActive: domainSpellSchool.IsActive,
         Title: domainSpellSchool.Title,
      },
      Relationships: DomainSpellSchoolDTORelationships{
         ManyToOne: DomainSpellSchoolDTOManyToOneRelationships {
         },
         OneToMany: DomainSpellSchoolDTOOneToManyRelationships {
         },
      },
   }
}

func DomainSpellSchoolDTOToDomainSpellSchool(domainSpellSchool *DomainSpellSchoolDTO) *types.DomainSpellSchool {
   var tableTypeBuffer types.DomainSpellSchool
   
   tableTypeBuffer.Id = domainSpellSchool.Id
   tableTypeBuffer.AbbreviatedTitle = domainSpellSchool.Attributes.AbbreviatedTitle
   tableTypeBuffer.Description = domainSpellSchool.Attributes.Description
   
   tableTypeBuffer.IsActive = domainSpellSchool.Attributes.IsActive
   tableTypeBuffer.Title = domainSpellSchool.Attributes.Title
   
   return &tableTypeBuffer
}
