//*** CAUTION ***
//This is an autogenerated file produced by regenerateBackend.py.
//Edits made here will not persist after backend regeneration.

package generatedDTOs

import (
   types "AdventureEngineServer/generatedDatabaseTypes"
   utils "AdventureEngineServer/utils"
   services "AdventureEngineServer/generatedServices"
   "gorm.io/gorm"
   "fmt"
   "reflect"
   "slices"
)

type DomainActionDTOAttributes struct {
   AbbreviatedTitle *string
   CreatedAt *string
   Description *string
   
   IsActive *bool
   Title *string
   UpdatedAt *string
}

type DomainActionDTOManyToOneRelationships struct {
   ResourceOwner__User *UserDTO
}

type DomainActionDTOOneToManyRelationships struct {
   Quantifiers__Quantifier []*QuantifierDTO
}

type DomainActionDTORelationships struct {
   ManyToOne DomainActionDTOManyToOneRelationships
   OneToMany DomainActionDTOOneToManyRelationships
}

type DomainActionDTO struct {
   Id *int
   
   Attributes DomainActionDTOAttributes
   
   Relationships DomainActionDTORelationships
}

func DomainActionToDomainActionDTO(db *gorm.DB, domainAction *types.DomainAction, traversedTables []string) *DomainActionDTO {
   
   if (domainAction == nil) {
      fmt.Println("Nil pointer passed to DTO conversion for table DomainAction")
      return nil
   }
   
   if (slices.Contains(traversedTables, reflect.TypeOf(*domainAction).Name())) {
      fmt.Println("Hit circular catch case for table DomainAction")
      return nil
   }
   
   traversedTables = append(traversedTables, reflect.TypeOf(*domainAction).Name())
   
   var includedResourceOwner__User types.User
   var includedQuantifiers__Quantifiers []types.Quantifier
   
   if (domainAction.ResourceOwner__User != nil) {
      if err := services.GetUserById(db, int(*domainAction.ResourceOwner__User), &includedResourceOwner__User); err != nil {
         fmt.Println("Error fetching many-to-one table User:")
         fmt.Println(err)
      }
   }

   if (slices.Contains(traversedTables, reflect.TypeOf(includedQuantifiers__Quantifiers).Elem().Name())) {
      includedQuantifiers__Quantifiers = []types.Quantifier{}
      fmt.Println("Hit circular catch case for table Quantifier")
   } else {
      services.GetQuantifiersByDomainActionId(db, int(*domainAction.Id), &includedQuantifiers__Quantifiers)
   }

   
   return &DomainActionDTO{
      Id: domainAction.Id,
      Attributes: DomainActionDTOAttributes{
         AbbreviatedTitle: domainAction.AbbreviatedTitle,
         CreatedAt: domainAction.CreatedAt,
         Description: domainAction.Description,
         
         IsActive: domainAction.IsActive,
         Title: domainAction.Title,
         UpdatedAt: domainAction.UpdatedAt,
      },
      Relationships: DomainActionDTORelationships{
         ManyToOne: DomainActionDTOManyToOneRelationships {
            ResourceOwner__User: UserToUserDTO(db, &includedResourceOwner__User, traversedTables),
         },
         OneToMany: DomainActionDTOOneToManyRelationships {
            Quantifiers__Quantifier: utils.Map(includedQuantifiers__Quantifiers, func(relationshipElement types.Quantifier) *QuantifierDTO { return QuantifierToQuantifierDTO(db, &relationshipElement, traversedTables) }),
         },
      },
   }
}

func DomainActionDTOToDomainAction(domainAction *DomainActionDTO) *types.DomainAction {
   var tableTypeBuffer types.DomainAction
   
   tableTypeBuffer.Id = domainAction.Id
   tableTypeBuffer.AbbreviatedTitle = domainAction.Attributes.AbbreviatedTitle
   tableTypeBuffer.CreatedAt = domainAction.Attributes.CreatedAt
   tableTypeBuffer.Description = domainAction.Attributes.Description
   
   tableTypeBuffer.IsActive = domainAction.Attributes.IsActive
   tableTypeBuffer.Title = domainAction.Attributes.Title
   tableTypeBuffer.UpdatedAt = domainAction.Attributes.UpdatedAt
   
   if (domainAction.Relationships.ManyToOne.ResourceOwner__User != nil) {
      tableTypeBuffer.ResourceOwner__User = domainAction.Relationships.ManyToOne.ResourceOwner__User.Id
   }

   return &tableTypeBuffer
}
