//*** CAUTION ***
//This is an autogenerated file produced by regenerateBackend.py.
//Edits made here will not persist after backend regeneration.

package generatedDTOs

import (
   contextProviders "AdventureEngineServer/contextProviders"
   types "AdventureEngineServer/generatedDatabaseTypes"
   
   services "AdventureEngineServer/generatedServices"
   "errors"
   "fmt"
   "reflect"
   "slices"
)

type DomainBooleanConditionDTOAttributes struct {
   AbbreviatedTitle *string
   CreatedAt *string
   Description *string
   
   IsActive *bool
   Title *string
   UpdatedAt *string
}

type DomainBooleanConditionDTOManyToOneRelationships struct {
   ResourceOwner__User *UserDTO
}

type DomainBooleanConditionDTOOneToManyRelationships struct {
}

type DomainBooleanConditionDTORelationships struct {
   ManyToOne DomainBooleanConditionDTOManyToOneRelationships
   OneToMany DomainBooleanConditionDTOOneToManyRelationships
}

type DomainBooleanConditionDTO struct {
   Id *int
   
   Attributes DomainBooleanConditionDTOAttributes
   
   Relationships DomainBooleanConditionDTORelationships
}

func DomainBooleanConditionToDomainBooleanConditionDTO(context *contextProviders.DTOContext, domainBooleanCondition *types.DomainBooleanCondition) (*DomainBooleanConditionDTO, error) {
   if context == nil {
      return nil, errors.New("No DTO context provided")
   }
   
   if (domainBooleanCondition == nil) {
      return nil, errors.New("Cannot convert nil pointer passed to DTO conversion for table DomainBooleanCondition")
   }
   
   if (slices.Contains(context.TraversedTables, reflect.TypeOf(*domainBooleanCondition).Name())) {
      fmt.Println("Hit circular catch case for table DomainBooleanCondition")
      return nil, nil
   }
   
   childDTOContext := contextProviders.DTOContext{
      DatabaseContext: context.DatabaseContext,
      TraversedTables: append(context.TraversedTables, reflect.TypeOf(*domainBooleanCondition).Name()),
   }
   serviceContext := &contextProviders.ServiceContext{
      DatabaseContext: context.DatabaseContext,
      CurrentUser: nil,
   }
   
   var includedResourceOwner__User *types.User
   
   var ResourceOwner__UserDTO *UserDTO
   
   var err error
   
   if (domainBooleanCondition.ResourceOwner__User != nil) {
      includedResourceOwner__User, err = services.GetUserById(serviceContext, contextProviders.ProduceGetByIdArgs[types.User](domainBooleanCondition.ResourceOwner__User))
      if err != nil {
         return nil, err
      }
      ResourceOwner__UserDTO, err = UserToUserDTO(&childDTOContext, includedResourceOwner__User)
      if err != nil {
         return nil, err
      }
   }

   
   return &DomainBooleanConditionDTO{
      Id: domainBooleanCondition.Id,
      Attributes: DomainBooleanConditionDTOAttributes{
         AbbreviatedTitle: domainBooleanCondition.AbbreviatedTitle,
         CreatedAt: domainBooleanCondition.CreatedAt,
         Description: domainBooleanCondition.Description,
         
         IsActive: domainBooleanCondition.IsActive,
         Title: domainBooleanCondition.Title,
         UpdatedAt: domainBooleanCondition.UpdatedAt,
      },
      Relationships: DomainBooleanConditionDTORelationships{
         ManyToOne: DomainBooleanConditionDTOManyToOneRelationships {
            ResourceOwner__User: ResourceOwner__UserDTO,
         },
         OneToMany: DomainBooleanConditionDTOOneToManyRelationships {
         },
      },
   }, nil
}

func DomainBooleanConditionDTOToDomainBooleanCondition(domainBooleanCondition *DomainBooleanConditionDTO) *types.DomainBooleanCondition {
   var tableTypeBuffer types.DomainBooleanCondition
   
   tableTypeBuffer.Id = domainBooleanCondition.Id
   tableTypeBuffer.AbbreviatedTitle = domainBooleanCondition.Attributes.AbbreviatedTitle
   tableTypeBuffer.CreatedAt = domainBooleanCondition.Attributes.CreatedAt
   tableTypeBuffer.Description = domainBooleanCondition.Attributes.Description
   
   tableTypeBuffer.IsActive = domainBooleanCondition.Attributes.IsActive
   tableTypeBuffer.Title = domainBooleanCondition.Attributes.Title
   tableTypeBuffer.UpdatedAt = domainBooleanCondition.Attributes.UpdatedAt
   
   if (domainBooleanCondition.Relationships.ManyToOne.ResourceOwner__User != nil) {
      tableTypeBuffer.ResourceOwner__User = domainBooleanCondition.Relationships.ManyToOne.ResourceOwner__User.Id
   }

   return &tableTypeBuffer
}
