//*** CAUTION ***
//This is an autogenerated file produced by regenerateBackend.py.
//Edits made here will not persist after backend regeneration.

package generatedDTOs

import (
   contextProviders "AdventureEngineServer/contextProviders"
   types "AdventureEngineServer/generatedDatabaseTypes"
   
   services "AdventureEngineServer/generatedServices"
   "errors"
   "fmt"
   "reflect"
   "slices"
)

type DomainClassResourceDTOAttributes struct {
   AbbreviatedTitle *string
   CreatedAt *string
   Description *string
   
   IsActive *bool
   Title *string
   UpdatedAt *string
}

type DomainClassResourceDTOManyToOneRelationships struct {
   Parent__DomainClass *DomainClassDTO
   Parent__DomainSubClass *DomainSubClassDTO
   ResourceOwner__User *UserDTO
}

type DomainClassResourceDTOOneToManyRelationships struct {
}

type DomainClassResourceDTORelationships struct {
   ManyToOne DomainClassResourceDTOManyToOneRelationships
   OneToMany DomainClassResourceDTOOneToManyRelationships
}

type DomainClassResourceDTO struct {
   Id *int
   
   Attributes DomainClassResourceDTOAttributes
   
   Relationships DomainClassResourceDTORelationships
}

func DomainClassResourceToDomainClassResourceDTO(context *contextProviders.DTOContext, domainClassResource *types.DomainClassResource) (*DomainClassResourceDTO, error) {
   if context == nil {
      return nil, errors.New("No DTO context provided")
   }
   
   if (domainClassResource == nil) {
      return nil, errors.New("Cannot convert nil pointer passed to DTO conversion for table DomainClassResource")
   }
   
   if (slices.Contains(context.TraversedTables, reflect.TypeOf(*domainClassResource).Name())) {
      fmt.Println("Hit circular catch case for table DomainClassResource")
      return nil, nil
   }
   
   childDTOContext := contextProviders.DTOContext{
      DatabaseContext: context.DatabaseContext,
      TraversedTables: append(context.TraversedTables, reflect.TypeOf(*domainClassResource).Name()),
   }
   serviceContext := &contextProviders.ServiceContext{
      DatabaseContext: context.DatabaseContext,
      CurrentUser: nil,
   }
   
   var includedParent__DomainClass *types.DomainClass
   var includedParent__DomainSubClass *types.DomainSubClass
   var includedResourceOwner__User *types.User
   
   var Parent__DomainClassDTO *DomainClassDTO
   var Parent__DomainSubClassDTO *DomainSubClassDTO
   var ResourceOwner__UserDTO *UserDTO
   
   var err error
   
   if (domainClassResource.Parent__DomainClass != nil) {
      includedParent__DomainClass, err = services.GetDomainClassById(serviceContext, contextProviders.ProduceGetByIdArgs[types.DomainClass](domainClassResource.Parent__DomainClass))
      if err != nil {
         return nil, err
      }
      Parent__DomainClassDTO, err = DomainClassToDomainClassDTO(&childDTOContext, includedParent__DomainClass)
      if err != nil {
         return nil, err
      }
   }

   if (domainClassResource.Parent__DomainSubClass != nil) {
      includedParent__DomainSubClass, err = services.GetDomainSubClassById(serviceContext, contextProviders.ProduceGetByIdArgs[types.DomainSubClass](domainClassResource.Parent__DomainSubClass))
      if err != nil {
         return nil, err
      }
      Parent__DomainSubClassDTO, err = DomainSubClassToDomainSubClassDTO(&childDTOContext, includedParent__DomainSubClass)
      if err != nil {
         return nil, err
      }
   }

   if (domainClassResource.ResourceOwner__User != nil) {
      includedResourceOwner__User, err = services.GetUserById(serviceContext, contextProviders.ProduceGetByIdArgs[types.User](domainClassResource.ResourceOwner__User))
      if err != nil {
         return nil, err
      }
      ResourceOwner__UserDTO, err = UserToUserDTO(&childDTOContext, includedResourceOwner__User)
      if err != nil {
         return nil, err
      }
   }

   
   return &DomainClassResourceDTO{
      Id: domainClassResource.Id,
      Attributes: DomainClassResourceDTOAttributes{
         AbbreviatedTitle: domainClassResource.AbbreviatedTitle,
         CreatedAt: domainClassResource.CreatedAt,
         Description: domainClassResource.Description,
         
         IsActive: domainClassResource.IsActive,
         Title: domainClassResource.Title,
         UpdatedAt: domainClassResource.UpdatedAt,
      },
      Relationships: DomainClassResourceDTORelationships{
         ManyToOne: DomainClassResourceDTOManyToOneRelationships {
            Parent__DomainClass: Parent__DomainClassDTO,
            Parent__DomainSubClass: Parent__DomainSubClassDTO,
            ResourceOwner__User: ResourceOwner__UserDTO,
         },
         OneToMany: DomainClassResourceDTOOneToManyRelationships {
         },
      },
   }, nil
}

func DomainClassResourceDTOToDomainClassResource(domainClassResource *DomainClassResourceDTO) *types.DomainClassResource {
   var tableTypeBuffer types.DomainClassResource
   
   tableTypeBuffer.Id = domainClassResource.Id
   tableTypeBuffer.AbbreviatedTitle = domainClassResource.Attributes.AbbreviatedTitle
   tableTypeBuffer.CreatedAt = domainClassResource.Attributes.CreatedAt
   tableTypeBuffer.Description = domainClassResource.Attributes.Description
   
   tableTypeBuffer.IsActive = domainClassResource.Attributes.IsActive
   tableTypeBuffer.Title = domainClassResource.Attributes.Title
   tableTypeBuffer.UpdatedAt = domainClassResource.Attributes.UpdatedAt
   
   if (domainClassResource.Relationships.ManyToOne.Parent__DomainClass != nil) {
      tableTypeBuffer.Parent__DomainClass = domainClassResource.Relationships.ManyToOne.Parent__DomainClass.Id
   }

   if (domainClassResource.Relationships.ManyToOne.Parent__DomainSubClass != nil) {
      tableTypeBuffer.Parent__DomainSubClass = domainClassResource.Relationships.ManyToOne.Parent__DomainSubClass.Id
   }

   if (domainClassResource.Relationships.ManyToOne.ResourceOwner__User != nil) {
      tableTypeBuffer.ResourceOwner__User = domainClassResource.Relationships.ManyToOne.ResourceOwner__User.Id
   }

   return &tableTypeBuffer
}
