//*** CAUTION ***
//This is an autogenerated file produced by regenerateBackend.py.
//Edits made here will not persist after backend regeneration.

package generatedDTOs

import (
   types "AdventureEngineServer/generatedDatabaseTypes"
   
   
   "gorm.io/gorm"
   "reflect"
)

type DomainStaticEffectDTOAttributes struct {
   Description *string
   IsActive *bool
   Title *string
   
}

type DomainStaticEffectDTORelationships struct {
}

type DomainStaticEffectDTO struct {
   Id *float64
   
   Attributes DomainStaticEffectDTOAttributes
   
   Relationships DomainStaticEffectDTORelationships
}

func DomainStaticEffectToDomainStaticEffectDTO(db *gorm.DB, domainStaticEffect *types.DomainStaticEffect, originTable *string) *DomainStaticEffectDTO {
   
   if (originTable != nil && *originTable == reflect.TypeOf(*domainStaticEffect).Name()) {
      print("Hit circular catch case for table DomainStaticEffect\n")
      return nil
   }
   if (originTable == nil) {
      var tableName string = reflect.TypeOf(*domainStaticEffect).Name()
      originTable = &tableName
   }
   
   
   return &DomainStaticEffectDTO{
      Id: domainStaticEffect.Id,
      Attributes: DomainStaticEffectDTOAttributes{
         Description: domainStaticEffect.Description,
         IsActive: domainStaticEffect.IsActive,
         Title: domainStaticEffect.Title,
         
      },
      Relationships: DomainStaticEffectDTORelationships{
      },
   }
}

func DomainStaticEffectDTOToDomainStaticEffect(domainStaticEffect *DomainStaticEffectDTO) types.DomainStaticEffect {
   return types.DomainStaticEffect{
      Id: domainStaticEffect.Id,
      Description: domainStaticEffect.Attributes.Description,
      IsActive: domainStaticEffect.Attributes.IsActive,
      Title: domainStaticEffect.Attributes.Title,
      
   }
}
