//*** CAUTION ***
//This is an autogenerated file produced by regenerateBackend.py.
//Edits made here will not persist after backend regeneration.

package generatedDTOs

import (
   types "AdventureEngineServer/generatedDatabaseTypes"
   
   
   "gorm.io/gorm"
)

type DomainActionDTOAttributes struct {
   Description *string
   IsActive *bool
   Title *string
   UsesAction *bool
   UsesBonusAction *bool
   
}

type DomainActionDTORelationships struct {
}

type DomainActionDTO struct {
   Id *float64
   
   Attributes DomainActionDTOAttributes
   
   Relationships DomainActionDTORelationships
}

func DomainActionToDomainActionDTO(db *gorm.DB, domainAction *types.DomainAction, originTable *string) *DomainActionDTO {
   
   
   
   return &DomainActionDTO{
      Id: domainAction.Id,
      Attributes: DomainActionDTOAttributes{
         Description: domainAction.Description,
         IsActive: domainAction.IsActive,
         Title: domainAction.Title,
         UsesAction: domainAction.UsesAction,
         UsesBonusAction: domainAction.UsesBonusAction,
         
      },
      Relationships: DomainActionDTORelationships{
      },
   }
}

func DomainActionDTOToDomainAction(domainAction *DomainActionDTO) types.DomainAction {
   return types.DomainAction{
      Id: domainAction.Id,
      Description: domainAction.Attributes.Description,
      IsActive: domainAction.Attributes.IsActive,
      Title: domainAction.Attributes.Title,
      UsesAction: domainAction.Attributes.UsesAction,
      UsesBonusAction: domainAction.Attributes.UsesBonusAction,
      
   }
}
