//*** CAUTION ***
//This is an autogenerated file produced by regenerateBackend.py.
//Edits made here will not persist after backend regeneration.

package generatedDTOs

import (
   contextProviders "AdventureEngineServer/contextProviders"
   types "AdventureEngineServer/generatedDatabaseTypes"
   
   services "AdventureEngineServer/generatedServices"
   "errors"
   "fmt"
   "reflect"
   "slices"
)

type DomainGameEventDTOAttributes struct {
   AbbreviatedTitle *string
   CreatedAt *string
   Description *string
   
   IsActive *bool
   Title *string
   Type *string
   UpdatedAt *string
}

type DomainGameEventDTOManyToOneRelationships struct {
   ResourceOwner__User *UserDTO
}

type DomainGameEventDTOOneToManyRelationships struct {
}

type DomainGameEventDTORelationships struct {
   ManyToOne DomainGameEventDTOManyToOneRelationships
   OneToMany DomainGameEventDTOOneToManyRelationships
}

type DomainGameEventDTO struct {
   Id *int
   
   Attributes DomainGameEventDTOAttributes
   
   Relationships DomainGameEventDTORelationships
}

func DomainGameEventToDomainGameEventDTO(context *contextProviders.DTOContext, domainGameEvent *types.DomainGameEvent) (*DomainGameEventDTO, error) {
   if context == nil {
      return nil, errors.New("No DTO context provided")
   }
   
   if (domainGameEvent == nil) {
      return nil, errors.New("Cannot convert nil pointer passed to DTO conversion for table DomainGameEvent")
   }
   
   if (slices.Contains(context.TraversedTables, reflect.TypeOf(*domainGameEvent).Name())) {
      fmt.Println("Hit circular catch case for table DomainGameEvent")
      return nil, nil
   }
   
   childDTOContext := contextProviders.DTOContext{
      DatabaseContext: context.DatabaseContext,
      TraversedTables: append(context.TraversedTables, reflect.TypeOf(*domainGameEvent).Name()),
   }
   serviceContext := &contextProviders.ServiceContext{
      DatabaseContext: context.DatabaseContext,
      CurrentUser: nil,
   }
   
   var includedResourceOwner__User *types.User
   
   var ResourceOwner__UserDTO *UserDTO
   
   var err error
   
   if (domainGameEvent.ResourceOwner__User != nil) {
      includedResourceOwner__User, err = services.GetUserById(serviceContext, contextProviders.ProduceGetByIdArgs[types.User](domainGameEvent.ResourceOwner__User))
      if err != nil {
         return nil, err
      }
      ResourceOwner__UserDTO, err = UserToUserDTO(&childDTOContext, includedResourceOwner__User)
      if err != nil {
         return nil, err
      }
   }

   
   return &DomainGameEventDTO{
      Id: domainGameEvent.Id,
      Attributes: DomainGameEventDTOAttributes{
         AbbreviatedTitle: domainGameEvent.AbbreviatedTitle,
         CreatedAt: domainGameEvent.CreatedAt,
         Description: domainGameEvent.Description,
         
         IsActive: domainGameEvent.IsActive,
         Title: domainGameEvent.Title,
         Type: domainGameEvent.Type,
         UpdatedAt: domainGameEvent.UpdatedAt,
      },
      Relationships: DomainGameEventDTORelationships{
         ManyToOne: DomainGameEventDTOManyToOneRelationships {
            ResourceOwner__User: ResourceOwner__UserDTO,
         },
         OneToMany: DomainGameEventDTOOneToManyRelationships {
         },
      },
   }, nil
}

func DomainGameEventDTOToDomainGameEvent(domainGameEvent *DomainGameEventDTO) *types.DomainGameEvent {
   var tableTypeBuffer types.DomainGameEvent
   
   tableTypeBuffer.Id = domainGameEvent.Id
   tableTypeBuffer.AbbreviatedTitle = domainGameEvent.Attributes.AbbreviatedTitle
   tableTypeBuffer.CreatedAt = domainGameEvent.Attributes.CreatedAt
   tableTypeBuffer.Description = domainGameEvent.Attributes.Description
   
   tableTypeBuffer.IsActive = domainGameEvent.Attributes.IsActive
   tableTypeBuffer.Title = domainGameEvent.Attributes.Title
   tableTypeBuffer.Type = domainGameEvent.Attributes.Type
   tableTypeBuffer.UpdatedAt = domainGameEvent.Attributes.UpdatedAt
   
   if (domainGameEvent.Relationships.ManyToOne.ResourceOwner__User != nil) {
      tableTypeBuffer.ResourceOwner__User = domainGameEvent.Relationships.ManyToOne.ResourceOwner__User.Id
   }

   return &tableTypeBuffer
}
