//*** CAUTION ***
//This is an autogenerated file produced by regenerateBackend.py.
//Edits made here will not persist after backend regeneration.

package generatedDTOs

import (
   types "AdventureEngineServer/generatedDatabaseTypes"
   
   services "AdventureEngineServer/generatedServices"
   "gorm.io/gorm"
   "fmt"
   "reflect"
   "slices"
)

type DomainDamageTypeDTOAttributes struct {
   AbbreviatedTitle *string
   CreatedAt *string
   Description *string
   
   IsActive *bool
   Title *string
   UpdatedAt *string
}

type DomainDamageTypeDTOManyToOneRelationships struct {
   ResourceOwner__User *UserDTO
}

type DomainDamageTypeDTOOneToManyRelationships struct {
}

type DomainDamageTypeDTORelationships struct {
   ManyToOne DomainDamageTypeDTOManyToOneRelationships
   OneToMany DomainDamageTypeDTOOneToManyRelationships
}

type DomainDamageTypeDTO struct {
   Id *int
   
   Attributes DomainDamageTypeDTOAttributes
   
   Relationships DomainDamageTypeDTORelationships
}

func DomainDamageTypeToDomainDamageTypeDTO(db *gorm.DB, domainDamageType *types.DomainDamageType, traversedTables []string) *DomainDamageTypeDTO {
   
   if (domainDamageType == nil) {
      fmt.Println("Nil pointer passed to DTO conversion for table DomainDamageType")
      return nil
   }
   
   if (slices.Contains(traversedTables, reflect.TypeOf(*domainDamageType).Name())) {
      fmt.Println("Hit circular catch case for table DomainDamageType")
      return nil
   }
   
   traversedTables = append(traversedTables, reflect.TypeOf(*domainDamageType).Name())
   
   var includedResourceOwner__User types.User
   
   if (domainDamageType.ResourceOwner__User != nil) {
      if err := services.GetUserById(db, int(*domainDamageType.ResourceOwner__User), &includedResourceOwner__User); err != nil {
         fmt.Println("Error fetching many-to-one table User:")
         fmt.Println(err)
      }
   }

   
   return &DomainDamageTypeDTO{
      Id: domainDamageType.Id,
      Attributes: DomainDamageTypeDTOAttributes{
         AbbreviatedTitle: domainDamageType.AbbreviatedTitle,
         CreatedAt: domainDamageType.CreatedAt,
         Description: domainDamageType.Description,
         
         IsActive: domainDamageType.IsActive,
         Title: domainDamageType.Title,
         UpdatedAt: domainDamageType.UpdatedAt,
      },
      Relationships: DomainDamageTypeDTORelationships{
         ManyToOne: DomainDamageTypeDTOManyToOneRelationships {
            ResourceOwner__User: UserToUserDTO(db, &includedResourceOwner__User, traversedTables),
         },
         OneToMany: DomainDamageTypeDTOOneToManyRelationships {
         },
      },
   }
}

func DomainDamageTypeDTOToDomainDamageType(domainDamageType *DomainDamageTypeDTO) *types.DomainDamageType {
   var tableTypeBuffer types.DomainDamageType
   
   tableTypeBuffer.Id = domainDamageType.Id
   tableTypeBuffer.AbbreviatedTitle = domainDamageType.Attributes.AbbreviatedTitle
   tableTypeBuffer.CreatedAt = domainDamageType.Attributes.CreatedAt
   tableTypeBuffer.Description = domainDamageType.Attributes.Description
   
   tableTypeBuffer.IsActive = domainDamageType.Attributes.IsActive
   tableTypeBuffer.Title = domainDamageType.Attributes.Title
   tableTypeBuffer.UpdatedAt = domainDamageType.Attributes.UpdatedAt
   
   if (domainDamageType.Relationships.ManyToOne.ResourceOwner__User != nil) {
      tableTypeBuffer.ResourceOwner__User = domainDamageType.Relationships.ManyToOne.ResourceOwner__User.Id
   }

   return &tableTypeBuffer
}
