//*** CAUTION ***
//This is an autogenerated file produced by regenerateBackend.py.
//Edits made here will not persist after backend regeneration.

package generatedDTOs

import (
   contextProviders "AdventureEngineServer/contextProviders"
   types "AdventureEngineServer/generatedDatabaseTypes"
   
   services "AdventureEngineServer/generatedServices"
   "errors"
   "fmt"
   "reflect"
   "slices"
)

type EvaluatedConditionalDTOAttributes struct {
   AbbreviatedTitle *string
   CreatedAt *string
   Description *string
   
   IsActive *bool
   Title *string
   UpdatedAt *string
   EvaluatedOnEvent *bool
   EvaluatedStatically *bool
}

type EvaluatedConditionalDTOManyToOneRelationships struct {
   Base__Quantifier *QuantifierDTO
   IsTrue__DomainCondition *DomainConditionDTO
   Modifier__Quantifier *QuantifierDTO
   ResourceOwner__User *UserDTO
}

type EvaluatedConditionalDTOOneToManyRelationships struct {
}

type EvaluatedConditionalDTORelationships struct {
   ManyToOne EvaluatedConditionalDTOManyToOneRelationships
   OneToMany EvaluatedConditionalDTOOneToManyRelationships
}

type EvaluatedConditionalDTO struct {
   Id *int
   
   Attributes EvaluatedConditionalDTOAttributes
   
   Relationships EvaluatedConditionalDTORelationships
}

func EvaluatedConditionalToEvaluatedConditionalDTO(context *contextProviders.DTOContext, evaluatedConditional *types.EvaluatedConditional) (*EvaluatedConditionalDTO, error) {
   if context == nil {
      return nil, errors.New("No DTO context provided")
   }
   
   if (evaluatedConditional == nil) {
      return nil, errors.New("Cannot convert nil pointer passed to DTO conversion for table EvaluatedConditional")
   }
   
   if (slices.Contains(context.TraversedTables, reflect.TypeOf(*evaluatedConditional).Name())) {
      fmt.Println("Hit circular catch case for table EvaluatedConditional")
      return nil, nil
   }
   
   childDTOContext := contextProviders.DTOContext{
      DatabaseContext: context.DatabaseContext,
      TraversedTables: append(context.TraversedTables, reflect.TypeOf(*evaluatedConditional).Name()),
   }
   serviceContext := &contextProviders.ServiceContext{
      DatabaseContext: context.DatabaseContext,
      CurrentUser: nil,
   }
   
   var includedBase__Quantifier *types.Quantifier
   var includedIsTrue__DomainCondition *types.DomainCondition
   var includedModifier__Quantifier *types.Quantifier
   var includedResourceOwner__User *types.User
   
   var Base__QuantifierDTO *QuantifierDTO
   var IsTrue__DomainConditionDTO *DomainConditionDTO
   var Modifier__QuantifierDTO *QuantifierDTO
   var ResourceOwner__UserDTO *UserDTO
   
   var err error
   
   if (evaluatedConditional.Base__Quantifier != nil) {
      includedBase__Quantifier, err = services.GetQuantifierById(serviceContext, contextProviders.ProduceGetByIdArgs[types.Quantifier](evaluatedConditional.Base__Quantifier))
      if err != nil {
         return nil, err
      }
      Base__QuantifierDTO, err = QuantifierToQuantifierDTO(&childDTOContext, includedBase__Quantifier)
      if err != nil {
         return nil, err
      }
   }

   if (evaluatedConditional.IsTrue__DomainCondition != nil) {
      includedIsTrue__DomainCondition, err = services.GetDomainConditionById(serviceContext, contextProviders.ProduceGetByIdArgs[types.DomainCondition](evaluatedConditional.IsTrue__DomainCondition))
      if err != nil {
         return nil, err
      }
      IsTrue__DomainConditionDTO, err = DomainConditionToDomainConditionDTO(&childDTOContext, includedIsTrue__DomainCondition)
      if err != nil {
         return nil, err
      }
   }

   if (evaluatedConditional.Modifier__Quantifier != nil) {
      includedModifier__Quantifier, err = services.GetQuantifierById(serviceContext, contextProviders.ProduceGetByIdArgs[types.Quantifier](evaluatedConditional.Modifier__Quantifier))
      if err != nil {
         return nil, err
      }
      Modifier__QuantifierDTO, err = QuantifierToQuantifierDTO(&childDTOContext, includedModifier__Quantifier)
      if err != nil {
         return nil, err
      }
   }

   if (evaluatedConditional.ResourceOwner__User != nil) {
      includedResourceOwner__User, err = services.GetUserById(serviceContext, contextProviders.ProduceGetByIdArgs[types.User](evaluatedConditional.ResourceOwner__User))
      if err != nil {
         return nil, err
      }
      ResourceOwner__UserDTO, err = UserToUserDTO(&childDTOContext, includedResourceOwner__User)
      if err != nil {
         return nil, err
      }
   }

   
   return &EvaluatedConditionalDTO{
      Id: evaluatedConditional.Id,
      Attributes: EvaluatedConditionalDTOAttributes{
         AbbreviatedTitle: evaluatedConditional.AbbreviatedTitle,
         CreatedAt: evaluatedConditional.CreatedAt,
         Description: evaluatedConditional.Description,
         
         IsActive: evaluatedConditional.IsActive,
         Title: evaluatedConditional.Title,
         UpdatedAt: evaluatedConditional.UpdatedAt,
         EvaluatedOnEvent: evaluatedConditional.EvaluatedOnEvent,
         EvaluatedStatically: evaluatedConditional.EvaluatedStatically,
      },
      Relationships: EvaluatedConditionalDTORelationships{
         ManyToOne: EvaluatedConditionalDTOManyToOneRelationships {
            Base__Quantifier: Base__QuantifierDTO,
            IsTrue__DomainCondition: IsTrue__DomainConditionDTO,
            Modifier__Quantifier: Modifier__QuantifierDTO,
            ResourceOwner__User: ResourceOwner__UserDTO,
         },
         OneToMany: EvaluatedConditionalDTOOneToManyRelationships {
         },
      },
   }, nil
}

func EvaluatedConditionalDTOToEvaluatedConditional(evaluatedConditional *EvaluatedConditionalDTO) *types.EvaluatedConditional {
   var tableTypeBuffer types.EvaluatedConditional
   
   tableTypeBuffer.Id = evaluatedConditional.Id
   tableTypeBuffer.AbbreviatedTitle = evaluatedConditional.Attributes.AbbreviatedTitle
   tableTypeBuffer.CreatedAt = evaluatedConditional.Attributes.CreatedAt
   tableTypeBuffer.Description = evaluatedConditional.Attributes.Description
   
   tableTypeBuffer.IsActive = evaluatedConditional.Attributes.IsActive
   tableTypeBuffer.Title = evaluatedConditional.Attributes.Title
   tableTypeBuffer.UpdatedAt = evaluatedConditional.Attributes.UpdatedAt
   tableTypeBuffer.EvaluatedOnEvent = evaluatedConditional.Attributes.EvaluatedOnEvent
   tableTypeBuffer.EvaluatedStatically = evaluatedConditional.Attributes.EvaluatedStatically
   
   if (evaluatedConditional.Relationships.ManyToOne.Base__Quantifier != nil) {
      tableTypeBuffer.Base__Quantifier = evaluatedConditional.Relationships.ManyToOne.Base__Quantifier.Id
   }

   if (evaluatedConditional.Relationships.ManyToOne.IsTrue__DomainCondition != nil) {
      tableTypeBuffer.IsTrue__DomainCondition = evaluatedConditional.Relationships.ManyToOne.IsTrue__DomainCondition.Id
   }

   if (evaluatedConditional.Relationships.ManyToOne.Modifier__Quantifier != nil) {
      tableTypeBuffer.Modifier__Quantifier = evaluatedConditional.Relationships.ManyToOne.Modifier__Quantifier.Id
   }

   if (evaluatedConditional.Relationships.ManyToOne.ResourceOwner__User != nil) {
      tableTypeBuffer.ResourceOwner__User = evaluatedConditional.Relationships.ManyToOne.ResourceOwner__User.Id
   }

   return &tableTypeBuffer
}
