//*** CAUTION ***
//This is an autogenerated file produced by regenerateBackend.py.
//Edits made here will not persist after backend regeneration.

package generatedDTOs

import (
   contextProviders "AdventureEngineServer/contextProviders"
   types "AdventureEngineServer/generatedDatabaseTypes"
   utils "AdventureEngineServer/utils"
   services "AdventureEngineServer/generatedServices"
   "errors"
   "fmt"
   "reflect"
   "slices"
)

type QuantifierDTOAttributes struct {
   AbbreviatedTitle *string
   AppliesAgainstSource *bool
   AppliesAgainstSourceForTargetsOnly *bool
   AppliesAgainstTargets *bool
   AppliesAgainstTargetsForSourceOnly *bool
   AppliesToSource *bool
   AppliesToTargets *bool
   AutomaticCritical *bool
   AutomaticFailure *bool
   CreatedAt *string
   DeltaPercentage *float64
   DeltaQuantity *float64
   Description *string
   GivesAdvantage *bool
   GivesDisadvantage *bool
   GivesResistance *bool
   HardSetPercentage *float64
   HardSetQuantity *float64
   
   IntoInventory *bool
   IsActive *bool
   LevelMaximumRequirement *float64
   LevelMinimumRequirement *float64
   PreventsApplying *bool
   PreventsReceiving *bool
   QuantityRestoredOnShortRest *float64
   Range *float64
   RefreshOnLongRest *bool
   RefreshOnShortRest *bool
   RemovedOn *bool
   Removes *bool
   ShouldReplace *bool
   TargetMaximum *float64
   TargetMinimum *float64
   Title *string
   UntilLongRest *bool
   UntilShortRest *bool
   UpdatedAt *string
}

type QuantifierDTOManyToOneRelationships struct {
   Parent__DomainAction *DomainActionDTO
   Parent__DomainClass *DomainClassDTO
   Parent__DomainClassTrait *DomainClassTraitDTO
   Parent__DomainCondition *DomainConditionDTO
   Parent__DomainStaticEffect *DomainStaticEffectDTO
   Parent__DomainSubClass *DomainSubClassDTO
   ResourceOwner__User *UserDTO
   Target__DomainAction *DomainActionDTO
   Target__DomainCharacterStat *DomainCharacterStatDTO
   Target__DomainCondition *DomainConditionDTO
   Target__DomainDamageType *DomainDamageTypeDTO
   Target__DomainDiceRollSubType *DomainDiceRollSubTypeDTO
   Target__DomainDiceRollType *DomainDiceRollTypeDTO
   Target__DomainSpell *DomainSpellDTO
   Target__DomainStaticEffect *DomainStaticEffectDTO
   Variant__DomainQuantifierVariant *DomainQuantifierVariantDTO
}

type QuantifierDTOOneToManyRelationships struct {
   Conditions__EvaluatedConditional []*EvaluatedConditionalDTO
   Costs__QuantifierCostSpecifier []*QuantifierCostSpecifierDTO
}

type QuantifierDTORelationships struct {
   ManyToOne QuantifierDTOManyToOneRelationships
   OneToMany QuantifierDTOOneToManyRelationships
}

type QuantifierDTO struct {
   Id *int
   
   Attributes QuantifierDTOAttributes
   
   Relationships QuantifierDTORelationships
}

func QuantifierToQuantifierDTO(context *contextProviders.DTOContext, quantifier *types.Quantifier) (*QuantifierDTO, error) {
   if context == nil {
      return nil, errors.New("No DTO context provided")
   }
   
   if (quantifier == nil) {
      return nil, errors.New("Cannot convert nil pointer passed to DTO conversion for table Quantifier")
   }
   
   if (slices.Contains(context.TraversedTables, reflect.TypeOf(*quantifier).Name())) {
      fmt.Println("Hit circular catch case for table Quantifier")
      return nil, nil
   }
   
   childDTOContext := contextProviders.DTOContext{
      DatabaseContext: context.DatabaseContext,
      TraversedTables: append(context.TraversedTables, reflect.TypeOf(*quantifier).Name()),
   }
   serviceContext := &contextProviders.ServiceContext{
      DatabaseContext: context.DatabaseContext,
      CurrentUser: nil,
   }
   
   var includedParent__DomainAction *types.DomainAction
   var includedParent__DomainClass *types.DomainClass
   var includedParent__DomainClassTrait *types.DomainClassTrait
   var includedParent__DomainCondition *types.DomainCondition
   var includedParent__DomainStaticEffect *types.DomainStaticEffect
   var includedParent__DomainSubClass *types.DomainSubClass
   var includedResourceOwner__User *types.User
   var includedTarget__DomainAction *types.DomainAction
   var includedTarget__DomainCharacterStat *types.DomainCharacterStat
   var includedTarget__DomainCondition *types.DomainCondition
   var includedTarget__DomainDamageType *types.DomainDamageType
   var includedTarget__DomainDiceRollSubType *types.DomainDiceRollSubType
   var includedTarget__DomainDiceRollType *types.DomainDiceRollType
   var includedTarget__DomainSpell *types.DomainSpell
   var includedTarget__DomainStaticEffect *types.DomainStaticEffect
   var includedVariant__DomainQuantifierVariant *types.DomainQuantifierVariant
   var includedConditions__EvaluatedConditionals []types.EvaluatedConditional
   var includedCosts__QuantifierCostSpecifiers []types.QuantifierCostSpecifier
   
   var Parent__DomainActionDTO *DomainActionDTO
   var Parent__DomainClassDTO *DomainClassDTO
   var Parent__DomainClassTraitDTO *DomainClassTraitDTO
   var Parent__DomainConditionDTO *DomainConditionDTO
   var Parent__DomainStaticEffectDTO *DomainStaticEffectDTO
   var Parent__DomainSubClassDTO *DomainSubClassDTO
   var ResourceOwner__UserDTO *UserDTO
   var Target__DomainActionDTO *DomainActionDTO
   var Target__DomainCharacterStatDTO *DomainCharacterStatDTO
   var Target__DomainConditionDTO *DomainConditionDTO
   var Target__DomainDamageTypeDTO *DomainDamageTypeDTO
   var Target__DomainDiceRollSubTypeDTO *DomainDiceRollSubTypeDTO
   var Target__DomainDiceRollTypeDTO *DomainDiceRollTypeDTO
   var Target__DomainSpellDTO *DomainSpellDTO
   var Target__DomainStaticEffectDTO *DomainStaticEffectDTO
   var Variant__DomainQuantifierVariantDTO *DomainQuantifierVariantDTO
   var Conditions__EvaluatedConditionalDTOs []*EvaluatedConditionalDTO
   var Costs__QuantifierCostSpecifierDTOs []*QuantifierCostSpecifierDTO
   
   var err error
   
   if (quantifier.Parent__DomainAction != nil) {
      includedParent__DomainAction, err = services.GetDomainActionById(serviceContext, contextProviders.ProduceGetByIdArgs[types.DomainAction](quantifier.Parent__DomainAction))
      if err != nil {
         return nil, err
      }
      Parent__DomainActionDTO, err = DomainActionToDomainActionDTO(&childDTOContext, includedParent__DomainAction)
      if err != nil {
         return nil, err
      }
   }

   if (quantifier.Parent__DomainClass != nil) {
      includedParent__DomainClass, err = services.GetDomainClassById(serviceContext, contextProviders.ProduceGetByIdArgs[types.DomainClass](quantifier.Parent__DomainClass))
      if err != nil {
         return nil, err
      }
      Parent__DomainClassDTO, err = DomainClassToDomainClassDTO(&childDTOContext, includedParent__DomainClass)
      if err != nil {
         return nil, err
      }
   }

   if (quantifier.Parent__DomainClassTrait != nil) {
      includedParent__DomainClassTrait, err = services.GetDomainClassTraitById(serviceContext, contextProviders.ProduceGetByIdArgs[types.DomainClassTrait](quantifier.Parent__DomainClassTrait))
      if err != nil {
         return nil, err
      }
      Parent__DomainClassTraitDTO, err = DomainClassTraitToDomainClassTraitDTO(&childDTOContext, includedParent__DomainClassTrait)
      if err != nil {
         return nil, err
      }
   }

   if (quantifier.Parent__DomainCondition != nil) {
      includedParent__DomainCondition, err = services.GetDomainConditionById(serviceContext, contextProviders.ProduceGetByIdArgs[types.DomainCondition](quantifier.Parent__DomainCondition))
      if err != nil {
         return nil, err
      }
      Parent__DomainConditionDTO, err = DomainConditionToDomainConditionDTO(&childDTOContext, includedParent__DomainCondition)
      if err != nil {
         return nil, err
      }
   }

   if (quantifier.Parent__DomainStaticEffect != nil) {
      includedParent__DomainStaticEffect, err = services.GetDomainStaticEffectById(serviceContext, contextProviders.ProduceGetByIdArgs[types.DomainStaticEffect](quantifier.Parent__DomainStaticEffect))
      if err != nil {
         return nil, err
      }
      Parent__DomainStaticEffectDTO, err = DomainStaticEffectToDomainStaticEffectDTO(&childDTOContext, includedParent__DomainStaticEffect)
      if err != nil {
         return nil, err
      }
   }

   if (quantifier.Parent__DomainSubClass != nil) {
      includedParent__DomainSubClass, err = services.GetDomainSubClassById(serviceContext, contextProviders.ProduceGetByIdArgs[types.DomainSubClass](quantifier.Parent__DomainSubClass))
      if err != nil {
         return nil, err
      }
      Parent__DomainSubClassDTO, err = DomainSubClassToDomainSubClassDTO(&childDTOContext, includedParent__DomainSubClass)
      if err != nil {
         return nil, err
      }
   }

   if (quantifier.ResourceOwner__User != nil) {
      includedResourceOwner__User, err = services.GetUserById(serviceContext, contextProviders.ProduceGetByIdArgs[types.User](quantifier.ResourceOwner__User))
      if err != nil {
         return nil, err
      }
      ResourceOwner__UserDTO, err = UserToUserDTO(&childDTOContext, includedResourceOwner__User)
      if err != nil {
         return nil, err
      }
   }

   if (quantifier.Target__DomainAction != nil) {
      includedTarget__DomainAction, err = services.GetDomainActionById(serviceContext, contextProviders.ProduceGetByIdArgs[types.DomainAction](quantifier.Target__DomainAction))
      if err != nil {
         return nil, err
      }
      Target__DomainActionDTO, err = DomainActionToDomainActionDTO(&childDTOContext, includedTarget__DomainAction)
      if err != nil {
         return nil, err
      }
   }

   if (quantifier.Target__DomainCharacterStat != nil) {
      includedTarget__DomainCharacterStat, err = services.GetDomainCharacterStatById(serviceContext, contextProviders.ProduceGetByIdArgs[types.DomainCharacterStat](quantifier.Target__DomainCharacterStat))
      if err != nil {
         return nil, err
      }
      Target__DomainCharacterStatDTO, err = DomainCharacterStatToDomainCharacterStatDTO(&childDTOContext, includedTarget__DomainCharacterStat)
      if err != nil {
         return nil, err
      }
   }

   if (quantifier.Target__DomainCondition != nil) {
      includedTarget__DomainCondition, err = services.GetDomainConditionById(serviceContext, contextProviders.ProduceGetByIdArgs[types.DomainCondition](quantifier.Target__DomainCondition))
      if err != nil {
         return nil, err
      }
      Target__DomainConditionDTO, err = DomainConditionToDomainConditionDTO(&childDTOContext, includedTarget__DomainCondition)
      if err != nil {
         return nil, err
      }
   }

   if (quantifier.Target__DomainDamageType != nil) {
      includedTarget__DomainDamageType, err = services.GetDomainDamageTypeById(serviceContext, contextProviders.ProduceGetByIdArgs[types.DomainDamageType](quantifier.Target__DomainDamageType))
      if err != nil {
         return nil, err
      }
      Target__DomainDamageTypeDTO, err = DomainDamageTypeToDomainDamageTypeDTO(&childDTOContext, includedTarget__DomainDamageType)
      if err != nil {
         return nil, err
      }
   }

   if (quantifier.Target__DomainDiceRollSubType != nil) {
      includedTarget__DomainDiceRollSubType, err = services.GetDomainDiceRollSubTypeById(serviceContext, contextProviders.ProduceGetByIdArgs[types.DomainDiceRollSubType](quantifier.Target__DomainDiceRollSubType))
      if err != nil {
         return nil, err
      }
      Target__DomainDiceRollSubTypeDTO, err = DomainDiceRollSubTypeToDomainDiceRollSubTypeDTO(&childDTOContext, includedTarget__DomainDiceRollSubType)
      if err != nil {
         return nil, err
      }
   }

   if (quantifier.Target__DomainDiceRollType != nil) {
      includedTarget__DomainDiceRollType, err = services.GetDomainDiceRollTypeById(serviceContext, contextProviders.ProduceGetByIdArgs[types.DomainDiceRollType](quantifier.Target__DomainDiceRollType))
      if err != nil {
         return nil, err
      }
      Target__DomainDiceRollTypeDTO, err = DomainDiceRollTypeToDomainDiceRollTypeDTO(&childDTOContext, includedTarget__DomainDiceRollType)
      if err != nil {
         return nil, err
      }
   }

   if (quantifier.Target__DomainSpell != nil) {
      includedTarget__DomainSpell, err = services.GetDomainSpellById(serviceContext, contextProviders.ProduceGetByIdArgs[types.DomainSpell](quantifier.Target__DomainSpell))
      if err != nil {
         return nil, err
      }
      Target__DomainSpellDTO, err = DomainSpellToDomainSpellDTO(&childDTOContext, includedTarget__DomainSpell)
      if err != nil {
         return nil, err
      }
   }

   if (quantifier.Target__DomainStaticEffect != nil) {
      includedTarget__DomainStaticEffect, err = services.GetDomainStaticEffectById(serviceContext, contextProviders.ProduceGetByIdArgs[types.DomainStaticEffect](quantifier.Target__DomainStaticEffect))
      if err != nil {
         return nil, err
      }
      Target__DomainStaticEffectDTO, err = DomainStaticEffectToDomainStaticEffectDTO(&childDTOContext, includedTarget__DomainStaticEffect)
      if err != nil {
         return nil, err
      }
   }

   if (quantifier.Variant__DomainQuantifierVariant != nil) {
      includedVariant__DomainQuantifierVariant, err = services.GetDomainQuantifierVariantById(serviceContext, contextProviders.ProduceGetByIdArgs[types.DomainQuantifierVariant](quantifier.Variant__DomainQuantifierVariant))
      if err != nil {
         return nil, err
      }
      Variant__DomainQuantifierVariantDTO, err = DomainQuantifierVariantToDomainQuantifierVariantDTO(&childDTOContext, includedVariant__DomainQuantifierVariant)
      if err != nil {
         return nil, err
      }
   }

   if (slices.Contains(context.TraversedTables, reflect.TypeOf(includedConditions__EvaluatedConditionals).Elem().Name())) {
      includedConditions__EvaluatedConditionals = []types.EvaluatedConditional{}
      fmt.Println("Hit circular catch case for table EvaluatedConditional")
   } else {
      includedConditions__EvaluatedConditionals, err = services.GetEvaluatedConditionals(serviceContext, contextProviders.ProduceGetArgs[types.EvaluatedConditional]("Base__Quantifier", quantifier.Id))
      if err != nil {
         return nil, err
      }
      Conditions__EvaluatedConditionalDTOs, err = utils.ErrorCompatibleMap(includedConditions__EvaluatedConditionals, func(relationshipElement types.EvaluatedConditional) (*EvaluatedConditionalDTO, error) { return EvaluatedConditionalToEvaluatedConditionalDTO(&childDTOContext, &relationshipElement) })
      if err != nil {
         return nil, err
      }
   }

   if (slices.Contains(context.TraversedTables, reflect.TypeOf(includedCosts__QuantifierCostSpecifiers).Elem().Name())) {
      includedCosts__QuantifierCostSpecifiers = []types.QuantifierCostSpecifier{}
      fmt.Println("Hit circular catch case for table QuantifierCostSpecifier")
   } else {
      includedCosts__QuantifierCostSpecifiers, err = services.GetQuantifierCostSpecifiers(serviceContext, contextProviders.ProduceGetArgs[types.QuantifierCostSpecifier]("Quantifier__Quantifier", quantifier.Id))
      if err != nil {
         return nil, err
      }
      Costs__QuantifierCostSpecifierDTOs, err = utils.ErrorCompatibleMap(includedCosts__QuantifierCostSpecifiers, func(relationshipElement types.QuantifierCostSpecifier) (*QuantifierCostSpecifierDTO, error) { return QuantifierCostSpecifierToQuantifierCostSpecifierDTO(&childDTOContext, &relationshipElement) })
      if err != nil {
         return nil, err
      }
   }

   
   return &QuantifierDTO{
      Id: quantifier.Id,
      Attributes: QuantifierDTOAttributes{
         AbbreviatedTitle: quantifier.AbbreviatedTitle,
         AppliesAgainstSource: quantifier.AppliesAgainstSource,
         AppliesAgainstSourceForTargetsOnly: quantifier.AppliesAgainstSourceForTargetsOnly,
         AppliesAgainstTargets: quantifier.AppliesAgainstTargets,
         AppliesAgainstTargetsForSourceOnly: quantifier.AppliesAgainstTargetsForSourceOnly,
         AppliesToSource: quantifier.AppliesToSource,
         AppliesToTargets: quantifier.AppliesToTargets,
         AutomaticCritical: quantifier.AutomaticCritical,
         AutomaticFailure: quantifier.AutomaticFailure,
         CreatedAt: quantifier.CreatedAt,
         DeltaPercentage: quantifier.DeltaPercentage,
         DeltaQuantity: quantifier.DeltaQuantity,
         Description: quantifier.Description,
         GivesAdvantage: quantifier.GivesAdvantage,
         GivesDisadvantage: quantifier.GivesDisadvantage,
         GivesResistance: quantifier.GivesResistance,
         HardSetPercentage: quantifier.HardSetPercentage,
         HardSetQuantity: quantifier.HardSetQuantity,
         
         IntoInventory: quantifier.IntoInventory,
         IsActive: quantifier.IsActive,
         LevelMaximumRequirement: quantifier.LevelMaximumRequirement,
         LevelMinimumRequirement: quantifier.LevelMinimumRequirement,
         PreventsApplying: quantifier.PreventsApplying,
         PreventsReceiving: quantifier.PreventsReceiving,
         QuantityRestoredOnShortRest: quantifier.QuantityRestoredOnShortRest,
         Range: quantifier.Range,
         RefreshOnLongRest: quantifier.RefreshOnLongRest,
         RefreshOnShortRest: quantifier.RefreshOnShortRest,
         RemovedOn: quantifier.RemovedOn,
         Removes: quantifier.Removes,
         ShouldReplace: quantifier.ShouldReplace,
         TargetMaximum: quantifier.TargetMaximum,
         TargetMinimum: quantifier.TargetMinimum,
         Title: quantifier.Title,
         UntilLongRest: quantifier.UntilLongRest,
         UntilShortRest: quantifier.UntilShortRest,
         UpdatedAt: quantifier.UpdatedAt,
      },
      Relationships: QuantifierDTORelationships{
         ManyToOne: QuantifierDTOManyToOneRelationships {
            Parent__DomainAction: Parent__DomainActionDTO,
            Parent__DomainClass: Parent__DomainClassDTO,
            Parent__DomainClassTrait: Parent__DomainClassTraitDTO,
            Parent__DomainCondition: Parent__DomainConditionDTO,
            Parent__DomainStaticEffect: Parent__DomainStaticEffectDTO,
            Parent__DomainSubClass: Parent__DomainSubClassDTO,
            ResourceOwner__User: ResourceOwner__UserDTO,
            Target__DomainAction: Target__DomainActionDTO,
            Target__DomainCharacterStat: Target__DomainCharacterStatDTO,
            Target__DomainCondition: Target__DomainConditionDTO,
            Target__DomainDamageType: Target__DomainDamageTypeDTO,
            Target__DomainDiceRollSubType: Target__DomainDiceRollSubTypeDTO,
            Target__DomainDiceRollType: Target__DomainDiceRollTypeDTO,
            Target__DomainSpell: Target__DomainSpellDTO,
            Target__DomainStaticEffect: Target__DomainStaticEffectDTO,
            Variant__DomainQuantifierVariant: Variant__DomainQuantifierVariantDTO,
         },
         OneToMany: QuantifierDTOOneToManyRelationships {
            Conditions__EvaluatedConditional: Conditions__EvaluatedConditionalDTOs,
            Costs__QuantifierCostSpecifier: Costs__QuantifierCostSpecifierDTOs,
         },
      },
   }, nil
}

func QuantifierDTOToQuantifier(quantifier *QuantifierDTO) *types.Quantifier {
   var tableTypeBuffer types.Quantifier
   
   tableTypeBuffer.Id = quantifier.Id
   tableTypeBuffer.AbbreviatedTitle = quantifier.Attributes.AbbreviatedTitle
   tableTypeBuffer.AppliesAgainstSource = quantifier.Attributes.AppliesAgainstSource
   tableTypeBuffer.AppliesAgainstSourceForTargetsOnly = quantifier.Attributes.AppliesAgainstSourceForTargetsOnly
   tableTypeBuffer.AppliesAgainstTargets = quantifier.Attributes.AppliesAgainstTargets
   tableTypeBuffer.AppliesAgainstTargetsForSourceOnly = quantifier.Attributes.AppliesAgainstTargetsForSourceOnly
   tableTypeBuffer.AppliesToSource = quantifier.Attributes.AppliesToSource
   tableTypeBuffer.AppliesToTargets = quantifier.Attributes.AppliesToTargets
   tableTypeBuffer.AutomaticCritical = quantifier.Attributes.AutomaticCritical
   tableTypeBuffer.AutomaticFailure = quantifier.Attributes.AutomaticFailure
   tableTypeBuffer.CreatedAt = quantifier.Attributes.CreatedAt
   tableTypeBuffer.DeltaPercentage = quantifier.Attributes.DeltaPercentage
   tableTypeBuffer.DeltaQuantity = quantifier.Attributes.DeltaQuantity
   tableTypeBuffer.Description = quantifier.Attributes.Description
   tableTypeBuffer.GivesAdvantage = quantifier.Attributes.GivesAdvantage
   tableTypeBuffer.GivesDisadvantage = quantifier.Attributes.GivesDisadvantage
   tableTypeBuffer.GivesResistance = quantifier.Attributes.GivesResistance
   tableTypeBuffer.HardSetPercentage = quantifier.Attributes.HardSetPercentage
   tableTypeBuffer.HardSetQuantity = quantifier.Attributes.HardSetQuantity
   
   tableTypeBuffer.IntoInventory = quantifier.Attributes.IntoInventory
   tableTypeBuffer.IsActive = quantifier.Attributes.IsActive
   tableTypeBuffer.LevelMaximumRequirement = quantifier.Attributes.LevelMaximumRequirement
   tableTypeBuffer.LevelMinimumRequirement = quantifier.Attributes.LevelMinimumRequirement
   tableTypeBuffer.PreventsApplying = quantifier.Attributes.PreventsApplying
   tableTypeBuffer.PreventsReceiving = quantifier.Attributes.PreventsReceiving
   tableTypeBuffer.QuantityRestoredOnShortRest = quantifier.Attributes.QuantityRestoredOnShortRest
   tableTypeBuffer.Range = quantifier.Attributes.Range
   tableTypeBuffer.RefreshOnLongRest = quantifier.Attributes.RefreshOnLongRest
   tableTypeBuffer.RefreshOnShortRest = quantifier.Attributes.RefreshOnShortRest
   tableTypeBuffer.RemovedOn = quantifier.Attributes.RemovedOn
   tableTypeBuffer.Removes = quantifier.Attributes.Removes
   tableTypeBuffer.ShouldReplace = quantifier.Attributes.ShouldReplace
   tableTypeBuffer.TargetMaximum = quantifier.Attributes.TargetMaximum
   tableTypeBuffer.TargetMinimum = quantifier.Attributes.TargetMinimum
   tableTypeBuffer.Title = quantifier.Attributes.Title
   tableTypeBuffer.UntilLongRest = quantifier.Attributes.UntilLongRest
   tableTypeBuffer.UntilShortRest = quantifier.Attributes.UntilShortRest
   tableTypeBuffer.UpdatedAt = quantifier.Attributes.UpdatedAt
   
   if (quantifier.Relationships.ManyToOne.Parent__DomainAction != nil) {
      tableTypeBuffer.Parent__DomainAction = quantifier.Relationships.ManyToOne.Parent__DomainAction.Id
   }

   if (quantifier.Relationships.ManyToOne.Parent__DomainClass != nil) {
      tableTypeBuffer.Parent__DomainClass = quantifier.Relationships.ManyToOne.Parent__DomainClass.Id
   }

   if (quantifier.Relationships.ManyToOne.Parent__DomainClassTrait != nil) {
      tableTypeBuffer.Parent__DomainClassTrait = quantifier.Relationships.ManyToOne.Parent__DomainClassTrait.Id
   }

   if (quantifier.Relationships.ManyToOne.Parent__DomainCondition != nil) {
      tableTypeBuffer.Parent__DomainCondition = quantifier.Relationships.ManyToOne.Parent__DomainCondition.Id
   }

   if (quantifier.Relationships.ManyToOne.Parent__DomainStaticEffect != nil) {
      tableTypeBuffer.Parent__DomainStaticEffect = quantifier.Relationships.ManyToOne.Parent__DomainStaticEffect.Id
   }

   if (quantifier.Relationships.ManyToOne.Parent__DomainSubClass != nil) {
      tableTypeBuffer.Parent__DomainSubClass = quantifier.Relationships.ManyToOne.Parent__DomainSubClass.Id
   }

   if (quantifier.Relationships.ManyToOne.ResourceOwner__User != nil) {
      tableTypeBuffer.ResourceOwner__User = quantifier.Relationships.ManyToOne.ResourceOwner__User.Id
   }

   if (quantifier.Relationships.ManyToOne.Target__DomainAction != nil) {
      tableTypeBuffer.Target__DomainAction = quantifier.Relationships.ManyToOne.Target__DomainAction.Id
   }

   if (quantifier.Relationships.ManyToOne.Target__DomainCharacterStat != nil) {
      tableTypeBuffer.Target__DomainCharacterStat = quantifier.Relationships.ManyToOne.Target__DomainCharacterStat.Id
   }

   if (quantifier.Relationships.ManyToOne.Target__DomainCondition != nil) {
      tableTypeBuffer.Target__DomainCondition = quantifier.Relationships.ManyToOne.Target__DomainCondition.Id
   }

   if (quantifier.Relationships.ManyToOne.Target__DomainDamageType != nil) {
      tableTypeBuffer.Target__DomainDamageType = quantifier.Relationships.ManyToOne.Target__DomainDamageType.Id
   }

   if (quantifier.Relationships.ManyToOne.Target__DomainDiceRollSubType != nil) {
      tableTypeBuffer.Target__DomainDiceRollSubType = quantifier.Relationships.ManyToOne.Target__DomainDiceRollSubType.Id
   }

   if (quantifier.Relationships.ManyToOne.Target__DomainDiceRollType != nil) {
      tableTypeBuffer.Target__DomainDiceRollType = quantifier.Relationships.ManyToOne.Target__DomainDiceRollType.Id
   }

   if (quantifier.Relationships.ManyToOne.Target__DomainSpell != nil) {
      tableTypeBuffer.Target__DomainSpell = quantifier.Relationships.ManyToOne.Target__DomainSpell.Id
   }

   if (quantifier.Relationships.ManyToOne.Target__DomainStaticEffect != nil) {
      tableTypeBuffer.Target__DomainStaticEffect = quantifier.Relationships.ManyToOne.Target__DomainStaticEffect.Id
   }

   if (quantifier.Relationships.ManyToOne.Variant__DomainQuantifierVariant != nil) {
      tableTypeBuffer.Variant__DomainQuantifierVariant = quantifier.Relationships.ManyToOne.Variant__DomainQuantifierVariant.Id
   }

   return &tableTypeBuffer
}
