//*** CAUTION ***
//This is an autogenerated file produced by regenerateBackend.py.
//Edits made here will not persist after backend regeneration.

package generatedDTOs

import (
   contextProviders "AdventureEngineServer/contextProviders"
   types "AdventureEngineServer/generatedDatabaseTypes"
   utils "AdventureEngineServer/utils"
   services "AdventureEngineServer/generatedServices"
   "errors"
   "fmt"
   "reflect"
   "slices"
)

type UserDTOAttributes struct {
   AbbreviatedTitle *string
   CreatedAt *string
   Description *string
   
   IsActive *bool
   Password *string
   Title *string
   UpdatedAt *string
   Username *string
}

type UserDTOManyToOneRelationships struct {
   ResourceOwner__User *UserDTO
}

type UserDTOOneToManyRelationships struct {
   Roles__UserRoleInstance []*UserRoleInstanceDTO
}

type UserDTORelationships struct {
   ManyToOne UserDTOManyToOneRelationships
   OneToMany UserDTOOneToManyRelationships
}

type UserDTO struct {
   Id *int
   
   Attributes UserDTOAttributes
   
   Relationships UserDTORelationships
}

func UserToUserDTO(context *contextProviders.DTOContext, user *types.User) (*UserDTO, error) {
   if context == nil {
      return nil, errors.New("No DTO context provided")
   }
   
   if (user == nil) {
      return nil, errors.New("Cannot convert nil pointer passed to DTO conversion for table User")
   }
   
   if (slices.Contains(context.TraversedTables, reflect.TypeOf(*user).Name())) {
      fmt.Println("Hit circular catch case for table User")
      return nil, nil
   }
   
   childDTOContext := contextProviders.DTOContext{
      DatabaseContext: context.DatabaseContext,
      TraversedTables: append(context.TraversedTables, reflect.TypeOf(*user).Name()),
   }
   serviceContext := &contextProviders.ServiceContext{
      DatabaseContext: context.DatabaseContext,
      CurrentUser: nil,
   }
   
   var includedResourceOwner__User *types.User
   var includedRoles__UserRoleInstances []types.UserRoleInstance
   
   var ResourceOwner__UserDTO *UserDTO
   var Roles__UserRoleInstanceDTOs []*UserRoleInstanceDTO
   
   var err error
   
   if (user.ResourceOwner__User != nil) {
      includedResourceOwner__User, err = services.GetUserById(serviceContext, contextProviders.ProduceGetByIdArgs[types.User](user.ResourceOwner__User))
      if err != nil {
         return nil, err
      }
      ResourceOwner__UserDTO, err = UserToUserDTO(&childDTOContext, includedResourceOwner__User)
      if err != nil {
         return nil, err
      }
   }

   if (slices.Contains(context.TraversedTables, reflect.TypeOf(includedRoles__UserRoleInstances).Elem().Name())) {
      includedRoles__UserRoleInstances = []types.UserRoleInstance{}
      fmt.Println("Hit circular catch case for table UserRoleInstance")
   } else {
      includedRoles__UserRoleInstances, err = services.GetUserRoleInstances(serviceContext, contextProviders.ProduceGetArgs[types.UserRoleInstance]("Roles__UserRoleInstance", user.Id))
      if err != nil {
         return nil, err
      }
      Roles__UserRoleInstanceDTOs, err = utils.ErrorCompatibleMap(includedRoles__UserRoleInstances, func(relationshipElement types.UserRoleInstance) (*UserRoleInstanceDTO, error) { return UserRoleInstanceToUserRoleInstanceDTO(&childDTOContext, &relationshipElement) })
      if err != nil {
         return nil, err
      }
   }

   
   return &UserDTO{
      Id: user.Id,
      Attributes: UserDTOAttributes{
         AbbreviatedTitle: user.AbbreviatedTitle,
         CreatedAt: user.CreatedAt,
         Description: user.Description,
         
         IsActive: user.IsActive,
         Password: nil,
         Title: user.Title,
         UpdatedAt: user.UpdatedAt,
         Username: user.Username,
      },
      Relationships: UserDTORelationships{
         ManyToOne: UserDTOManyToOneRelationships {
            ResourceOwner__User: ResourceOwner__UserDTO,
         },
         OneToMany: UserDTOOneToManyRelationships {
            Roles__UserRoleInstance: Roles__UserRoleInstanceDTOs,
         },
      },
   }, nil
}

func UserDTOToUser(user *UserDTO) *types.User {
   var tableTypeBuffer types.User
   
   tableTypeBuffer.Id = user.Id
   tableTypeBuffer.AbbreviatedTitle = user.Attributes.AbbreviatedTitle
   tableTypeBuffer.CreatedAt = user.Attributes.CreatedAt
   tableTypeBuffer.Description = user.Attributes.Description
   
   tableTypeBuffer.IsActive = user.Attributes.IsActive
   tableTypeBuffer.Password = user.Attributes.Password
   tableTypeBuffer.Title = user.Attributes.Title
   tableTypeBuffer.UpdatedAt = user.Attributes.UpdatedAt
   tableTypeBuffer.Username = user.Attributes.Username
   
   if (user.Relationships.ManyToOne.ResourceOwner__User != nil) {
      tableTypeBuffer.ResourceOwner__User = user.Relationships.ManyToOne.ResourceOwner__User.Id
   }

   return &tableTypeBuffer
}
