//*** CAUTION ***
//This is an autogenerated file produced by regenerateBackend.py.
//Edits made here will not persist after backend regeneration.

package generatedControllers
import (
   "github.com/gin-gonic/gin"
   "gorm.io/gorm"
   "strconv"
   "net/http"
   services "AdventureEngineServer/generatedServices"
   types "AdventureEngineServer/generatedDatabaseTypes"
   dtos "AdventureEngineServer/generatedDTOs"
)

func GetCampaigns(ctx *gin.Context, db *gorm.DB) {
   var serviceBuffer []types.Campaign
   err := services.GetCampaigns(db, &serviceBuffer)
   if err != nil {
      ctx.IndentedJSON(http.StatusInternalServerError, err.Error())
      return
   }
   
   var returnBuffer []dtos.CampaignDTO
   for _, dbTypeInstance := range serviceBuffer {
      pointerToDTO := dtos.CampaignToCampaignDTO(db, &dbTypeInstance, nil)
      if (pointerToDTO != nil) {
         returnBuffer = append(returnBuffer, *pointerToDTO)
      }
   }
   ctx.IndentedJSON(http.StatusOK, returnBuffer)
}

func GetCampaignById(ctx *gin.Context, db *gorm.DB) {
   id := ctx.Param("id")
   idNum, err := strconv.Atoi(id)
   if err != nil {
      ctx.IndentedJSON(http.StatusInternalServerError, err.Error())
      return
   }
   var serviceBuffer types.Campaign
   err = services.GetCampaignById(db, idNum, &serviceBuffer)
   if err != nil {
      ctx.IndentedJSON(http.StatusInternalServerError, err.Error())
      return
   }
   
   returnBuffer := dtos.CampaignToCampaignDTO(db, &serviceBuffer, nil)
   ctx.IndentedJSON(http.StatusOK, returnBuffer)
}

func SaveCampaign(ctx *gin.Context, db *gorm.DB) {
   var serviceBuffer types.Campaign
   err := services.SaveCampaign(db, &serviceBuffer)
   if err != nil {
      ctx.IndentedJSON(http.StatusInternalServerError, err.Error())
      return
   }
   
   returnBuffer := dtos.CampaignToCampaignDTO(db, &serviceBuffer, nil)
   ctx.IndentedJSON(http.StatusOK, returnBuffer)
}
