//*** CAUTION ***
//This is an autogenerated file produced by regenerateBackend.py.
//Edits made here will not persist after backend regeneration.

package generatedControllers
import (
   "github.com/gin-gonic/gin"
   "gorm.io/gorm"
   "strconv"
   "net/http"
   services "AdventureEngineServer/generatedServices"
   types "AdventureEngineServer/generatedDatabaseTypes"
   dtos "AdventureEngineServer/generatedDTOs"
)

func GetCharacters(ctx *gin.Context, db *gorm.DB) {
   var serviceBuffer []types.Character
   err := services.GetCharacters(db, &serviceBuffer)
   if err != nil {
      ctx.IndentedJSON(http.StatusInternalServerError, err.Error())
      return
   }
   
   var returnBuffer []dtos.CharacterDTO
   tableName := "Character"
   for _, dbTypeInstance := range serviceBuffer {
      pointerToDTO := dtos.CharacterToCharacterDTO(db, &dbTypeInstance, &tableName)
      if (pointerToDTO != nil) {
         returnBuffer = append(returnBuffer, *pointerToDTO)
      }
   }
   ctx.IndentedJSON(http.StatusOK, returnBuffer)
}

func GetCharacterById(ctx *gin.Context, db *gorm.DB) {
   id := ctx.Param("id")
   idNum, err := strconv.Atoi(id)
   if err != nil {
      ctx.IndentedJSON(http.StatusInternalServerError, err.Error())
      return
   }
   var serviceBuffer types.Character
   err = services.GetCharacterById(db, idNum, &serviceBuffer)
   if err != nil {
      ctx.IndentedJSON(http.StatusInternalServerError, err.Error())
      return
   }
   
   tableName := "Character"
   returnBuffer := dtos.CharacterToCharacterDTO(db, &serviceBuffer, &tableName)
   ctx.IndentedJSON(http.StatusOK, returnBuffer)
}

func SaveCharacter(ctx *gin.Context, db *gorm.DB) {
   var serviceBuffer types.Character
   err := services.SaveCharacter(db, &serviceBuffer)
   if err != nil {
      ctx.IndentedJSON(http.StatusInternalServerError, err.Error())
      return
   }
   
   tableName := "Character"
   returnBuffer := dtos.CharacterToCharacterDTO(db, &serviceBuffer, &tableName)
   ctx.IndentedJSON(http.StatusOK, returnBuffer)
}
