//*** CAUTION ***
//This is an autogenerated file produced by regenerateBackend.py.
//Edits made here will not persist after backend regeneration.

package generatedcontrollers
import (
   "github.com/gin-gonic/gin"
   "gorm.io/gorm"
   "net/http"
   services "AdventureEngineServer/generatedServices"
   types "AdventureEngineServer/generatedTypes"
)

func GetCharacters(ctx *gin.Context, db *gorm.DB) {
   var returnBuffer []types.CharacterJson
   err := services.GetCharacters(db, &returnBuffer)
   if err != nil {
      ctx.IndentedJSON(http.StatusInternalServerError, err.Error())
      return
   }
   ctx.IndentedJSON(http.StatusOK, returnBuffer)
}
