//*** CAUTION ***
//This is an autogenerated file produced by regenerateBackend.py.
//Edits made here will not persist after backend regeneration.

package generatedControllers
import (
   "github.com/gin-gonic/gin"
   "gorm.io/gorm"
   "strconv"
   "net/http"
   services "AdventureEngineServer/generatedServices"
   types "AdventureEngineServer/generatedDatabaseTypes"
   dtos "AdventureEngineServer/generatedDTOs"
)

func GetClassSaves(ctx *gin.Context, db *gorm.DB) {
   var serviceBuffer []types.ClassSave
   err := services.GetClassSaves(db, &serviceBuffer)
   if err != nil {
      ctx.IndentedJSON(http.StatusInternalServerError, err.Error())
      return
   }
   
   var returnBuffer []dtos.ClassSaveDTO
   for _, dbTypeInstance := range serviceBuffer {
      pointerToDTO := dtos.ClassSaveToClassSaveDTO(db, &dbTypeInstance, []string{})
      if (pointerToDTO != nil) {
         returnBuffer = append(returnBuffer, *pointerToDTO)
      }
   }
   ctx.IndentedJSON(http.StatusOK, returnBuffer)
}

func GetClassSaveById(ctx *gin.Context, db *gorm.DB) {
   id := ctx.Param("id")
   idNum, err := strconv.Atoi(id)
   if err != nil {
      ctx.IndentedJSON(http.StatusInternalServerError, err.Error())
      return
   }
   var serviceBuffer types.ClassSave
   err = services.GetClassSaveById(db, idNum, &serviceBuffer)
   if err != nil {
      ctx.IndentedJSON(http.StatusInternalServerError, err.Error())
      return
   }
   
   returnBuffer := dtos.ClassSaveToClassSaveDTO(db, &serviceBuffer, []string{})
   ctx.IndentedJSON(http.StatusOK, returnBuffer)
}

func SaveClassSave(ctx *gin.Context, db *gorm.DB) {
   var serviceBuffer types.ClassSave
   err := services.SaveClassSave(db, &serviceBuffer)
   if err != nil {
      ctx.IndentedJSON(http.StatusInternalServerError, err.Error())
      return
   }
   
   returnBuffer := dtos.ClassSaveToClassSaveDTO(db, &serviceBuffer, []string{})
   ctx.IndentedJSON(http.StatusOK, returnBuffer)
}
