//*** CAUTION ***
//This is an autogenerated file produced by regenerateBackend.py.
//Edits made here will not persist after backend regeneration.

package generatedControllers
import (
   "github.com/gin-gonic/gin"
   "github.com/gin-gonic/gin/binding"
   "gorm.io/gorm"
   "strconv"
   "net/http"
   services "AdventureEngineServer/generatedServices"
   types "AdventureEngineServer/generatedDatabaseTypes"
   dtos "AdventureEngineServer/generatedDTOs"
   utils "AdventureEngineServer/utils"
)

func GetClassPrimaryAbilitys(ctx *gin.Context, db *gorm.DB) {
   var serviceBuffer []types.ClassPrimaryAbility
   err := services.GetClassPrimaryAbilitys(db, &serviceBuffer)
   if err != nil {
      ctx.IndentedJSON(http.StatusInternalServerError, err.Error())
      return
   }
   
   var returnBuffer []dtos.ClassPrimaryAbilityDTO
   for _, dbTypeInstance := range serviceBuffer {
      pointerToDTO := dtos.ClassPrimaryAbilityToClassPrimaryAbilityDTO(db, &dbTypeInstance, []string{})
      if (pointerToDTO != nil) {
         returnBuffer = append(returnBuffer, *pointerToDTO)
      }
   }
   ctx.IndentedJSON(http.StatusOK, returnBuffer)
}

func GetClassPrimaryAbilityById(ctx *gin.Context, db *gorm.DB) {
   id := ctx.Param("id")
   idNum, err := strconv.Atoi(id)
   if err != nil {
      ctx.IndentedJSON(http.StatusInternalServerError, err.Error())
      return
   }
   var serviceBuffer types.ClassPrimaryAbility
   err = services.GetClassPrimaryAbilityById(db, idNum, &serviceBuffer)
   if err != nil {
      ctx.IndentedJSON(http.StatusInternalServerError, err.Error())
      return
   }
   
   returnBuffer := dtos.ClassPrimaryAbilityToClassPrimaryAbilityDTO(db, &serviceBuffer, []string{})
   ctx.IndentedJSON(http.StatusOK, returnBuffer)
}

func SaveClassPrimaryAbility(ctx *gin.Context, db *gorm.DB) {
   //Weirdness with unmarshalling, cannot unmarshal into a nil pointer, there must be some pre-initialization somewhere along the line
   var DTOBuffer *dtos.ClassPrimaryAbilityDTO = &dtos.ClassPrimaryAbilityDTO{}
   var batchDTOBuffer []*dtos.ClassPrimaryAbilityDTO
   var serviceBuffer []*types.ClassPrimaryAbility
   
   //If neither a single item nor a collection can be bound to JSON, fail early
   //ShouldBindBodyWith is used instead of ShouldBindJSON since the latter prevents multiple bind attempts
   if err := ctx.ShouldBindBodyWith(DTOBuffer, binding.JSON); err == nil {
      
      serviceBuffer = []*types.ClassPrimaryAbility{dtos.ClassPrimaryAbilityDTOToClassPrimaryAbility(DTOBuffer)}
      if err := services.SaveClassPrimaryAbility(db, serviceBuffer); err != nil {
         ctx.IndentedJSON(http.StatusInternalServerError, err.Error())
         return
      }
      
      returnBuffer := dtos.ClassPrimaryAbilityToClassPrimaryAbilityDTO(db, serviceBuffer[0], []string{})
      
      ctx.IndentedJSON(http.StatusOK, returnBuffer)
      return
      
   } else if err := ctx.ShouldBindBodyWith(&batchDTOBuffer, binding.JSON); err == nil {
      
      serviceBuffer = utils.Map(batchDTOBuffer, func(dto *dtos.ClassPrimaryAbilityDTO) *types.ClassPrimaryAbility { return dtos.ClassPrimaryAbilityDTOToClassPrimaryAbility(dto) })
      if err := services.SaveClassPrimaryAbility(db, serviceBuffer); err != nil {
         ctx.IndentedJSON(http.StatusInternalServerError, err.Error())
         return
      }
      
      returnBuffer := utils.Map(serviceBuffer, func(dbReturn *types.ClassPrimaryAbility) *dtos.ClassPrimaryAbilityDTO { return dtos.ClassPrimaryAbilityToClassPrimaryAbilityDTO(db, dbReturn, []string{}) })
      
      ctx.IndentedJSON(http.StatusOK, returnBuffer)
      return
      
   } else {
      ctx.IndentedJSON(http.StatusBadRequest, err.Error())
      return
   }
}
