//*** CAUTION ***
//This is an autogenerated file produced by regenerateBackend.py.
//Edits made here will not persist after backend regeneration.

package generatedControllers
import (
   "github.com/gin-gonic/gin"
   "gorm.io/gorm"
   "strconv"
   "net/http"
   services "AdventureEngineServer/generatedServices"
   types "AdventureEngineServer/generatedDatabaseTypes"
   dtos "AdventureEngineServer/generatedDTOs"
)

func GetDomainActions(ctx *gin.Context, db *gorm.DB) {
   var serviceBuffer []types.DomainAction
   err := services.GetDomainActions(db, &serviceBuffer)
   if err != nil {
      ctx.IndentedJSON(http.StatusInternalServerError, err.Error())
      return
   }
   
   var returnBuffer []dtos.DomainActionDTO
   tableName := "DomainAction"
   for _, dbTypeInstance := range serviceBuffer {
      pointerToDTO := dtos.DomainActionToDomainActionDTO(db, &dbTypeInstance, &tableName)
      if (pointerToDTO != nil) {
         returnBuffer = append(returnBuffer, *pointerToDTO)
      }
   }
   ctx.IndentedJSON(http.StatusOK, returnBuffer)
}

func GetDomainActionById(ctx *gin.Context, db *gorm.DB) {
   id := ctx.Param("id")
   idNum, err := strconv.Atoi(id)
   if err != nil {
      ctx.IndentedJSON(http.StatusInternalServerError, err.Error())
      return
   }
   var serviceBuffer types.DomainAction
   err = services.GetDomainActionById(db, idNum, &serviceBuffer)
   if err != nil {
      ctx.IndentedJSON(http.StatusInternalServerError, err.Error())
      return
   }
   
   tableName := "DomainAction"
   returnBuffer := dtos.DomainActionToDomainActionDTO(db, &serviceBuffer, &tableName)
   ctx.IndentedJSON(http.StatusOK, returnBuffer)
}

func SaveDomainAction(ctx *gin.Context, db *gorm.DB) {
   var serviceBuffer types.DomainAction
   err := services.SaveDomainAction(db, &serviceBuffer)
   if err != nil {
      ctx.IndentedJSON(http.StatusInternalServerError, err.Error())
      return
   }
   
   tableName := "DomainAction"
   returnBuffer := dtos.DomainActionToDomainActionDTO(db, &serviceBuffer, &tableName)
   ctx.IndentedJSON(http.StatusOK, returnBuffer)
}
