//*** CAUTION ***
//This is an autogenerated file produced by regenerateBackend.py.
//Edits made here will not persist after backend regeneration.

package generatedControllers
import (
   "github.com/gin-gonic/gin"
   "gorm.io/gorm"
   "strconv"
   "net/http"
   services "AdventureEngineServer/generatedServices"
   types "AdventureEngineServer/generatedDatabaseTypes"
)

func GetDomainCharacterStats(ctx *gin.Context, db *gorm.DB) {
   var returnBuffer []types.DomainCharacterStat
   err := services.GetDomainCharacterStats(db, &returnBuffer)
   if err != nil {
      ctx.IndentedJSON(http.StatusInternalServerError, err.Error())
      return
   }
   ctx.IndentedJSON(http.StatusOK, returnBuffer)
}

func GetDomainCharacterStatById(ctx *gin.Context, db *gorm.DB) {
   id := ctx.Param("id")
   idNum, err := strconv.Atoi(id)
   if err != nil {
      ctx.IndentedJSON(http.StatusInternalServerError, err.Error())
      return
   }
   var returnBuffer types.DomainCharacterStat
   err = services.GetDomainCharacterStatById(db, idNum, &returnBuffer)
   if err != nil {
      ctx.IndentedJSON(http.StatusInternalServerError, err.Error())
      return
   }
   ctx.IndentedJSON(http.StatusOK, returnBuffer)
}

func SaveDomainCharacterStat(ctx *gin.Context, db *gorm.DB) {
   var returnBuffer types.DomainCharacterStat
   err := services.SaveDomainCharacterStat(db, &returnBuffer)
   if err != nil {
      ctx.IndentedJSON(http.StatusInternalServerError, err.Error())
      return
   }
   ctx.IndentedJSON(http.StatusOK, returnBuffer)
}
