//*** CAUTION ***
//This is an autogenerated file produced by regenerateBackend.py.
//Edits made here will not persist after backend regeneration.

package generatedControllers
import (
   "github.com/gin-gonic/gin"
   "gorm.io/gorm"
   "strconv"
   "net/http"
   services "AdventureEngineServer/generatedServices"
   types "AdventureEngineServer/generatedDatabaseTypes"
)

func GetDomainCreatureTypes(ctx *gin.Context, db *gorm.DB) {
   var returnBuffer []types.DomainCreatureType
   err := services.GetDomainCreatureTypes(db, &returnBuffer)
   if err != nil {
      ctx.IndentedJSON(http.StatusInternalServerError, err.Error())
      return
   }
   ctx.IndentedJSON(http.StatusOK, returnBuffer)
}

func GetDomainCreatureTypeById(ctx *gin.Context, db *gorm.DB) {
   id := ctx.Param("id")
   idNum, err := strconv.Atoi(id)
   if err != nil {
      ctx.IndentedJSON(http.StatusInternalServerError, err.Error())
      return
   }
   var returnBuffer types.DomainCreatureType
   err = services.GetDomainCreatureTypeById(db, idNum, &returnBuffer)
   if err != nil {
      ctx.IndentedJSON(http.StatusInternalServerError, err.Error())
      return
   }
   ctx.IndentedJSON(http.StatusOK, returnBuffer)
}

func SaveDomainCreatureType(ctx *gin.Context, db *gorm.DB) {
   var returnBuffer types.DomainCreatureType
   err := services.SaveDomainCreatureType(db, &returnBuffer)
   if err != nil {
      ctx.IndentedJSON(http.StatusInternalServerError, err.Error())
      return
   }
   ctx.IndentedJSON(http.StatusOK, returnBuffer)
}
