//*** CAUTION ***
//This is an autogenerated file produced by regenerateBackend.py.
//Edits made here will not persist after backend regeneration.

package generatedControllers
import (
   "github.com/gin-gonic/gin"
   "github.com/gin-gonic/gin/binding"
   "gorm.io/gorm"
   "strconv"
   "net/http"
   services "AdventureEngineServer/generatedServices"
   types "AdventureEngineServer/generatedDatabaseTypes"
   dtos "AdventureEngineServer/generatedDTOs"
   utils "AdventureEngineServer/utils"
)

func GetDomainDiceRollTypes(ctx *gin.Context, db *gorm.DB) {
   var serviceBuffer []types.DomainDiceRollType
   err := services.GetDomainDiceRollTypes(db, &serviceBuffer)
   if err != nil {
      ctx.IndentedJSON(http.StatusInternalServerError, err.Error())
      return
   }
   
   var returnBuffer []dtos.DomainDiceRollTypeDTO
   for _, dbTypeInstance := range serviceBuffer {
      pointerToDTO := dtos.DomainDiceRollTypeToDomainDiceRollTypeDTO(db, &dbTypeInstance, []string{})
      if (pointerToDTO != nil) {
         returnBuffer = append(returnBuffer, *pointerToDTO)
      }
   }
   ctx.IndentedJSON(http.StatusOK, returnBuffer)
}

func GetDomainDiceRollTypeById(ctx *gin.Context, db *gorm.DB) {
   id := ctx.Param("id")
   idNum, err := strconv.Atoi(id)
   if err != nil {
      ctx.IndentedJSON(http.StatusInternalServerError, err.Error())
      return
   }
   var serviceBuffer types.DomainDiceRollType
   err = services.GetDomainDiceRollTypeById(db, idNum, &serviceBuffer)
   if err != nil {
      ctx.IndentedJSON(http.StatusInternalServerError, err.Error())
      return
   }
   
   returnBuffer := dtos.DomainDiceRollTypeToDomainDiceRollTypeDTO(db, &serviceBuffer, []string{})
   ctx.IndentedJSON(http.StatusOK, returnBuffer)
}

func SaveDomainDiceRollType(ctx *gin.Context, db *gorm.DB) {
   //Weirdness with unmarshalling, cannot unmarshal into a nil pointer, there must be some pre-initialization somewhere along the line
   var DTOBuffer *dtos.DomainDiceRollTypeDTO = &dtos.DomainDiceRollTypeDTO{}
   var batchDTOBuffer []*dtos.DomainDiceRollTypeDTO
   var serviceBuffer []*types.DomainDiceRollType
   
   //If neither a single item nor a collection can be bound to JSON, fail early
   //ShouldBindBodyWith is used instead of ShouldBindJSON since the latter prevents multiple bind attempts
   if err := ctx.ShouldBindBodyWith(DTOBuffer, binding.JSON); err == nil {
      
      serviceBuffer = []*types.DomainDiceRollType{dtos.DomainDiceRollTypeDTOToDomainDiceRollType(DTOBuffer)}
      if err := services.SaveDomainDiceRollType(db, serviceBuffer); err != nil {
         ctx.IndentedJSON(http.StatusInternalServerError, err.Error())
         return
      }
      
      returnBuffer := dtos.DomainDiceRollTypeToDomainDiceRollTypeDTO(db, serviceBuffer[0], []string{})
      
      ctx.IndentedJSON(http.StatusOK, returnBuffer)
      return
      
   } else if err := ctx.ShouldBindBodyWith(&batchDTOBuffer, binding.JSON); err == nil {
      
      serviceBuffer = utils.Map(batchDTOBuffer, func(dto *dtos.DomainDiceRollTypeDTO) *types.DomainDiceRollType { return dtos.DomainDiceRollTypeDTOToDomainDiceRollType(dto) })
      if err := services.SaveDomainDiceRollType(db, serviceBuffer); err != nil {
         ctx.IndentedJSON(http.StatusInternalServerError, err.Error())
         return
      }
      
      returnBuffer := utils.Map(serviceBuffer, func(dbReturn *types.DomainDiceRollType) *dtos.DomainDiceRollTypeDTO { return dtos.DomainDiceRollTypeToDomainDiceRollTypeDTO(db, dbReturn, []string{}) })
      
      ctx.IndentedJSON(http.StatusOK, returnBuffer)
      return
      
   } else {
      ctx.IndentedJSON(http.StatusBadRequest, err.Error())
      return
   }
}
